Repository saltstack/salt, pull requests merged in 2018-08, with the labels that each got.

#48688 A new execution module: PeeringDB
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.peeringdb.rst
  salt/modules/peeringdb.py
  salt/utils/args.py
  tests/integration/files/file/base/_modules/runtests_helpers.py
Labels: Fluorine

#48344 allow using proxy minion from cli
  doc/ref/clients/index.rst
  salt/cli/caller.py
  salt/client/__init__.py
  salt/minion.py
  salt/utils/parsers.py
  salt/utils/platform.py
  tests/integration/proxy/test_shell.py
Labels: Fluorine

#48863 Decode file contents for python2 as well
  salt/states/file.py
Labels: Bugfix - back-port

#48779 Two new features for the napalm configuration management: commit_in and commit_at
  salt/modules/napalm_network.py
  salt/states/netconfig.py
  salt/utils/timeutil.py
Labels: Fluorine

#48730 Fix batch install on FreeBSD using pkgng
  salt/modules/pkgng.py
Labels: Bugfix - back-port

#48864 Remove support for virtual packages in the pkg state
  doc/topics/releases/fluorine.rst
  salt/states/pkg.py
Labels: Fluorine

#48660 [develop] Adding jids in master & minion logs
  doc/ref/configuration/logging/index.rst
  doc/topics/releases/fluorine.rst
  salt/config/__init__.py
  salt/log/setup.py
  salt/master.py
  salt/minion.py
  salt/utils/ctx.py
  salt/utils/decorators/jinja.py
  tests/integration/logging/__init__.py
  tests/integration/logging/test_jid_logging.py
  tests/runtests.py
Labels: Awesome, Fluorine, Tests Passed

#48912 make jboss7.py compatible with 2018.3.0 and later
  salt/states/jboss7.py
Labels: Bugfix - back-port

#46167 [develop] Removing deprecation warnings from client/mixins.py
  salt/client/mixins.py
Labels: Fluorine

#48909 Add napalm commit confirmed features
  salt/modules/napalm_mod.py
  salt/modules/napalm_network.py
  salt/states/netconfig.py
  salt/utils/napalm.py
Labels: Fluorine

#48361 Improve retcode reporting in salt/salt-call CLI commands
  doc/contents.rst
  doc/topics/development/dunder_dictionaries.rst
  doc/topics/return_codes/index.rst
  salt/cli/caller.py
  salt/cli/salt.py
  salt/defaults/exitcodes.py
  salt/minion.py
  salt/modules/state.py
  salt/modules/test.py
  tests/integration/shell/test_saltcli.py
Labels: Fluorine

#48832 Ability to set permissions in the Windows Registry
  salt/modules/win_file.py
  salt/states/reg.py
  salt/utils/win_dacl.py
  tests/unit/utils/test_win_dacl.py
Labels: Fluorine

#47718 Add file.tidied similar to Puppet's tidy resource.
  salt/states/file.py
  tests/unit/states/test_file.py
Labels: Fluorine

#48879 Adding an execution module providing helpers for the NAPALM formulas
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.napalm_formula.rst
  salt/modules/napalm_formula.py
  tests/unit/modules/test_napalm_formula.py
Labels: Fluorine

#47621 Runas any user even when shell is limited like winrm
  doc/topics/releases/fluorine.rst
  salt/modules/cmdmod.py
  salt/platform/__init__.py
  salt/platform/win.py
  salt/utils/win_runas.py
  tests/integration/utils/test_win_runas.py
  tests/support/helpers.py
Labels: Fluorine

#48852 Record all the artifacts from the build
  .ci/kitchen-centos7-py2
  .ci/kitchen-centos7-py3
  .ci/kitchen-ubuntu1604-py2
  .ci/kitchen-ubuntu1604-py3
Labels: Bugfix - back-port

#48910 Two more options added to the netbox Pillar, and use salt.utils.http
  salt/pillar/netbox.py
Labels: Fluorine

#48861 Add execution module to SCP files on devices where we can't install the Salt Minion
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.scp_mod.rst
  salt/modules/napalm_mod.py
  salt/modules/scp_mod.py
Labels: Fluorine

#48946 Fixed Python 3 incompatibility in methods in nilrt_ip and debian_ip.
  salt/modules/debian_ip.py
  salt/modules/nilrt_ip.py
Labels: Fluorine

#48919 Add new google_chat module
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.google_chat.rst
  doc/topics/releases/fluorine.rst
  salt/modules/google_chat.py
  tests/unit/modules/test_google_chat.py
Labels: Fluorine

#48948 Add force reconnection feature to NAPALM Proxy Minions
  salt/proxy/napalm.py
  salt/utils/napalm.py
Labels: Fluorine

#48970 [2017.7.8] Backport #48962
  tests/integration/modules/test_service.py
Labels: 2017.7.8

#48956 if booted from volume, use string from image
  salt/cloud/clouds/openstack.py
Labels: 2018.3.3

#48924 Support for virtual execution module pkg on AIX
  salt/modules/aixpkg.py
Labels: Fluorine

#48981 Add warning to mac runas docs about escaping characters
  doc/topics/releases/2018.3.3.rst
  salt/modules/cmdmod.py
  tests/integration/modules/test_cmdmod.py
Labels: 2018.3.3

#49007 Adding all the network automation changes and features to the Fluorine release notes
  doc/topics/releases/fluorine.rst
Labels: Fluorine

#48932 Fix pkg.install when pkg already installed
  salt/modules/win_pkg.py
  tests/unit/modules/test_win_pkg.py
Labels: 2018.3.3

#49041 [2017.7.8] backport PR #48212
  salt/cloud/clouds/ec2.py
Labels: 2017.7.8

#49044 increase timeout on vultr cloud integration test
  tests/integration/cloud/providers/test_vultr.py
Labels: 2017.7.8

#49026 Fix file.line line endings
  salt/utils/atomicfile.py
  tests/integration/states/test_file.py
Labels: 2018.3.3

#49052 Python 3.7 support (backport 2018.3)
  salt/client/__init__.py
  salt/client/api.py
  salt/client/mixins.py
  salt/cloud/clouds/msazure.py
  salt/cloud/clouds/profitbricks.py
  salt/cloud/clouds/xen.py
  salt/daemons/masterapi.py
  salt/engines/slack.py
  salt/master.py
  salt/minion.py
  salt/modules/cassandra_cql.py
  salt/modules/mandrill.py
  salt/modules/saltutil.py
  salt/netapi/rest_cherrypy/app.py
  salt/netapi/rest_cherrypy/event_processor.py
  salt/netapi/rest_tornado/event_processor.py
  salt/netapi/rest_tornado/saltnado.py
  salt/netapi/rest_tornado/saltnado_websockets.py
  salt/returners/cassandra_cql_return.py
  salt/runner.py
  salt/thorium/runner.py
  salt/thorium/wheel.py
  salt/transport/client.py
  salt/transport/ipc.py
  salt/transport/server.py
  salt/transport/tcp.py
  salt/utils/asynchronous.py
  salt/utils/event.py
  salt/utils/process.py
  salt/utils/thin.py
  salt/wheel/__init__.py
  tests/integration/files/engines/runtests_engine.py
  tests/integration/netapi/rest_tornado/test_app.py
  tests/support/case.py
  tests/unit/utils/test_async.py
Labels: 2018.3.3

#49032 add lxd tests
  requirements/tests.txt
  salt/modules/lxd.py
  salt/states/lxd.py
  salt/states/lxd_container.py
  salt/states/lxd_image.py
  tests/integration/states/test_lxd.py
  tests/integration/states/test_lxd_container.py
  tests/integration/states/test_lxd_image.py
  tests/integration/states/test_lxd_profile.py
Labels: Fluorine

#48070 [RFC] Refactor error messages to have better documented errors and to allow packagers to customize them in an easy way
  rfcs/0001-error_messages.md
Labels: RFC

#48945 Rethinking the way configuration management for network devices is handled
  salt/modules/napalm_network.py
  salt/states/netconfig.py
Labels: Fluorine, Tests Passed

#49075 fix last async issue
  tests/support/case.py
Labels: 2018.3.3, Bugfix - back-port, Fluorine

#49084 [2018.3] Update bootstrap script to latest release
  salt/cloud/deploy/bootstrap-salt.sh
Labels: 2018.3.3

#48623 Get multiple mines in single mine.get request
  salt/daemons/masterapi.py
  salt/modules/mine.py
  salt/utils/minions.py
  tests/unit/daemons/test_masterapi.py
Labels: Tests Passed

#49055 [2018.3] Merge forward from 2017.7 to 2018.3
  doc/ref/configuration/master.rst
  doc/ref/configuration/minion.rst
  salt/config/__init__.py
  salt/grains/core.py
  salt/loader.py
  salt/returners/highstate_return.py
  salt/states/netyang.py
  tests/integration/cloud/providers/test_vultr.py
  tests/integration/minion/test_pillar.py
  tests/integration/modules/test_grains.py
  tests/integration/modules/test_service.py
  tests/integration/netapi/test_client.py
  tests/integration/states/test_compiler.py
  tests/support/gitfs.py
  tests/unit/cloud/test_map_conf.py
  tests/unit/loader/test_loader.py
  tests/unit/output/test_highstate_out.py
  tests/unit/pillar/test_file_tree.py
  tests/unit/returners/test_smtp_return.py
  tests/unit/runners/test_winrepo.py
  tests/unit/templates/test_jinja.py
  tests/unit/test_pillar.py
  tests/unit/utils/test_sdb.py
Labels: 2018.3.3

#49077 Back-port #49075 to 2018.3
  tests/support/case.py
Labels: 2018.3.3

#49099 Back-port #49085 to 2018.3
  salt/minion.py
Labels: 2018.3.3

#49085 fix async call to process manager
  salt/minion.py
Labels: Bugfix - [Done] back-ported, Fluorine

#48901 [2018.3] fix to auth/ldap.py
  salt/auth/ldap.py
Labels: 2018.3.3

#48775 Log error when reactor tasks go to a full queue
  salt/utils/reactor.py
Labels: Tests Passed

#49108 salt/utils/cloud: fix crash issue. Thanks @rklaren
  salt/utils/cloud.py
Labels: Bugfix - back-port, Fluorine

#49124 remove brew from cask and info cmds
  salt/modules/mac_brew.py
Labels: Fluorine

#49121 Add pathstate to keepalive check in mac_service
  salt/modules/mac_service.py
  tests/unit/modules/test_mac_service.py
Labels: Fluorine

#49092 skip gpg tests if not installed
  tests/unit/modules/test_gpg.py
Labels: Fluorine

#49066 Add appoptics returner.
  salt/returners/appoptics_return.py
  tests/integration/returners/test_appoptics_return.py
Labels: Awesome

#47945 Add Azure DNS modules
  salt/modules/azurearm_dns.py
  salt/states/azurearm_dns.py
  salt/utils/azurearm.py
Labels: Needs Testcase

#49062 fix memoize on available macOS services
  salt/modules/mac_service.py
  salt/utils/mac_utils.py
  tests/unit/utils/test_mac_utils.py
Labels: 2018.3.3

#49142 Remove -Z script_arg for cloud tests
  tests/integration/files/conf/cloud.profiles.d/azure.conf
  tests/integration/files/conf/cloud.profiles.d/digitalocean.conf
  tests/integration/files/conf/cloud.profiles.d/ec2.conf
  tests/integration/files/conf/cloud.profiles.d/gogrid.conf
  tests/integration/files/conf/cloud.profiles.d/joyent.conf
  tests/integration/files/conf/cloud.profiles.d/linode.conf
  tests/integration/files/conf/cloud.profiles.d/rackspace.conf
Labels: 2018.3.3

#49132 [2018.3.3] backport PR #49062
  salt/modules/mac_service.py
  salt/utils/mac_utils.py
  tests/unit/utils/test_mac_utils.py
Labels: 2018.3.3

#49172 [2018.3.3] cherry pick #49118
  salt/modules/file.py
  salt/states/file.py
  tests/integration/states/test_file.py
Labels: 2018.3.3

#49170 force mine update on minion start
  salt/minion.py
Labels: Bugfix - back-port

#48873 [RFC] Terraform roster module to be used with terraform-provider-salt
  doc/ref/roster/all/index.rst
  doc/ref/roster/all/salt.roster.terraform.rst
  salt/roster/__init__.py
  salt/roster/flat.py
  salt/roster/terraform.py
  salt/utils/roster_matcher.py
  tests/unit/roster/terraform.data/ssh/salt-ssh.rsa
  tests/unit/roster/terraform.data/ssh_key
  tests/unit/roster/terraform.data/terraform.tfstate
  tests/unit/roster/test_terraform.py
Labels: Fluorine

#48545 Fix unreachable ssh-id-wrapper template when root_dir is relative
  salt/modules/git.py
Labels: Pending Discussion

#49239 Use yaml's safe_dump in windows ec2 tests
  tests/integration/cloud/providers/test_ec2.py
Labels: 2018.3.3

#49263 Revert default value for ipv6 to None
  salt/config/__init__.py
Labels: Tests Passed

#49253 skip ID 7 for vmware hard drives
  salt/cloud/clouds/vmware.py
Labels: Bugfix - back-port

#49294 Move run_function call from __init__ to setup
  tests/integration/modules/test_shadow.py
Labels: 2018.3.3

#49303 use os._exit instead of sys.exit when daemonizing
  salt/utils/process.py
Labels: 2018.3.3, Bugfix - back-port

#49311 Back-port #49303 to 2018.3.3
  salt/utils/process.py
Labels: 2018.3.3

#49313 Back-port #49236 to 2018.3.3
  salt/utils/minions.py
  tests/unit/utils/test_minions.py
Labels: 2018.3.3

#49323 Skip nonexistent branch test for git versions <1.7.10
  tests/integration/states/test_git.py
Labels: 2018.3.3

#48812 Use Adler32 algorithm to compute string checksums
  salt/config/__init__.py
  salt/grains/core.py
Labels: Pending Discussion

#49345 upgrade including linux kernels
  tests/integration/modules/test_pkg.py
Labels: Bugfix - back-port

#49347 [2018.3.3] Backport #49345
  tests/integration/modules/test_pkg.py
Labels: 2018.3.3

#49364 Back-port #49243 to 2018.3.3
  tests/unit/fileserver/test_roots.py
Labels: 2018.3.3

#49365 Back-port #49270 to 2018.3.3
  tests/unit/test_minion.py
Labels: 2018.3.3

#49362 Back-port #49240 to 2018.3.3
  tests/integration/states/test_file.py
Labels: 2018.3.3

#49361 Back-port #49244 to 2018.3.3
  salt/utils/files.py
  tests/unit/fileserver/test_gitfs.py
Labels: 2018.3.3

#49363 Back-port #49245 to 2018.3.3
  tests/unit/modules/test_file.py
Labels: 2018.3.3

#49368 Back-port #49322 to 2018.3.3
  salt/utils/timed_subprocess.py
  tests/integration/modules/test_state.py
Labels: 2018.3.3

#49376 Fix issue with duplicates in user.list_users on OSX
  pkg/osx/build_env.sh
  salt/modules/mac_user.py
  tests/unit/modules/test_mac_user.py
Labels: 2017.7.9, 2018.3.4

#49440 Back-port #49258 to 2018.3.3
  tests/integration/runners/test_state.py
  tests/integration/shell/test_call.py
Labels: 2018.3.3

#49442 Back-port #49180 and related fixes to 2018.3.3
  tests/unit/states/test_file.py
  tests/whitelist.txt
Labels: 2018.3.3

#49443 Back-port #49197 to 2018.3.3
  salt/modules/file.py
  tests/integration/states/test_file.py
Labels: 2018.3.3

#49445 Back-port #49192 to 2018.3.3
  tests/integration/modules/test_pip.py
  tests/integration/modules/test_system.py
Labels: 2018.3.3

#49446 Back-port #49356 to 2018.3.3
  salt/utils/timed_subprocess.py
Labels: 2018.3.3

#49448 Back-port #49400 to 2018.3.3
  tests/integration/modules/test_saltutil.py
Labels: 2018.3.3

#49444 Back-port #49299 to 2018.3.3
  tests/integration/states/test_file.py
Labels: 2018.3.3

#49449 Mark status test as flaky
  tests/integration/modules/test_status.py
Labels: 2018.3.3

#49461 Revert "Allow for not being prompted to supply a password to deploy keys to a…"
  salt/client/ssh/__init__.py
  salt/utils/parsers.py
  tests/integration/ssh/test_key_deploy.py
Labels: 2017.7.8, Bugfix - back-port

#49466 Back-port #49461 to 2017.7.8
  salt/client/ssh/__init__.py
  salt/utils/parsers.py
  tests/integration/ssh/test_key_deploy.py
Labels: 2017.7.8

#49468 Back-port #49291 and #49331 to 2018.3.3
  tests/integration/states/test_file.py
  tests/support/helpers.py
Labels: 2018.3.3

#49467 Back-port #49451 to 2018.3.3
  salt/scripts.py
  salt/utils/odict.py
Labels: 2018.3.3

#49473 Use correct and explicit paths for salt utils libs
  salt/states/boto3_route53.py
Labels: Bugfix - back-port
