Repository saltstack/salt, pull requests merged in 2018-07, with the labels that each got.

#48356 Adding a pair of proxy and execution modules for managing Arista switches via the pyeapi
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.arista_pyeapi.rst
  doc/ref/proxy/all/index.rst
  doc/ref/proxy/all/salt.proxy.arista_pyeapi.rst
  salt/modules/arista_pyeapi.py
  salt/proxy/arista_pyeapi.py
  salt/utils/args.py
Labels: Awesome

#48707 Add several new functions to the napalm module
  salt/modules/napalm_mod.py
Labels: Awesome

#48757 Update carbon_return.py
  salt/returners/carbon_return.py
Labels: Bugfix - back-port

#48617 modules/nilrt_ip.py: Add EtherCAT Support
  salt/modules/nilrt_ip.py
Labels: Fluorine

#48631 [RFC] add rfc for loader changes in Fluorine
  rfcs/0001-adding-package-logic-to-loader.md
Labels: RFC

#48842 modules/nilrt_ip.py: Fix _get_adapter_mode
  salt/modules/nilrt_ip.py
Labels: Fluorine
