Repository saltstack/salt, pull requests merged in 2018-09, with the labels that each got.

#49477 Check if service exists first in service.status for mac
  salt/modules/mac_service.py
Labels: Fluorine

#49478 Test fixes
  salt/modules/pip.py
  salt/platform/win.py
  tests/integration/files/file/base/issue-30161.sls
  tests/integration/modules/test_state.py
  tests/integration/states/test_reg.py
Labels: Fluorine

#49498 Pin CherryPy version to < 18.0.0 in requirements files for PY2
  requirements/opt.txt
  requirements/tests.txt
Labels: 2017.7.8

#49499 Pin CherryPy version to < 18.0.0 in requirements files for PY2
  requirements/opt.txt
  requirements/tests.txt
Labels: 2018.3.3

#49505 Update 2017.7.8 ChangeLog with new fixes
  doc/topics/releases/2017.7.8.rst
Labels: 2017.7.8

#49510 virt: allow defining the VM type and arch when creating it
  salt/modules/virt.py
  salt/states/virt.py
  salt/templates/virt/libvirt_domain.jinja
  tests/unit/modules/test_virt.py
  tests/unit/states/test_virt.py
Labels: Bugfix - back-port

#49535 Skip test_virt and pip_state requirements tests on macosx
  tests/integration/states/test_pip_state.py
  tests/integration/states/test_virtualenv.py
Labels: 2018.3.3

#49536 Back-port #49524 to 2018.3.3
  tests/unit/modules/test_boto_elb.py
  tests/unit/modules/test_boto_route53.py
  tests/unit/modules/test_boto_secgroup.py
  tests/unit/modules/test_boto_vpc.py
Labels: 2018.3.3

#49518 Skip service module integration tests on CentOS 7
  tests/integration/modules/test_service.py
Labels: Bugfix - back-port

#49548 [2018.3] Disabling State boto tests for Python 3.7+
  tests/unit/states/test_boto_vpc.py
Labels: Bugfix - [Done] back-ported

#49550 Back-port #49548 to 2018.3.3
  tests/unit/states/test_boto_vpc.py
Labels: 2018.3.3

#49560 [2017.7.8] Use correct path for is_true function
  salt/modules/pkgng.py
Labels: 2017.7.8

#49546 Skip flaky test on Python 3
  tests/unit/serializers/test_serializers.py
Labels: Bugfix - back-port

#49576 Use __utils__ in mac_system to ensure context is packed in
  salt/modules/mac_system.py
Labels: Fluorine

#49589 Update old utils paths to use new utils paths
  tests/integration/states/test_file.py
  tests/support/helpers.py
Labels: 2018.3.3

#49594 Back-port #49580 to 2018.3.3
  salt/grains/iscsi.py
  salt/modules/ini_manage.py
  tests/integration/states/test_file.py
  tests/unit/cache/test_localfs.py
  tests/unit/grains/test_iscsi.py
  tests/unit/modules/test_genesis.py
  tests/unit/modules/test_puppet.py
  tests/unit/utils/test_stringutils.py
Labels: 2018.3.3

#49580 [2018.3] Fixing tests for Python 3.7
  salt/grains/iscsi.py
  salt/modules/ini_manage.py
  tests/integration/states/test_file.py
  tests/unit/cache/test_localfs.py
  tests/unit/grains/test_iscsi.py
  tests/unit/modules/test_genesis.py
  tests/unit/modules/test_puppet.py
  tests/unit/utils/test_stringutils.py
Labels: Bugfix - [Done] back-ported

#49632 [2018.3] Fixing integration.states.test_file.FileTest.test_directory_max_depth
  tests/integration/states/test_file.py
Labels: Bugfix - back-port

#49641 Back-port #49632 to 2018.3.3
  tests/integration/states/test_file.py
Labels: 2018.3.3

#49568 Skip reverse patch integration tests for version <2.6.1
  tests/integration/states/test_file.py
Labels: Fluorine

#49655 Fix windows test whitelist errors
  tests/whitelist.txt
Labels: 2018.3.3

#49555 Change StringIO and BytesIO imports
  salt/modules/hashutil.py
Labels: Bugfix - back-port

#49703 Detect when system needs reboot after domain join (2017.7)
  salt/modules/win_system.py
Labels: 2017.7.9

#49684 Detect when system needs reboot after domain join
  salt/modules/win_system.py
  salt/utils/win_reg.py
  tests/integration/modules/test_system.py
Labels: 2018.3.4

#49741 Add Changelog for 2018.3.3
  doc/topics/releases/2018.3.3.rst
Labels: 2018.3.3

#49714 [salt-cloud] add parameters for VM clone in proxmox driver
  salt/cloud/clouds/proxmox.py
Labels: Bugfix - back-port

#49728 zsh-completion: strip out u'' unicode __repr__ of function names
  pkg/zsh_completion.zsh
Labels: Bugfix - back-port

#49761 Handle Auth exceptions in run_job
  salt/client/__init__.py
  tests/integration/netapi/rest_tornado/test_app.py
Labels: 2018.3.3

#49759 runners.state.orch: generate jid if missing
  salt/runners/state.py
Labels: Bugfix - back-port

#49824 Skip test_local_pkg_install for now: this is causing the test suite to hang
  tests/integration/shell/test_call.py
Labels: Bugfix - [Done] back-ported

#49763 Add ability to clear DNS entries on static DNS
  salt/modules/win_ip.py
  salt/states/win_network.py
  tests/unit/modules/test_win_ip.py
  tests/unit/states/test_win_network.py
Labels: 2017.7.9, 2018.3.4
