Repository saltstack/salt, pull requests merged in 2018-06, with the labels that each got.

#47913 Fixup! beacons/avahi_announce.py finding grains
  salt/beacons/avahi_announce.py
Labels: Bugfix - back-port

#47725 network_settings beacon: Update example to follow new cfg convention
  salt/beacons/network_settings.py
Labels: Bugfix - back-port

#47544 Multi-command salt calls return highest exit
  salt/cli/salt.py
Labels: Tests Passed

#47923 Prevent crash if files in file.recurse
  salt/modules/state.py
Labels: Bugfix - back-port

#47957 [2018.8] Ensure x509 passphrase is a string
  salt/modules/x509.py
  tests/unit/modules/test_x509.py
Labels: 2018.3.1

#47827 Fix issue when archive is on mapped drive
  salt/states/archive.py
Labels: 2017.7.7, 2018.3.2

#47677 fix states.alternatives.install to really install alternative
  salt/states/alternatives.py
  tests/unit/states/test_alternatives.py
Labels: Tests Passed

#47983 [2017.7] Backporting #47843
  salt/states/saltmod.py
  tests/integration/files/file/base/orch/issue30367/init.sls
  tests/integration/runners/test_state.py
Labels: 2017.7.7

#48040 states/github.py fix for incorrect positional argument
  salt/states/github.py
Labels: Bugfix - back-port

#47851 Fixup! add master.py:FileserverUpdate **kwargs
  salt/master.py
Labels: Bugfix - back-port

#47442 Add attachment support to SMTP state and module
  salt/modules/smtp.py
  salt/states/smtp.py
Labels: Tests Passed

#48097 Back-port #48075 to 2018.3.2
  salt/minion.py
Labels: 2018.3.2

#48098 Back-port #48075 to 2017.7.7
  salt/minion.py
Labels: 2017.7.7

#48099 Back-port #47915 to 2018.3.2
  salt/runners/state.py
  tests/integration/runners/test_state.py
Labels: 2018.3.2

#48100 Back-port #48014 to 2018.3.2
  salt/runners/jobs.py
Labels: 2018.3.2

#48134 Add release notes file for 2017.7.7
  doc/topics/releases/2017.7.7.rst
Labels: 2017.7.7

#48158 always listen when gathering job info
  salt/client/__init__.py
Labels: 2018.3.2

#48157 always listen when gathering job info
  salt/client/__init__.py
Labels: 2017.7.7

#48172 Update release notes for 2017.7.7
  doc/topics/releases/2017.7.7.rst
Labels: 2017.7.7

#48171 Update release notes for 2018.3.2
  doc/topics/releases/2018.3.2.rst
Labels: 2018.3.2

#48189 If pip binary is passed to bin_env, use that pip binary
  salt/modules/pip.py
  tests/integration/modules/test_pip.py
Labels: Bugfix - back-port

#48258 preserve tuples for ldap modification operations
  salt/modules/ldap3.py
Labels: Bugfix - back-port

#48193 Properly wait on returns in saltnado
  salt/netapi/rest_tornado/saltnado.py
  tests/integration/netapi/rest_tornado/test_app.py
Labels: Bugfix - back-port

#48288 fix lsattr.get in file.check_perms
  salt/modules/file.py
Labels: 2017.7.8, Bugfix - back-port

#48215 Notify during tests using different credentials
  .ci/docs
  .ci/kitchen-centos7-py2
  .ci/kitchen-centos7-py3
  .ci/kitchen-ubuntu1604-py2
  .ci/kitchen-ubuntu1604-py3
  .ci/lint
Labels: Bugfix - back-port
