Repository saltstack/salt, pull requests merged in 2018-05, with the labels that each got.

#47405 Fix file.get_diff regression in 2018.3 branch
  salt/modules/file.py
  tests/unit/modules/test_file.py
Labels: 2018.3.1

#47403 Back-port #47356 to 2018.3
  salt/modules/linux_sysctl.py
Labels: 2018.3.1

#47375 Warn on use of virtual packages in pkg.installed state
  salt/states/pkg.py
Labels: 2017.7.6

#47399 zeromq 17 deprecation warning backport from 2018.3 + tornado 5 fixes
  salt/client/__init__.py
  salt/client/ssh/__init__.py
  salt/daemons/flo/zero.py
  salt/engines/napalm_syslog.py
  salt/master.py
  salt/minion.py
  salt/transport/zeromq.py
  salt/utils/async.py
  salt/utils/cache.py
  salt/utils/master.py
  salt/utils/zeromq.py
  tests/integration/netapi/rest_tornado/test_app.py
Labels: 2017.7.6

#47410 gitfs: Fix identification of base env when saltenv mapping is disabled
  salt/utils/gitfs.py
  tests/unit/fileserver/test_gitfs.py
Labels: 2018.3.1

#47354 fix forward port of #46751
  salt/state.py
Labels: 2018.3.1, Bugfix - back-port

#47465 Back-port #47354 to 2018.3
  salt/state.py
Labels: 2018.3.1

#47482 add all autodoc for new salt openstack modules
  doc/ref/modules/all/salt.modules.glanceng.rst
  doc/ref/modules/all/salt.modules.keystoneng.rst
  doc/ref/modules/all/salt.modules.neutronng.rst
  doc/ref/states/all/salt.states.glance_image.rst
  doc/ref/states/all/salt.states.keystone_domain.rst
  doc/ref/states/all/salt.states.keystone_endpoint.rst
  doc/ref/states/all/salt.states.keystone_group.rst
  doc/ref/states/all/salt.states.keystone_project.rst
  doc/ref/states/all/salt.states.keystone_role.rst
  doc/ref/states/all/salt.states.keystone_role_grant.rst
  doc/ref/states/all/salt.states.keystone_service.rst
  doc/ref/states/all/salt.states.keystone_user.rst
  doc/ref/states/all/salt.states.neutron_network.rst
  doc/ref/states/all/salt.states.neutron_secgroup.rst
  doc/ref/states/all/salt.states.neutron_secgroup_rule.rst
  doc/ref/states/all/salt.states.neutron_subnet.rst
Labels: 2018.3.1

#47507 fix win_task for py3
  salt/modules/win_task.py
Labels: 2018.3.1, ZD

#47517 Back-port #47505 to 2017.7.6
  salt/modules/win_dsc.py
Labels: 2017.7.6

#47515 Back-port #47503 to 2018.3
  salt/modules/freebsdservice.py
Labels: 2018.3.1

#47516 Back-port #47505 to 2018.3
  salt/modules/win_dsc.py
Labels: 2018.3.1

#47514 [2018.3] Merge forward from 2017.7 to 2018.3
  .kitchen.yml
  doc/_ext/youtube.py
  doc/topics/releases/2017.7.6.rst
  pkg/windows/modules/get-settings.psm1
  requirements/base-py2.txt
  requirements/base-py3.txt
  salt/modules/cmdmod.py
  salt/modules/pip.py
  salt/modules/virtualenv_mod.py
  salt/modules/win_lgpo.py
  salt/states/pip_state.py
  salt/states/virtualenv_mod.py
  tests/integration/files/file/base/issue-1959-virtualenv-runas/init.sls
  tests/integration/modules/test_pip.py
  tests/integration/states/test_pip.py
  tests/support/helpers.py
  tests/unit/modules/test_pip.py
  tests/unit/states/test_pip.py
  tests/whitelist.txt
Labels: 2018.3.1

#47159 Fix for whitelist/blacklist checking for non-list iterables
  salt/utils/stringutils.py
  tests/unit/utils/test_stringutils.py
Labels: 2018.3.1

#47224 Zpool zol fixes
  salt/modules/zpool.py
  tests/unit/modules/test_zpool.py
Labels: Bugfix - back-port

#47440 fix for the race condition, details are here: https://github.com/salt…
  salt/fileclient.py
  salt/utils/thin.py
Labels: Bugfix - back-port

#47568 salt.serializers.yaml/yamlex: remove invalid multi_constructor
  salt/serializers/yaml.py
  salt/serializers/yamlex.py
Labels: Bugfix - back-port

#47599 Back-port #47570 to 2018.3.1
  requirements/base.txt
Labels: 2018.3.1

#47595 Back-port #47569 to 2018.3.1
  tests/unit/grains/test_core.py
Labels: 2018.3.1

#47596 Back-port #47568 to 2018.3.1
  salt/serializers/yaml.py
  salt/serializers/yamlex.py
Labels: 2018.3.1

#47646 Back-port #47601 and #47643 to 2017.7.6
  tests/integration/states/test_pip.py
Labels: 2017.7.6

#47647 Back-port #47601 and #47643 to 2018.3.1
  tests/integration/states/test_pip.py
Labels: 2018.3.1

#47645 query the pip path for test test_issue_2087_missing_pip
  tests/integration/modules/test_pip.py
  tests/integration/states/test_pip.py
Labels: 2017.7.6, 2018.3.1, Bugfix - back-port

#47664 Back-port #47645 to 2018.3.1
  tests/integration/modules/test_pip.py
  tests/integration/states/test_pip.py
Labels: 2018.3.1

#47487 bad ref to error fix
  salt/states/docker_image.py
Labels: Bugfix - back-port

#45808 [bugfix] Fix for oversized filenames in fileclient
  salt/fileclient.py
  tests/unit/test_fileclient.py
Labels: Bugfix - back-port

#47706 Add cmd._run_all_quiet to mac_utils and __utils__ in mac_service
  salt/modules/mac_service.py
  salt/utils/mac_utils.py
Labels: 2018.3.1

#47541 switch skip-roster to update-roster
  conf/master
  doc/topics/releases/2018.3.1.rst
  salt/client/ssh/__init__.py
  salt/utils/parsers.py
Labels: 2018.3.1

#47703 Fix elasticsearch.index_template_present with check_definition
  salt/states/elasticsearch.py
Labels: Bugfix - back-port

#47641 fix _create_stream and tornado 5.0
  requirements/base.txt
  salt/transport/tcp.py
Labels: 2018.3.1

#47700 fix roots modification time check
  salt/fileserver/roots.py
Labels: 2017.7.6, 2018.3.1, Bugfix - [Done] back-ported

#47729 fix cli example to match function name
  salt/modules/win_system.py
Labels: Documentation

#47736 mac_utils test: patch __salt__['cmd.run*']
  tests/unit/utils/test_mac_utils.py
Labels: 2018.3.1

#47727 Fix salt.utils.versions.warn_until spelling
  salt/modules/kubernetes.py
  salt/modules/pip.py
  salt/states/kubernetes.py
  salt/states/pip_state.py
  salt/states/virtualenv_mod.py
  salt/states/win_servermanager.py
  salt/utils/cloud.py
  tests/unit/utils/test_versions.py
Labels: 2018.3.1

#47740 [2018.3] Updating Beacon topic to include list based configuration for Beacons
  doc/topics/beacons/index.rst
Labels: Documentation

#47730 Back-port #47700 to 2018.3.1
  salt/fileserver/roots.py
Labels: 2018.3.1

#47739 Back-port #47702 to 2018.3.1
  salt/states/pkg.py
Labels: 2018.3.1

#47724 2 master_tops/ext_nodes fixes
  salt/fileclient.py
  salt/fileserver/__init__.py
Labels: 2018.3.1

#47761 Fix userdata in openstack instances
  salt/cloud/clouds/openstack.py
Labels: Bugfix - back-port

#47769 skip test that breaks test suite
  tests/unit/modules/test_cmdmod.py
Labels: 2017.7.7, 2018.3.1, Bugfix - [Done] back-ported

#47775 catch UnsupportedOperation with AssertionError
  salt/output/__init__.py
Labels: 2017.7.6, Bugfix - back-port

#47782 Back-port #47775 to 2018.3.1
  salt/output/__init__.py
Labels: 2018.3.1

#47776 [2018.3] Fixes to failing _before_connect tests
  tests/unit/test_minion.py
Labels: 2018.3.1, Bugfix - [Done] back-ported

#47798 Back-port #47776 to 2018.3.1
  tests/unit/test_minion.py
Labels: 2018.3.1

#47820 Remove output_loglevel in mac_system module
  salt/modules/mac_system.py
Labels: 2018.3.1

#47810 Fix Linode plan selection
  salt/cloud/clouds/linode.py
Labels: Bugfix - back-port

#47873 allow tornado 5.0 to be installed only for python2
  doc/topics/releases/2017.7.6.rst
  requirements/base.txt
Labels: 2017.7.6

#47874 Tornado 5.0 is only supported on python 2 for now
  doc/topics/releases/2017.7.6.rst
  doc/topics/releases/2018.3.1.rst
  requirements/base.txt
Labels: 2018.3.1

#47875 Update 2017.7.6 release notes: remove "unreleased" text
  doc/topics/releases/2017.7.6.rst
Labels: 2017.7.6

#47848 Fix some major issues with the LGPO module
  salt/modules/win_lgpo.py
Labels: 2018.3.1, Blocker

#47843 [2018.3] orchestration results False when function is False
  salt/states/saltmod.py
  tests/integration/files/file/base/orch/issue30367/init.sls
  tests/integration/runners/test_state.py
Labels: Bugfix - back-port
