Repository saltstack/salt, pull requests merged in 2018-12, with the labels that each got.

#50740 Catch UnicodeDecodeErrors in id verification
  salt/utils/verify.py
Labels: Bugfix - back-port

#50353 Virtual module interface concept
  rfcs/0003-api-unification.md
Labels: RFC

#50086 Make win_groupadd module behave like other modules
  salt/modules/win_groupadd.py
  tests/unit/modules/test_win_groupadd.py
Labels: Fluorine

#50780 Add netsh mechanism in the LGPO module
  salt/modules/win_firewall.py
  salt/modules/win_lgpo.py
  salt/states/win_lgpo.py
  salt/utils/win_lgpo_netsh.py
  tests/unit/utils/test_win_lgpo_netsh.py
Labels: 2018.3.4, Fluorine

#50617 Capabilities RFC
  rfcs/minion-capabilitles.md
Labels: RFC

#49622 fix command line options
  salt/modules/archive.py
Labels: Bugfix - back-port

#50053 introduce a concept of a reactor 'leader'
  salt/runners/reactor.py
  salt/utils/reactor.py
  tests/integration/__init__.py
  tests/integration/files/reactor-test.sls
  tests/integration/reactor/test_reactor.py
Labels: Awesome

#50959 #46886: Use correct path to config_dir when running salt from alternate placement.
  salt/executors/sudo.py
Labels: Bugfix - back-port

#50885 fix a del in cloud vmware that crash when the key isn't there
  salt/cloud/clouds/vmware.py
Labels: Bugfix - [Done] back-ported
