Repository saltstack/salt, pull requests merged in 2018-02, with the labels that each got.

#45928 [2017.7] Fixing vault when used with pillar over salt-ssh
  salt/utils/vault.py
Labels: Bugfix - back-port

#45931 Fix publisher_acl for oxygen
  salt/cli/daemons.py
  salt/cli/salt.py
  salt/client/__init__.py
  salt/config/__init__.py
  salt/daemons/masterapi.py
  salt/key.py
  salt/runner.py
  salt/utils/parsers.py
  salt/utils/verify.py
  tests/unit/utils/test_verify.py
Labels: oxygen.rc1

#45950 Back-port #45902 to oxygen.rc1
  salt/states/archive.py
  salt/states/file.py
  tests/integration/files/file/prod/issue45893/custom.tar.gz
  tests/integration/files/file/prod/issue45893/init.sls
  tests/integration/states/test_archive.py
Labels: oxygen.rc1

#45797 follow symlinks in aliases module (close #45796)
  salt/modules/aliases.py
Labels: Bugfix - back-port

#45462 emit port cli version, variants as separate args
  salt/modules/mac_ports.py
Labels: Bugfix - back-port

#45826 Fix selinux.fcontext_policy_present for Centos 6
  salt/modules/selinux.py
Labels: Bugfix - back-port

#45785 m/selinux.fcontext_get_policy allow long filespecs
  salt/modules/selinux.py
  tests/unit/modules/test_selinux.py
Labels: Bugfix - back-port

#44892 Force Salt's YAML loader to load all strings as unicode types
  salt/utils/yamlloader.py
  tests/unit/utils/test_yamlloader.py
Labels: Tests Passed, oxygen.rc1

#45979 Unicode/logger fix + bugfix: salt/utils/parsers
  salt/utils/parsers.py
  tests/support/mock.py
  tests/unit/utils/test_parsers.py
Labels: oxygen.rc1

#46000 salt.states.reg.present: Prevent traceback when reg data is binary
  salt/states/reg.py
Labels: Bugfix - back-port, Pending Discussion, oxygen.rc1

#45991 yumpkg: Fix a couple issues with _get_extra_opts
  salt/modules/yumpkg.py
  tests/unit/modules/test_yumpkg.py
Labels: Bugfix - back-port, oxygen.rc1

#46043 Allow zookeeper znode creation to not require an ACL
  salt/states/zookeeper.py
Labels: Bugfix - back-port

#45811 Fix ldap eauth
  salt/auth/ldap.py
  tests/unit/auth/__init__.py
  tests/unit/auth/test_ldap.py
Labels: Tests Passed, oxygen.rc1

#45994 Fix hosted zone Comment updates & quote TXT entries correctly
  salt/states/boto3_route53.py
Labels: Bugfix - back-port

#46036 git.latest: Fix regression with identity file usage
  pkg/windows/build_pkg.bat
  salt/modules/git.py
  salt/modules/ssh.py
  salt/utils/ssh.py
  tests/unit/modules/test_git.py
Labels: Bugfix - back-port, oxygen.rc1

#45932 Fix cmd run_all bg error
  salt/modules/cmdmod.py
Labels: Bugfix - back-port, oxygen.rc1

#46056 Fix mac_assistive module not loading
  salt/modules/mac_assistive.py
Labels: Bugfix - back-port, oxygen.rc1

#46066 Pin tornado version in requirements file
  requirements/base.txt
Labels: Bugfix - back-port, oxygen.rc1

#46094 Fix memory leak
  salt/netapi/rest_tornado/saltnado.py
  salt/transport/ipc.py
Labels: Bugfix - back-port, oxygen.rc1

#46088 fix kernel subpackages install bug
  salt/modules/yumpkg.py
Labels: Bugfix - back-port

#46115 update digitalocean salt-cloud driver
  salt/cloud/clouds/digitalocean.py
Labels: Bugfix - back-port

#46123 If no pubkey is passed in openmode fail
  salt/transport/mixins/auth.py
Labels: Bugfix - back-port, oxygen.rc1

#45911 LGPO Module: Convert reg values to unicode for debug
  salt/modules/win_lgpo.py
Labels: Bugfix - back-port, oxygen.rc1

#46005 pass opts to SSHClient for enable_ssh_minions
  salt/client/ssh/__init__.py
  salt/config/__init__.py
  salt/master.py
  salt/utils/minions.py
  tests/integration/__init__.py
  tests/integration/cli/test_batch.py
  tests/integration/files/conf/_ssh/syndic_roster
  tests/integration/files/conf/master
  tests/integration/files/conf/syndic_master
  tests/integration/netapi/rest_tornado/test_app.py
  tests/integration/netapi/test_client.py
  tests/integration/runners/test_state.py
  tests/integration/shell/test_cp.py
  tests/integration/ssh/test_master.py
Labels: oxygen.rc1

#46145 3 small fixes for runners/orchestration
  doc/topics/orchestrate/orchestrate_runner.rst
  salt/runner.py
  salt/runners/pillar.py
  salt/state.py
  salt/utils/jinja.py
  tests/unit/modules/test_file.py
  tests/unit/templates/test_jinja.py
Labels: Bugfix - [Done] back-ported, oxygen.rc1

#46148 [2017.7] Merge forward from 2017.7.3 to 2017.7
  doc/topics/releases/2017.7.4.rst
  salt/modules/git.py
  salt/modules/ssh.py
  salt/utils/ssh.py
  tests/unit/modules/test_git.py
Labels: Tests Passed

#46221 Fix hanging tests in integration suite
  tests/integration/modules/test_cp.py
Labels: 2018.3.0rc1, Bugfix - back-port

#46217 fix ssh integration test with enable_ssh_minions
  tests/integration/ssh/test_master.py
Labels: 2018.3.0rc1

#46256 Don't install msgpack 0.5.5
  requirements/base.txt
Labels: Bugfix - back-port
