Repository saltstack/salt, pull requests merged in 2018-10, with the labels that each got.

#48666 values need to be bytes when writing back to ldap
  salt/modules/ldap3.py
Labels: Bugfix - back-port

#49798 saltnado: teach runner about full_return
  salt/netapi/rest_tornado/saltnado.py
Labels: Bugfix - back-port

#49862 move tests that exercise missing minions into local setup/teardown
  tests/integration/files/pillar/base/top.sls
  tests/integration/minion/test_pillar.py
Labels: Bugfix - back-port

#49891 Add salt_version execution module
  doc/topics/releases/version_numbers.rst
  salt/modules/salt_version.py
  tests/unit/modules/test_salt_version.py
Labels: Awesome

#49739 Populate changes dictionary on system.join_domain
  salt/states/win_system.py
Labels: 2017.7.9, 2018.3.4

#49899 Remove arrInstalled artifact
  pkg/windows/build_env_2.ps1
  pkg/windows/build_env_3.ps1
Labels: 2017.7.9, 2018.3.4

#49872 Fix issues with windows file permissions when using reset=True
  salt/modules/win_file.py
  salt/utils/win_functions.py
  tests/unit/modules/test_win_file.py
Labels: 2018.3.4

#49940 Clean up documentation/language in service state. (Fixes #40819)
  salt/states/at.py
  salt/states/cmd.py
  salt/states/docker_container.py
  salt/states/docker_image.py
  salt/states/etcd_mod.py
  salt/states/kernelpkg.py
  salt/states/mount.py
  salt/states/pkg.py
  salt/states/service.py
  salt/states/supervisord.py
  salt/states/tomcat.py
Labels: Bugfix - back-port

#49958 [fluorine] Fixes to mac_system.py
  salt/modules/mac_system.py
Labels: Bugfix - back-port

#49950 Fix file patch tests on CentOS 6
  tests/integration/states/test_file.py
Labels: Fluorine

#49966 Fix quoting issue when passing extra_vars to ansible-playbook
  salt/modules/ansiblegate.py
Labels: Bugfix - back-port

#49943 Coerce string when calling compile_template_str
  salt/pillar/file_tree.py
Labels: Bugfix - back-port

#49977 Fix nova module cooperation with python-novaclient
  salt/modules/nova.py
  salt/utils/openstack/nova.py
Labels: Bugfix - back-port

#50019 runtests.py: Accept modified file list from a text file
  tests/support/parser/__init__.py
Labels: Bugfix - back-port

#50044 add saltclass info from release notes to docs
  doc/ref/pillar/all/index.rst
  doc/ref/pillar/all/salt.pillar.saltclass.rst
  doc/ref/tops/all/index.rst
  doc/ref/tops/all/salt.tops.saltclass.rst
  salt/pillar/saltclass.py
  salt/tops/saltclass.py
Labels: Bugfix - back-port

#50022 Make test check_pillar more lenient
  salt/states/test.py
  tests/unit/states/test_test.py
Labels: Bugfix - back-port

#50069 Fix `unit.modules.test_virt` for Windows
  tests/unit/modules/test_virt.py
Labels: Fluorine

#49611 Moved Community section of the index to its own topic
  doc/contents.rst
  doc/topics/community/index.rst
  doc/topics/index.rst
Labels: Documentation

#50061 pkg.install bugfix
  salt/modules/yumpkg.py
  tests/unit/modules/test_yumpkg.py
Labels: Bugfix - back-port

#50005 script engine
  salt/engines/script.py
  tests/unit/engines/test_script.py
Labels: Awesome

#50117 Include the address of the client with the malformed message
  salt/transport/tcp.py
Labels: Awesome

#49980 Add support for AddPrinterDrivers
  salt/modules/win_lgpo.py
Labels: 2018.3.4

#50143 Fix #50142, stringutils.to_none
  salt/utils/stringutils.py
  tests/unit/utils/test_stringutils.py
Labels: Bugfix - back-port

#50140 Adding XCP-ng support
  salt/grains/core.py
  salt/modules/rh_service.py
Labels: Bugfix - back-port

#50146 Improve handling of non-ascii characters in terminal output. (Fixes: #49523)
  salt/utils/vt.py
Labels: Bugfix - back-port

#50021 Add a `windowsdomaintype` grain
  salt/grains/core.py
  salt/modules/win_system.py
  salt/utils/win_osinfo.py
  tests/unit/grains/test_core.py
  tests/unit/modules/test_win_system.py
  tests/unit/utils/test_win_osinfo.py
Labels: Fluorine

#50184 Added handling for minion return exceptions containing the word "return"
  salt/client/__init__.py
Labels: Needs Testcase

#50257 put variables in apostrophe in dracr module
  salt/modules/dracr.py
Labels: Bugfix - back-port

#50280 fix InstallRequirement.from_line for pip 18.1
  salt/states/pip_state.py
Labels: 2017.7.9, 2018.3.4

#50059 [develop] Initial work to allow running multiple instances of a Salt engine
  doc/topics/engines/index.rst
  doc/topics/releases/neon.rst
  salt/engines/__init__.py
  tests/unit/test_engines.py
Labels: Awesome

#50290 Fix `test_state` for Windows
  salt/utils/atomicfile.py
  salt/utils/win_dacl.py
Labels: 2018.3.4, Fluorine
