Repository saltstack/salt, pull requests merged in 2018-04, with the labels that each got.

#46769 Adding windows minion tests for salt cloud
  salt/cloud/clouds/ec2.py
  salt/utils/cloud.py
  tests/integration/cloud/providers/test_ec2.py
  tests/integration/files/conf/cloud.profiles.d/ec2.conf
  tests/integration/files/windows-firewall-winexe.ps1
  tests/integration/files/windows-firewall.ps1
  tests/support/win_installer.py
Labels: 2017.7.6, 2018.3.1

#46641 Make LazyLoader thread safe
  salt/loader.py
Labels: Awesome

#46809 Fix sharedsecret authentication
  salt/auth/sharedsecret.py
Labels: Bugfix - [Done] back-ported

#46817 address filehandle/event leak in async run_job invocations
  salt/client/__init__.py
Labels: Bugfix - back-port

#46844 Fix warning format in 2018.3.0 release notes
  doc/topics/releases/2018.3.0.rst
Labels: Bugfix - back-port

#46801 rename jenkins to jenkinsmod
  salt/modules/jenkinsmod.py
Labels: Bugfix - back-port

#46874 Use bytestrings for PY3 compatibility when running setsockopt for zmq.SUBSCRIBE
  salt/utils/master.py
Labels: Bugfix - [Done] back-ported

#46933 Only very recent zfs support parsable output
  salt/grains/zfs.py
  salt/modules/zfs.py
  salt/modules/zpool.py
  tests/unit/modules/test_zfs.py
  tests/unit/modules/test_zpool.py
  tests/unit/utils/test_zfs.py
Labels: Bugfix - back-port

#46997 Fix respository (=> repository) typo in sls_build
  salt/modules/dockermod.py
Labels: Bugfix - back-port

#46930 Clean up bad public key headers
  salt/crypt.py
  tests/unit/test_crypt.py
Labels: 2018.3.1

#47029 ldapmod.py/ldap3.py: Force modlist for search/modify/etc. to be str types
  salt/modules/ldap3.py
  salt/modules/ldapmod.py
  salt/utils/data.py
  salt/utils/stringutils.py
  tests/unit/utils/test_data.py
Labels: 2018.3.1

#47121 fix pip import error in pip 10.0.0
  salt/states/pip_state.py
Labels: Bugfix - back-port

#47129 Back-port #47121 to 2017.7
  salt/states/pip_state.py
Labels: 2017.7.6, 2018.3.1

#46922 Add function to return TLS cert expiration date
  salt/modules/tls.py
  tests/unit/modules/test_tls.py
Labels: Has Testcase

#47287 convert unicode ssh pass to str for azure
  salt/cloud/clouds/azurearm.py
Labels: Bugfix - back-port

#47060 Return an empty dict for 'changes' instead of 'None'
  salt/states/boto_cfn.py
  salt/states/boto_iam.py
  salt/states/boto_iot.py
  salt/states/glassfish.py
  salt/states/grafana_datasource.py
  salt/states/influxdb_user.py
  tests/unit/states/test_grafana_datasource.py
Labels: Tests Passed

#47038 [2018.3] fix to fileclient.py
  salt/fileclient.py
  salt/version.py
Labels: 2018.3.1

#47248 forward merge #46520 to develop
  salt/minion.py
  salt/utils/schedule.py
Labels: Tests Passed

#47356 Fix sysctl translate
  salt/modules/linux_sysctl.py
Labels: 2017.7.6, 2018.3.1, Bugfix - back-port
