Repository saltstack/salt, pull requests merged in 2018-11, with the labels that each got.

#50329 Check WinRM port before initiating connection
  salt/utils/cloud.py
Labels: 2017.7.9, 2018.3.4, Fluorine

#50006 Correct more issues in lgpo
  salt/modules/win_lgpo.py
  tests/integration/modules/test_win_lgpo.py
Labels: 2018.3.4, Fluorine

#50346 Extend deprecation warning for enable_legacy_startup_events to Sodium
  conf/minion
  doc/ref/configuration/minion.rst
  doc/topics/releases/fluorine.rst
  salt/config/__init__.py
  salt/minion.py
Labels: Fluorine

#50339 The driver requires dependency, not the other way around.
  salt/config/__init__.py
Labels: Bugfix - back-port

#50228 Fix 50227 malformed plists
  salt/utils/mac_utils.py
  tests/unit/utils/test_mac_utils.py
Labels: Bugfix - back-port

#50272 Fix out of order docker Env comparison
  salt/modules/dockermod.py
  tests/unit/modules/test_dockermod.py
Labels: Bugfix - back-port

#50443 fix when checking for service Label on macOS
  salt/utils/mac_utils.py
Labels: Bugfix - back-port

#50390 Fix integration.runners.test_nacl on Windows Py3
  salt/utils/nacl.py
  tests/integration/runners/test_nacl.py
Labels: Fluorine

#49651 [RFC] Add minion id to all fileserver events
  rfcs/0002-adding-minion-id-to-fileserver-calls.md
Labels: RFC

#50078 Job retry RFC
  rfcs/0003-job-retry.md
Labels: RFC

#50397 Add Win WUSA management, to install Windows Update files (.msu).
  salt/modules/win_wusa.py
  salt/states/win_wusa.py
Labels: Bugfix - back-port

#50549 Add security credits to release notes
  doc/topics/releases/2016.11.10.rst
  doc/topics/releases/2017.7.8.rst
  doc/topics/releases/2018.3.3.rst
Labels: Bugfix - back-port

#50487 [develop] minion handle_event cleanup
  salt/minion.py
Labels: Awesome

#50451 Introduce a new way of specifying uri + attempt to use oratab
  salt/modules/oracle.py
Labels: ZD
