Repository saltstack/salt, pull requests merged in 2019-01, with the labels that each got.

#50401 supportconfig: examine your infrastructure in just one go
  salt/cli/support/__init__.py
  salt/cli/support/collector.py
  salt/loader.py
  salt/modules/saltsupport.py
  salt/state.py
  salt/states/saltsupport.py
  salt/utils/args.py
  salt/utils/decorators/__init__.py
  tests/unit/modules/test_saltsupport.py
Labels: Awesome

#51084 [fluorine] Cleanup the singleton instances map.
  salt/transport/ipc.py
  salt/transport/tcp.py
  salt/transport/zeromq.py
Labels: Bugfix - back-port

#51100 Fix typo in method name (2019.2)
  salt/utils/cloud.py
Labels: 2019.2.0.rc1, Bugfix - back-port

#51154 Add support for Advanced Audit policies
  salt/modules/win_auditpol.py
  salt/modules/win_lgpo.py
  salt/utils/win_lgpo_auditpol.py
  salt/utils/win_lgpo_netsh.py
  tests/unit/utils/test_win_lgpo_auditpol.py
Labels: 2018.3.4, 2019.2, 2019.2.0.rc1

#51226 [2018.3] Handle spaces in fstab opts, similar fix to #39593
  salt/modules/mount.py
Labels: 2018.3.4, Bugfix - back-port

#50655 Fix race condition in Salt loader.
  salt/cloud/clouds/ec2.py
  salt/cloud/clouds/gce.py
  salt/engines/stalekey.py
  salt/loader.py
  salt/log/handlers/fluent_mod.py
  salt/modules/saltcheck.py
  salt/modules/state.py
  salt/modules/win_repo.py
  salt/payload.py
  salt/renderers/msgpack.py
  salt/returners/local_cache.py
  salt/runners/winrepo.py
  salt/sdb/sqlite3.py
  salt/serializers/msgpack.py
  salt/state.py
  salt/states/netsnmp.py
  salt/states/netusers.py
  salt/states/pkg.py
  salt/states/probes.py
  salt/states/zabbix_host.py
  salt/states/zabbix_user.py
  salt/transport/frame.py
  salt/transport/tcp.py
  salt/utils/cache.py
  salt/utils/cloud.py
  salt/utils/http.py
  salt/utils/json.py
  salt/utils/msgpack.py
  salt/utils/thread_local_proxy.py
  tests/integration/files/log_handlers/runtests_log_handler.py
  tests/packdump.py
  tests/unit/utils/test_thread_local_proxy.py
Labels: 2018.3.4, Bugfix - back-port

#51286 Skip test_get_file_templated_paths on Windows/Py3
  tests/integration/modules/test_cp.py
Labels: 2019.2.0.rc1

#51274 Fix minion start issue
  salt/utils/network.py
  tests/unit/utils/test_network.py
Labels: 2018.3.4, 2019.2.0.rc1, Bugfix - back-port

#51299 Add sleep before sending stop over UDP
  tests/unit/transport/test_zeromq.py
Labels: Bugfix - back-port

#51311 Fix failing test `unit.states.test_file.TestFileState.test_managed` on Windows
  tests/unit/states/test_file.py
Labels: 2018.3.4

#51290 [2018.3.4] Fix minion start
  salt/utils/network.py
  tests/unit/utils/test_network.py
Labels: 2018.3.4, Bugfix - back-port

#51376 Fix issue when directory doesn't exist in LGPO module
  salt/modules/win_lgpo.py
Labels: 2019.2.0.rc3

#51377 Fix issue when directory doesn't exist in LGPO module (2018.3.4)
  salt/modules/win_lgpo.py
Labels: 2018.3.4

#51390 Avoid tracebacks when GC has nuked all objects
  salt/transport/ipc.py
Labels: 2019.2.0

#51366 Cloud provider and profile configs are merged [2018.3]
  salt/cloud/__init__.py
  tests/support/case.py
  tests/unit/cloud/__init__.py
Labels: 2018.3.4, Bugfix - back-port
