Repository saltstack/salt, pull requests merged in 2019-03, with the labels that each got.

#51920 Add zabbix to the Windows builds
  pkg/windows/build_pkg.bat
Labels: 2018.3.5, 2019.2.1

#51966 Use winapi.com instead of coinitialize
  salt/modules/win_groupadd.py
  salt/modules/win_system.py
  salt/modules/win_task.py
  salt/modules/win_useradd.py
  salt/modules/win_wua.py
  salt/states/file.py
  salt/utils/win_update.py
  tests/unit/modules/test_win_system.py
Labels: 2018.3.5, 2019.2.1

#51895 Add __virtual__ to win_update
  salt/utils/win_update.py
Labels: 2017.7.9, 2018.3.5, 2019.2.1

#51806 Fix diskusage beacon on Windows
  salt/beacons/diskusage.py
  tests/unit/beacons/test_diskusage.py
Labels: 2018.3.5, 2019.2.1

#51967 Add unit tests for _compat.py
  tests/unit/test__compat.py
Labels: 2018.3.5, 2019.2.1

#52003 Check for path to be a symlink
  salt/modules/win_file.py
  tests/unit/modules/test_win_file.py
Labels: 2018.3.5, 2019.2.1

#52004 Fixed comparison of `None` with constants
  salt/cloud/clouds/gce.py
  salt/modules/github.py
Labels: 2018.3.5, Bugfix - back-port

#51988 Fix file comment
  salt/states/file.py
  tests/unit/states/test_file.py
Labels: 2018.3.5, 2019.2.1

#51918 Fix _compat for py3
  salt/_compat.py
  tests/unit/test__compat.py
Labels: 2018.3.5, 2019.2.1

#51896 Add all attached drives to the disks grain
  salt/grains/disks.py
  tests/unit/grains/test_disks.py
Labels: 2018.3.5, 2019.2.1

#52212 Fix 49329
  salt/states/file.py
Labels: Bugfix - back-port

#52290 Add missing master/minion docs for log_rotate*
  doc/ref/configuration/master.rst
  doc/ref/configuration/minion.rst
Labels: 2018.3.5, 2019.2.1

#52307 Fix x509 inconsistent file name in state example
  salt/states/x509.py
Labels: 2018.3, 2019.2

#52314 Add the ability to pass a timeout to beacons
  salt/modules/beacons.py
  salt/states/beacon.py
  tests/integration/modules/test_beacons.py
  tests/integration/states/test_beacon.py
Labels: 2019.2.1

#52306 Replaced `test.ping` with `test.version`
  doc/ref/cli/salt-unity.rst
  doc/ref/cli/salt.rst
  doc/ref/configuration/index.rst
  doc/ref/executors/index.rst
  doc/ref/peer.rst
  doc/ref/returners/index.rst
  doc/ref/runners/index.rst
  doc/topics/blackout/index.rst
  doc/topics/cloud/aws.rst
  doc/topics/cloud/azure.rst
  doc/topics/cloud/azurearm.rst
  doc/topics/cloud/deploy.rst
  doc/topics/cloud/gce.rst
  doc/topics/cloud/libvirt.rst
  doc/topics/cloud/linode.rst
  doc/topics/cloud/opennebula.rst
  doc/topics/cloud/parallels.rst
  doc/topics/cloud/proxmox.rst
  doc/topics/cloud/saltify.rst
  doc/topics/cloud/softlayer.rst
  doc/topics/cloud/vagrant.rst
  doc/topics/cloud/vexxhost.rst
  doc/topics/cloud/xen.rst
  doc/topics/development/architecture.rst
  doc/topics/development/hacking.rst
  doc/topics/eauth/access_control.rst
  doc/topics/eauth/index.rst
  doc/topics/event/master_events.rst
  doc/topics/installation/index.rst
  doc/topics/installation/windows.rst
  doc/topics/proxyminion/demo.rst
  doc/topics/ssh/index.rst
  doc/topics/targeting/batch.rst
  doc/topics/targeting/compound.rst
  doc/topics/targeting/globbing.rst
  doc/topics/targeting/grains.rst
  doc/topics/targeting/index.rst
  doc/topics/targeting/ipcidr.rst
  doc/topics/targeting/nodegroups.rst
  doc/topics/targeting/pillar.rst
  doc/topics/targeting/range.rst
  doc/topics/thorium/index.rst
  doc/topics/topology/syndic.rst
  doc/topics/tutorials/cloud_controller.rst
  doc/topics/tutorials/docker_sls.rst
  doc/topics/tutorials/esxi_proxy_minion.rst
  doc/topics/tutorials/firewall.rst
  doc/topics/tutorials/modules.rst
  doc/topics/tutorials/multimaster_pki.rst
  doc/topics/tutorials/walkthrough.rst
  doc/topics/tutorials/walkthrough_macosx.rst
Labels: Awesome, Documentation

#52283 Update to allow for malformed CPE_NAME from some OS's
  salt/grains/core.py
Labels: 2018.3, 2019.2, 2019.2.1, Bug, Confirmed, Grains, High Severity, P1, team-core
