Repository saltstack/salt, pull requests merged in 2019-07, with the labels that each got.

#52550 Add support for VMware Photon OS to pkgrepo
  doc/topics/releases/neon.rst
  salt/states/pkgrepo.py
Labels: Reviewers Assigned

#53562 Move create key call into try/except in Digital Ocean key test
  tests/integration/cloud/clouds/test_digitalocean.py
Labels: Reviewers Assigned

#53586 Forward port PR 53412 to Neon
  conf/master
  doc/topics/releases/2018.3.5.rst
  salt/config/__init__.py
  salt/utils/event.py
Labels: Reviewers Assigned

#53505 Change grains['manufacture'] to grains['manufacturer'] for Solaris
  salt/grains/core.py
Labels: Reviewers Assigned

#53624 Allow yaml list notation for nodegroup expansion
  salt/utils/minions.py
  tests/integration/files/conf/master
  tests/integration/shell/test_matcher.py
  tests/unit/utils/test_minions.py
Labels: Reviewers Assigned

#53614 Increase flaky attempts on mac tests using systemsetup
  tests/integration/modules/test_mac_power.py
  tests/integration/modules/test_mac_shadow.py
  tests/integration/modules/test_mac_system.py
Labels: Reviewers Assigned

#53662 Update win_lgpo
  salt/modules/win_lgpo.py
  tests/integration/modules/test_win_lgpo.py
Labels: 2019.2.1, Reviewers Assigned

#52600 Add missing files to release tarball
  MANIFEST.in
Labels: Documentation, Reviewers Assigned

#53220 Don't remove the pythonwin directory (2019.2.1)
  pkg/windows/build_env_2.ps1
  pkg/windows/build_env_3.ps1
Labels: 2019.2.1, Neon, Reviewers Assigned

#53678 Fix LGPO when string object is None
  salt/modules/win_lgpo.py
  tests/unit/modules/test_win_lgpo.py
Labels: 2019.2.1, Has Testcase, Reviewers Assigned

#53682 Fix compare issue in lgpo state module
  salt/states/win_lgpo.py
  tests/unit/states/test_win_lgpo.py
Labels: 2019.2.1, Has Testcase

#53626 Backport beacon test fix
  .ci/kitchen-amazon2-py2
  .ci/kitchen-amazon2-py3
  tests/integration/shell/test_minion.py
Labels: 2018.3, Reviewers Assigned

#52195 Use encoding when caching pillar data
  salt/minion.py
  tests/integration/minion/test_minion_cache.py
  tests/unit/test_module_names.py
Labels: 2019.2.1, Has Testcase, Reviewers Assigned

#53540 Don't double encode s3 paths
  salt/fileserver/s3fs.py
  tests/unit/fileserver/test_s3fs.py
Labels: Reviewers Assigned

#53690 Merge Forward #52065 (2019.2.1)
  salt/modules/win_dism.py
  tests/unit/modules/test_win_dism.py
Labels: 2019.2.1, Has Testcase

#53689 Merge Forward #52593 (2019.2.1)
  setup.py
  tests/integration/shell/test_proxy.py
  tests/integration/utils/testprogram.py
  tests/support/case.py
Labels: 2019.2.1, Has Testcase

#52470 Ignore vscode (and improve the vim swap line)
  .gitignore
Labels: Reviewers Assigned

#53418 [2019.2] More fixes to mysql module
  salt/modules/mysql.py
  salt/states/mysql_user.py
  tests/unit/modules/test_mysql.py
  tests/unit/states/test_mysql_user.py
Labels: Reviewers Assigned

#53653 [2019.2.1] Log which address failed to resolve
  salt/grains/core.py
Labels: 2019.2.1, Reviewers Assigned

#53557 Fix test_pydsl on Windows
  tests/integration/renderers/test_pydsl.py
Labels: 2019.2.1, Has Testcase, Neon, Reviewers Assigned

#53496 Add Pedro's suggested import method to network.py
  salt/utils/network.py
Labels: Reviewers Assigned

#53556 Fixes an issue with line endings in the jinja renderer
  salt/utils/templates.py
  tests/integration/minion/test_pillar.py
Labels: 2019.2.1, Has Testcase, Neon, Reviewers Assigned

#52065 Use the dism binary that matches system architecture
  salt/modules/win_dism.py
  tests/unit/modules/test_win_dism.py
Labels: 2018.3.5, Has Testcase, Reviewers Assigned

#53590 Fix `test status` on Windows
  tests/unit/beacons/test_status.py
Labels: Reviewers Assigned

#53585 Fix `test_winrepo` on Windows
  tests/unit/states/test_winrepo.py
Labels: Reviewers Assigned

#52401 Port Junos-related bug fixes from develop to 2019.2
  salt/modules/junos.py
  salt/proxy/junos.py
  salt/states/junos.py
  tests/unit/modules/test_junos.py
Labels: 2019.2.1, Has Testcase, Reviewers Assigned

#53688 Merge Forward #53662 (2019.2.1)
  salt/modules/win_lgpo.py
  tests/integration/modules/test_win_lgpo.py
Labels: 2019.2.1, Has Testcase

#53591 Fix whitelist errors in `test_boto_*` state tests on Windows
  tests/unit/states/test_boto_apigateway.py
  tests/unit/states/test_boto_cloudtrail.py
  tests/unit/states/test_boto_cognitoidentity.py
  tests/unit/states/test_boto_lambda.py
  tests/unit/states/test_boto_s3_bucket.py
  tests/unit/states/test_boto_vpc.py
Labels: Reviewers Assigned

#53732 Split exception assertion in pieces
  tests/unit/utils/test_schema.py
Labels: 2018.3

#53826 WAR ROOM test skip till rewritten to allow for dnf on RHEL 8 and F30
  tests/integration/modules/test_pkg.py
  tests/integration/states/test_pkg.py
Labels: 2019.2.1, Neon

#53894 [neon] Just skip overly mocked tests
  tests/integration/states/test_pkg.py
  tests/unit/utils/test_thin.py
Labels: WarRoom

#53542 Fix leak of SaltMessageClient instances when using tcp transport
  .ci/kitchen-centos7-py2-tcp
  .ci/kitchen-centos7-py3-tcp
  .ci/kitchen-ubuntu1604-py2-tcp
  .ci/kitchen-ubuntu1604-py3-tcp
  salt/transport/tcp.py
  tests/unit/transport/test_tcp.py
Labels: 2019.2.1, Reviewers Assigned

#53879 [neon] CI Pipelines; Remove old Jenkins cruft, Serial test runs.
  .ci/docs
  .ci/full-pipeline
  .ci/kitchen-centos6-py2
  .ci/kitchen-centos7-py2
  .ci/kitchen-centos7-py2-tcp
  .ci/kitchen-centos7-py3
  .ci/kitchen-centos7-py3-tcp
  .ci/kitchen-debian8-py2
  .ci/kitchen-debian8-py3
  .ci/kitchen-debian9-py2
  .ci/kitchen-debian9-py3
  .ci/kitchen-fedora29-py2
  .ci/kitchen-fedora29-py3
  .ci/kitchen-ubuntu1604-py2
  .ci/kitchen-ubuntu1604-py2-tcp
  .ci/kitchen-ubuntu1604-py3
  .ci/kitchen-ubuntu1604-py3-tcp
  .ci/kitchen-ubuntu1804-py2
  .ci/kitchen-ubuntu1804-py3
  .ci/kitchen-windows2016-py2
  .ci/kitchen-windows2016-py3
  .ci/lint
Labels: WarRoom

#53903 [neon] Replace `@pytest.mark.skip` with `@skipIf`
  tests/unit/utils/test_thin.py
Labels: WarRoom

#53923 [neon] Pass the correct path for the cloud tests
  noxfile.py
Labels: WarRoom

#53862 Cleanup vault test
  tests/integration/sdb/test_vault.py
Labels: Neon, WarRoom

#53381 systemd_service: add firstboot function
  salt/modules/systemd_service.py
  tests/unit/modules/test_systemd_service.py
Labels: Reviewers Assigned
