Repository saltstack/salt, pull requests merged in 2019-04, with the labels that each got.

#52381 Fix issue #51869 and add cert signing test
  salt/modules/x509.py
  tests/integration/files/conf/master.d/peers.conf
  tests/integration/files/file/base/test_cert.sls
  tests/integration/states/test_x509.py
Labels: 2019.2.1

#52413 [2019.2] Merge forward from 2018.3 to 2019.2
  salt/grains/core.py
  tests/unit/grains/test_core.py
  tests/unit/test_config.py
  tests/unit/utils/test_extend.py
Labels: 2019.2.1

#51913 [2019.2] Fixes to utils/nacl.py
  salt/utils/nacl.py
  tests/integration/runners/test_nacl.py
  tests/unit/modules/test_nacl.py
Labels: 2019.2.1

#51937 [2019.2] Fix to test state functions to allow arguments that mod_watch uses
  salt/states/test.py
Labels: 2019.2.1

#52008 Allow `/` in pillar includes
  salt/pillar/__init__.py
  tests/unit/test_pillar.py
Labels: 2019.2.1

#52160 Virt whitespace fix
  salt/modules/virt.py
  tests/unit/modules/test_virt.py
Labels: 2019.2.1

#52234 [2019.2] Fixes to matchers when used in pillar
  salt/matchers/compound_match.py
  salt/matchers/glob_match.py
  salt/pillar/__init__.py
Labels: 2019.2.1

#52427 [2019.2] Support for old yaml render
  doc/topics/releases/2019.2.1.rst
  salt/renderers/yaml.py
  salt/utils/yamlloader_old.py
  tests/unit/renderers/test_yaml.py
Labels: 2019.2.1

#52473 Backport #49437 into 2018.3
  salt/modules/opkg.py
Labels: 2019.2.1

#52341 virt.pool_running: fix pool start
  salt/states/virt.py
  tests/unit/states/test_virt.py
Labels: 2019.2.1

#52146 Add missing symlink test
  tests/unit/modules/test_win_file.py
Labels: 2019.2.1

#52043 fix missing client_args in influxdb module
  salt/states/influxdb_retention_policy.py
Labels: 2019.2.1

#52334 51879 fix binary pillar return error
  .gitignore
  doc/topics/pillar/index.rst
  salt/renderers/gpg.py
  salt/states/file.py
  tests/unit/renderers/test_gpg.py
  tests/unit/states/test_file.py
Labels: 2019.2.1

#52396 Altered code to support salt-ssh on AIX
  salt/client/ssh/ssh_py_shim.py
  salt/utils/rsax931.py
Labels: 2018.3.5, 2019.2.1

#52046 Use registry to get timezone
  salt/modules/win_timezone.py
  tests/unit/modules/test_win_timezone.py
Labels: 2018.3.5, 2019.2.1

#52171 use proxyfile based on salt.syspaths.CONFIG_DIR
  salt/modules/salt_proxy.py
Labels: 2019.2.1

#52415 Backport #49832 into 2018.3
  doc/ref/states/writing.rst
  salt/modules/win_file.py
  salt/states/archive.py
  salt/states/boto_cloudfront.py
  salt/states/boto_s3.py
  salt/states/boto_sqs.py
  salt/states/chocolatey.py
  salt/states/dvs.py
  salt/states/esxdatacenter.py
  salt/states/esxi.py
  salt/states/file.py
  salt/states/glance_image.py
  salt/states/kernelpkg.py
  salt/states/keystone_domain.py
  salt/states/keystone_endpoint.py
  salt/states/keystone_group.py
  salt/states/keystone_project.py
  salt/states/keystone_role.py
  salt/states/keystone_service.py
  salt/states/keystone_user.py
  salt/states/linux_acl.py
  salt/states/net_napalm_yang.py
  salt/states/neutron_network.py
  salt/states/neutron_secgroup.py
  salt/states/neutron_secgroup_rule.py
  salt/states/neutron_subnet.py
  salt/states/pbm.py
  salt/states/saltmod.py
  salt/states/snapper.py
  salt/states/solrcloud.py
  salt/states/test.py
  salt/utils/napalm.py
  salt/utils/state.py
  tests/integration/files/file/base/onchanges_prereq.sls
  tests/integration/files/file/base/orch/req_test.sls
  tests/integration/modules/test_state.py
  tests/integration/runners/test_state.py
  tests/integration/states/test_file.py
  tests/support/helpers.py
  tests/support/unit.py
  tests/unit/states/test_boto_cloudfront.py
  tests/unit/states/test_boto_sqs.py
  tests/unit/states/test_esxdatacenter.py
  tests/unit/states/test_file.py
  tests/unit/states/test_kernelpkg.py
  tests/unit/states/test_linux_acl.py
  tests/unit/states/test_net_napalm_yang.py
  tests/unit/states/test_saltmod.py
  tests/unit/utils/test_state.py
Labels: 2019.2.1

#52552 Bring 52170 into 2019.2
  salt/modules/win_task.py
Labels: 2019.2.1

#52490 Fix pillar include regression
  salt/pillar/__init__.py
  tests/filename_map.yml
  tests/integration/files/pillar/base/glob_include.sls
  tests/integration/files/pillar/base/glob_include_a.sls
  tests/integration/files/pillar/base/glob_include_b.sls
  tests/integration/files/pillar/base/include-a.sls
  tests/integration/files/pillar/base/include-b.sls
  tests/integration/files/pillar/base/include.sls
  tests/integration/files/pillar/base/top.sls
  tests/integration/pillar/test_pillar_include.py
  tests/unit/test_module_names.py
Labels: 2019.2.1

#51661 git_pillar: Fix all_saltenvs on base env
  salt/utils/gitfs.py
  tests/integration/pillar/test_git_pillar.py
Labels: 2019.2.1, Bugfix - back-port

#52610 Add win function tests
  salt/utils/win_functions.py
  tests/unit/utils/test_win_functions.py
Labels: 2018.3.5

#52259 Fix win_proc threads leaked on linux
  salt/minion.py
Labels: 2018.3.5, 2019.2.1

#52608 Remove outdated thorium warning: Solves #52557
  doc/topics/thorium/index.rst
Labels: 2018.3, 2019.2, develop

#52684 Fix issue with compare_lists
  doc/topics/jinja/index.rst
  salt/utils/data.py
  tests/unit/states/test_win_dism.py
  tests/unit/utils/test_data.py
Labels: 2018.3, 2018.3.4, 2019.2.2

#52385 Refactor test_cron test
  tests/integration/states/test_cron.py
Labels: 2019.2.1
