Repository saltstack/salt, pull requests merged in 2019-12, with the labels that each got.

#55485 Doc fix in pkgrepo state
  salt/states/pkgrepo.py
Labels: Documentation, master-port

#55356 doc: escape special characters on linux for cmd.run
  salt/modules/cmdmod.py
Labels: Documentation

#54991 master-port #52126
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.keystore.rst
  doc/ref/states/all/index.rst
  doc/ref/states/all/salt.states.keystore.rst
  doc/topics/releases/neon.rst
  salt/modules/keystore.py
  salt/modules/saltcheck.py
  salt/states/keystore.py
  tests/unit/states/test_keystore.py
Labels: master-port

#55388 Update win_path.py
  salt/states/win_path.py
Labels: master-port

#55258 Make aptpkg.info return only installed packages
  salt/modules/aptpkg.py
  tests/unit/modules/test_aptpkg.py
Labels: master-port

#55400 Port 51758
  salt/grains/core.py
  tests/unit/grains/test_core.py
Labels: master-port

#55345 chroot: add apply_, sls and highstate for state execution
  salt/modules/chroot.py
  tests/unit/modules/test_chroot.py
Labels: Feature

#55404 Porting 54543
  salt/modules/cmdmod.py
  tests/unit/modules/test_cmdmod.py
Labels: master-port

#55195 [master] Port #49891 (salt_version module)
  doc/topics/releases/version_numbers.rst
  salt/modules/salt_version.py
  tests/unit/modules/test_salt_version.py
Labels: master-port

#55498 change disabled doc to true logic
  salt/modules/debian_service.py
Labels: Documentation

#46713 Don't refresh modules twice per sync or refresh ops
  salt/minion.py
  salt/modules/saltutil.py
  tests/integration/modules/test_grains.py
  tests/integration/modules/test_saltutil.py
Labels: Pending Changes, Reviewers Assigned

#55151 [master] Preserve already defined DESTRUCTIVE_TESTS and EXPENSIVE_TESTS env variables
  tests/support/parser/__init__.py
Labels: master-port

#54670 [master] Porting #49151 to master
  salt/states/cmd.py
Labels: Documentation, master-port

#54661 [master] Porting #51057 to master
  salt/executors/splay.py
Labels: Documentation, master-port

#54681 [master] Porting #52020 to master
  doc/ref/states/requisites.rst
Labels: Documentation, master-port

#55429 Add use_yamlloader_old to minion and master config docs
  doc/ref/configuration/master.rst
  doc/ref/configuration/minion.rst
  doc/topics/releases/2019.2.1.rst
  doc/topics/releases/2019.2.2.rst
Labels: Documentation

#55005 (Backport 52712) mount: fix remount when fstype is not set
  salt/modules/mount.py
  tests/unit/modules/test_mount.py
Labels: master-port

#54997 (Backport 51929, 51954) lvm: be quiet when a pv, lv or vg is not expected
  salt/modules/linux_lvm.py
  salt/states/lvm.py
  tests/unit/modules/test_linux_lvm.py
Labels: master-port

#54996 (Backport 51871) cmdmod: add 'binds' parameter in run_chroot
  salt/modules/cmdmod.py
  tests/unit/modules/test_cmdmod.py
Labels: master-port

#54955 (Backport 50175) Add root parameter to useradd, shadow and groupadd
  salt/modules/groupadd.py
  salt/modules/shadow.py
  salt/modules/useradd.py
  tests/unit/modules/test_groupadd.py
  tests/unit/modules/test_useradd.py
Labels: master-port

#54572 [master] Porting #52670 to master
  salt/modules/debian_ip.py
Labels: master-port

#55492 Allow arbitrary arguments to be bassed through the pip module
  salt/modules/pip.py
  salt/states/pip_state.py
  tests/unit/modules/test_pip.py
Labels: master-port

#54965 (Backport 50725) mount: add fstab_{present,absent} states
  salt/states/mount.py
  tests/unit/states/test_mount.py
Labels: master-port

#55398 Port #51499 to master
  tests/integration/files/file/base/issue-51499.sls
  tests/integration/modules/test_state.py
Labels: master-port

#55006 (Backport 49037) Fix case where args or kwargs are not specified in loop state
  salt/states/loop.py
Labels: master-port

#54676 [master] Porting #51726 to master
  salt/states/archive.py
Labels: master-port

#54658 [master] Porting #53298 to master
  salt/states/host.py
Labels: Documentation, master-port

#54622 [master] Porting #49378 to master
  doc/ref/configuration/minion.rst
  salt/config/__init__.py
  tests/unit/test_config.py
Labels: master-port

#55557 Use utc times for jids
  salt/utils/jid.py
  tests/unit/utils/test_jid.py
Labels: master-port

#55424 adding DNS exec and state modules to master
  salt/modules/azurearm_dns.py
  salt/states/azurearm_dns.py
  salt/utils/azurearm.py
  tests/unit/modules/test_azurearm_dns.py
Labels: Needs Testcase, master-port

#54957 Copy-paste error
  doc/ref/states/requisites.rst
Labels: Documentation

#51706 grains/core: ignore HOST_NOT_FOUND errno in fqdns()
  salt/grains/core.py
  tests/unit/grains/test_core.py
Labels: Reviewers Assigned

#51790 Doc fix
  doc/ref/renderers/all/salt.renderers.yaml.rst
  doc/topics/states/index.rst
Labels: Documentation, Reviewers Assigned

#55566 Clarify the outputter docs with CLI examples
  salt/output/json_out.py
  salt/output/newline_values_only.py
  salt/output/no_out_quiet.py
  salt/output/pony.py
  salt/output/pprint_out.py
  salt/output/profile.py
  salt/output/raw.py
  salt/output/table_out.py
  salt/output/txt.py
  salt/output/yaml_out.py
Labels: Documentation

#55403 Port 54653 to master and add a test
  salt/client/ssh/wrapper/state.py
  tests/unit/client/ssh/__init__.py
  tests/unit/client/ssh/wrapper/__init__.py
  tests/unit/client/ssh/wrapper/test_state.py
Labels: master-port

#54981 master-port 50141
  doc/topics/releases/neon.rst
  salt/states/ssh_auth.py
  tests/unit/states/test_ssh_auth.py
Labels: master-port

#54958 (Backport 50380) systemd: add optional root parameter
  salt/modules/systemd_service.py
  tests/unit/modules/test_systemd_service.py
Labels: master-port

#54956 (Backport 50302) cmd: Add root parameter for wait and run states
  salt/states/cmd.py
  tests/unit/states/test_cmd.py
Labels: master-port

#54634 [master] Porting #53425 to master
  salt/states/pkg.py
Labels: Documentation, master-port

#54011 Correct status code - should be a number
  doc/topics/tutorials/http.rst
Labels: Documentation

#55506 Add hmac_compute (Repost of #54164)
  salt/modules/hashutil.py
  salt/utils/hashutils.py
  tests/unit/modules/test_hashutil.py
  tests/unit/utils/test_hashutils.py
Labels: master-port

#54685 [master] Porting #51915 to master
  salt/states/zabbix_host.py
Labels: master-port

#53712 Update dunder docs (Neon)
  doc/topics/development/modules/developing.rst
Labels: master-port

#55650 Fix simple typo: virutal -> virtual
  salt/modules/vsphere.py
Labels: Documentation

#55637 Backport #51677 to master
  salt/config/__init__.py
  salt/modules/config.py
  salt/modules/dockermod.py
  salt/states/docker_container.py
  tests/integration/states/test_docker_container.py
  tests/unit/modules/test_config.py
  tests/unit/modules/test_dockermod.py
Labels: master-port

#54608 [master] Porting #52304 to master
  salt/utils/path.py
Labels: master-port

#54638 [master] Porting #50757 to master
  salt/modules/restartcheck.py
Labels: master-port

#54198 Remove incorrect information from docker_container.running docs
  salt/states/docker_container.py
Labels: Documentation

#54597 [master] Porting #51322 to master
  salt/payload.py
  tests/unit/test_payload.py
Labels: master-port

#55661 Proxy doc improvement - list current proxy support
  doc/topics/proxyminion/index.rst
Labels: Documentation

#55205 openSUSE ships with Salt
  doc/topics/installation/suse.rst
Labels: Documentation

#54663 [master] Porting #51141 to master
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.lxd.rst
  salt/modules/lxd.py
Labels: master-port

#55197 Update index.rst
  doc/topics/index.rst
Labels: Documentation

#55605 [master] Port #51907 (module docs fixes)
  doc/topics/development/modules/index.rst
  doc/topics/tutorials/jinja_to_execution_module.rst
Labels: Documentation, master-port

#55589 Acme state fixup master
  doc/topics/jinja/index.rst
  salt/modules/acme.py
  salt/states/acme.py
  salt/utils/dictupdate.py
  tests/unit/modules/test_acme.py
  tests/unit/states/test_acme.py
  tests/unit/utils/test_dictupdate.py
  tests/unit/utils/test_jinja.py
Labels: master-port

#54624 [master] Porting #50904 to master
  doc/topics/proxyminion/beacon.rst
  doc/topics/proxyminion/demo.rst
  doc/topics/proxyminion/ssh.rst
  doc/topics/proxyminion/state.rst
Labels: Documentation, master-port

#54607 [master] Porting #52182 to master
  salt/modules/mdadm_raid.py
Labels: master-port

#54566 [master] Porting #53080 to master
  salt/modules/win_pkg.py
Labels: master-port

#55354 Use packaged msgpack
  salt/cloud/clouds/ec2.py
  salt/cloud/clouds/gce.py
  salt/engines/stalekey.py
  salt/log/handlers/fluent_mod.py
  salt/modules/state.py
  salt/modules/winrepo.py
  salt/payload.py
  salt/renderers/msgpack.py
  salt/returners/local_cache.py
  salt/runners/winrepo.py
  salt/sdb/sqlite3.py
  salt/serializers/msgpack.py
  salt/state.py
  salt/states/pkg.py
  salt/transport/frame.py
  salt/transport/ipc.py
  salt/transport/tcp.py
  salt/utils/cache.py
  salt/utils/cloud.py
  salt/utils/http.py
  salt/utils/msgpack.py
  tests/integration/__init__.py
  tests/integration/files/log_handlers/runtests_log_handler.py
  tests/packdump.py
  tests/unit/utils/test_msgpack.py
Labels: Core

#51718 Fix the Cheetah template renderer in salt.utils.templates, and unit-tests for Jinja, Cheetah, Mako, Genshi, wempy templates,
  requirements/static/darwin.in
  requirements/static/linux.in
  requirements/static/py2.7/darwin.txt
  requirements/static/py3.4/linux.txt
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.5/linux.txt
  requirements/static/py3.5/windows.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.6/linux.txt
  requirements/static/py3.6/windows.txt
  requirements/static/py3.7/darwin.txt
  requirements/static/py3.7/linux.txt
  requirements/static/windows.in
  salt/utils/templates.py
  tests/unit/utils/test_templates.py
Labels: Reviewers Assigned

#55660 Use packaged json module for ThreadsafeProxy
  salt/modules/azurearm_resource.py
  salt/modules/mssql.py
  salt/modules/saltcheck.py
  salt/netapi/rest_tornado/saltnado.py
  salt/states/netsnmp.py
  salt/states/netusers.py
  salt/states/probes.py
  salt/states/zabbix_host.py
  salt/states/zabbix_user.py
  salt/utils/json.py
  tests/unit/utils/test_thin.py
Labels: Core

#55253 [master] Port #51047 (Jinja map troubleshooting)
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.jinja.rst
  doc/topics/releases/neon.rst
  salt/modules/jinja.py
  tests/integration/files/file/base/modules/jinja/defaults.yaml
  tests/integration/files/file/base/modules/jinja/map.jinja
  tests/integration/files/file/base/modules/jinja/osarchmap.json
  tests/integration/files/file/base/modules/jinja/osfamilymap.yaml
  tests/integration/files/file/base/modules/jinja/osfingermap.yaml
  tests/integration/files/file/base/modules/jinja/osmap.yaml
  tests/integration/modules/test_jinja.py
Labels: Needs Testcase, master-port

#54647 [master] Porting #51813 to master
  salt/modules/npm.py
Labels: master-port

#55659 Cherry pick non-proxy related changes from #54878
  salt/cloud/clouds/ec2.py
  tests/unit/cloud/clouds/test_ec2.py
Labels: Core

#54628 [master] Porting #51327 to master
  doc/topics/installation/freebsd.rst
Labels: Documentation, master-port

#54625 [master] Porting #49903 to master
  salt/pillar/consul_pillar.py
  tests/unit/pillar/test_consul_pillar.py
Labels: master-port

#55636 Backport #49338 to master
  salt/output/dson.py
  salt/renderers/dson.py
Labels: master-port

#55680 Master Port #49779
  doc/topics/releases/neon.rst
  salt/modules/dockermod.py
Labels: Neon, master-port

#54673 [master] Porting #50511 to master
  salt/modules/virt.py
Labels: Documentation, master-port

#54667 [master] Porting #52210 to master
  salt/states/file.py
Labels: Documentation, master-port

#54645 [master] Porting #51785 to master
  salt/utils/path.py
  tests/unit/utils/test_path.py
Labels: master-port

#55666 Add the `internal` flag to openvswitch
  salt/modules/openvswitch.py
  salt/states/openvswitch_port.py
  tests/unit/states/test_openvswitch_port.py
Labels: Core

#54623 [master] Porting #52458 to master
  doc/topics/jinja/index.rst
  salt/modules/testinframod.py
  salt/states/testinframod.py
  salt/utils/stringutils.py
  tests/unit/utils/test_jinja.py
Labels: master-port

#54680 [master] Porting #53198 to master
  salt/queues/pgjsonb_queue.py
Labels: master-port

#55328 How to create profiling graphs on Windows (merge against master)
  doc/topics/troubleshooting/master.rst
Labels: Documentation

#55537 Do not deprecate expr_form in mine_get
  salt/daemons/masterapi.py
Labels: Neon

#55713 Cumulative port 50049 & 50072
  salt/states/module.py
  tests/unit/states/test_module.py
Labels: master-port

#55622 Updating download link for openSUSE
  doc/topics/tutorials/cloud_controller.rst
Labels: Documentation

#55256 Let dpkg.info expose package status
  salt/modules/dpkg_lowpkg.py
  tests/integration/modules/test_pkg.py
  tests/unit/modules/test_dpkg_lowpkg.py
Labels: master-port

#55002 (Backport 52182) mdadm_raid: convert metadata to text
  tests/unit/modules/test_mdadm_raid.py
Labels: master-port

#54616 [master] Porting #50374 to master
  salt/returners/local_cache.py
Labels: master-port

#54668 [master] Porting #49223 to master
  salt/utils/parsers.py
  tests/unit/utils/test_parsers.py
Labels: master-port

#54992 master-port 51846 and 52969
  doc/ref/states/requisites.rst
  doc/topics/releases/neon.rst
  salt/state.py
  tests/integration/modules/test_state.py
  tests/unit/test_state.py
Labels: master-port

#55684 Master Port #50344
  salt/modules/test.py
Labels: Neon, master-port

#55643 Ensure refresh and refresh_db both work in aptpkg
  salt/modules/aptpkg.py
  salt/states/pkgrepo.py
Labels: Neon

#55614 Deprecate jinja filters for neon
  doc/topics/jinja/index.rst
  salt/utils/data.py
  salt/utils/hashutils.py
  salt/utils/jinja.py
  salt/utils/stringutils.py
Labels: Neon

#55679 document retry_on_errors and error_retries boto opts and remove deprecation
  salt/modules/boto_route53.py
  salt/modules/boto_vpc.py
Labels: Neon

#55683 Master Port #50343
  salt/modules/firewalld.py
  salt/states/firewalld.py
Labels: Neon, master-port

#55685 Master Port #49826
  salt/states/win_servermanager.py
Labels: Neon, master-port

#55682 Master Port #49796
  salt/modules/ssh.py
Labels: Neon, master-port

#55641 Deprecate enviroment for environment in heat modules
  salt/modules/heat.py
  salt/states/heat.py
  tests/integration/files/file/base/templates/heat-env.yml
  tests/integration/files/file/base/templates/heat-template.yml
  tests/unit/modules/test_heat.py
  tests/unit/states/test_heat.py
Labels: Neon

#55569 Deprecate nova cloud driver
  doc/ref/clouds/all/index.rst
  doc/ref/clouds/all/salt.cloud.clouds.nova.rst
  salt/cloud/clouds/nova.py
  tests/unit/cloud/clouds/test_nova.py
Labels: Neon

#55573 Deprecate quiet kwarg in cmd.run state module
  doc/topics/tutorials/writing_tests.rst
  salt/states/cmd.py
  tests/integration/states/test_cmd.py
  tests/unit/modules/test_cmdmod.py
Labels: Neon

#55568 Document use of ? to split path/key in vault sdb is deprecated
  doc/topics/sdb/index.rst
  salt/sdb/vault.py
  tests/unit/sdb/test_vault.py
Labels: Neon

#55217 Note known pip version incompatibility
  salt/modules/pip.py
Labels: Documentation

#55706 Update zabbix module to avoid exception
  salt/modules/zabbix.py
Labels: master-port

#55715 Add deprecations to changelog and neon release notes
  CHANGELOG.md
  doc/topics/releases/neon.rst
Labels: Neon

#54686 [master] Porting #51098 to master
  salt/sdb/memcached.py
Labels: Documentation, master-port

#54650 [master] Porting #51538 to master
  salt/utils/etcd_util.py
  tests/unit/utils/test_etcd_util.py
Labels: master-port

#53621 Git pillar update interval
  doc/ref/configuration/master.rst
  salt/config/__init__.py
  salt/master.py
  salt/pillar/git_pillar.py
Labels: Reviewers Assigned

#54675 [master] Porting #49076 to master
  salt/modules/file.py
Labels: master-port

#54678 [master] Porting #52747 to master
  tests/unit/pillar/test_csvpillar.py
Labels: master-port

#54960 (Backport 50452, 54022) Add new module freezer
  salt/modules/freezer.py
  tests/unit/modules/test_freezer.py
Labels: master-port

#54961 (Backport 50541) btrfs: add all subvolume commands
  salt/modules/btrfs.py
  tests/unit/modules/test_btrfs.py
Labels: master-port

#55722 Deprecate salt/utils/__init__.py functions
  doc/topics/proxyminion/index.rst
  salt/cloud/clouds/vagrant.py
  salt/grains/mdata.py
  salt/grains/smartos.py
  salt/grains/zfs.py
  salt/states/file.py
  salt/states/gem.py
  salt/utils/__init__.py
  salt/utils/dicttrim.py
  tests/integration/__init__.py
  tests/integration/files/file/base/_modules/runtests_helpers.py
  tests/integration/modules/test_pip.py
  tests/integration/modules/test_pkg.py
  tests/multimaster/__init__.py
  tests/unit/grains/test_core.py
Labels: Neon

#55730 Master Port #50089
  salt/transport/tcp.py
  salt/transport/zeromq.py
  tests/integration/__init__.py
  tests/unit/transport/test_tcp.py
  tests/unit/transport/test_zeromq.py
Labels: Neon, master-port

#55725 Deprecate gitfs_env_whitelist and gitfs_env_blacklist
  doc/ref/states/top.rst
  salt/config/__init__.py
  salt/fileserver/gitfs.py
  salt/utils/gitfs.py
  tests/unit/fileserver/test_gitfs.py
Labels: Neon

#55664 Bump deprecation warning to Aluminium for neutron module
  salt/utils/openstack/neutron.py
Labels: Neon

#55218 update openstack.py for more verbose auth example
  salt/cloud/clouds/openstack.py
Labels: Documentation

#55155 Fix the documentation rendering for the S3 execution module
  salt/modules/s3.py
Labels: Documentation

#54660 [master] Porting #52244 to master
  salt/states/icinga2.py
Labels: Documentation, master-port

#54657 [master] Porting #49250 to master
  salt/states/jboss7.py
  tests/unit/states/test_jboss7.py
Labels: master-port

#54982 master-port 50215 and 51943
  doc/topics/releases/neon.rst
  salt/engines/logentries.py
  salt/engines/logstash_engine.py
  salt/modules/boto_ssm.py
Labels: master-port

#54662 [master] Porting #50399 to master
  salt/runners/saltutil.py
Labels: Documentation, master-port

#54641 [master] Porting #50485 to master
  doc/topics/cloud/saltify.rst
Labels: Documentation, master-port

#55346 Add virt.pool_capabilities function
  salt/modules/virt.py
  tests/unit/modules/test_virt.py
Labels: Feature

#54600 [master] Porting #51168 to master
  salt/states/debconfmod.py
Labels: Documentation, master-port

#53307 Fix slot parsing in unless/onlyif function arguments
  doc/topics/releases/neon.rst
  salt/state.py
  tests/unit/test_state.py
Labels: Neon, Reviewers Assigned

#53462 Supports all valid protos for remote sources
  salt/modules/config.py
  salt/modules/cp.py
  salt/modules/win_pkg.py
  tests/integration/modules/test_config.py
  tests/unit/modules/test_win_pkg.py
Labels: Reviewers Assigned

#55743 Bloomberg tornado set cookie
  CHANGELOG.md
  salt/netapi/rest_tornado/saltnado.py
  tests/unit/netapi/test_rest_tornado.py
Labels: master-port

#54411 Manage wusa 3010 return code
  salt/modules/win_wusa.py
  salt/states/win_wusa.py
  tests/unit/modules/test_win_wusa.py
  tests/unit/states/test_win_wusa.py
Labels: Neon

#55165 Master -- pr52033 -- Volume infos fix
  salt/modules/virt.py
  tests/unit/modules/test_virt.py
Labels: master-port

#54642 [master] Porting #50938 to master
  salt/modules/opkg.py
  tests/unit/modules/test_opkg.py
Labels: master-port

#54580 [master] Porting #50842 to master
  salt/utils/schedule.py
  tests/integration/scheduler/test_error.py
Labels: master-port

#54569 [master] Porting #52365 to master
  pkg/windows/modules/start-process-and-test-exitcode.psm1
Labels: master-port

#55749 [master] Port json_query Jinja filter from Ansible
  doc/topics/jinja/index.rst
  doc/topics/releases/neon.rst
  requirements/static/darwin.in
  requirements/static/linux.in
  requirements/static/windows.in
  salt/utils/data.py
  tests/unit/utils/test_data.py
  tests/unit/utils/test_jinja.py
Labels: master-port

#54630 [master] Porting #50117 to master
  salt/transport/tcp.py
Labels: master-port
