Repository saltstack/salt, pull requests merged in 2019-05, with the labels that each got.

#52786 Fix user.present for Windows
  salt/states/user.py
  tests/integration/states/test_user.py
Labels: 2018.3.4, 2019.2.2

#52767 [2019.2.1] Add tests to PR #51983
  salt/transport/zeromq.py
  tests/unit/transport/test_zeromq.py
Labels: 2019.2.1

#52211 Normalize file mode for Python 3 compatibility
  salt/modules/file.py
  salt/modules/win_file.py
  tests/unit/modules/test_file.py
  tests/unit/modules/test_win_file.py
Labels: 2019.2.1

#52170 Fix issue when task doesn't have delay_random defined
  salt/modules/win_task.py
Labels: 2017.7.9, 2018.3.5, 2019.2.1

#52973 Fix `integration.states.test_pip_state.PipStateTest.test_issue_2028_pip_installed_state` on Windows
  tests/integration/files/file/base/_modules/runtests_helpers.py
Labels: 2019.2.1, Neon

#52992 Fix `unit.modules.test_win_system` tests
  tests/unit/modules/test_win_system.py
Labels: Neon

#52998 Fix `test.modules.test_win_file` tests on Windows
  tests/unit/modules/test_win_file.py
Labels: Neon

#52124 Optimize __context__ in LGPO module
  salt/modules/win_lgpo.py
Labels: 2019.2.1

#52191 Fix issue where version doesn't detect when check_remote=True
  salt/modules/chocolatey.py
Labels: 2017.7.9, 2018.3.5, 2019.2.1

#53031 Add tests for changes to chocolatey module
  salt/modules/chocolatey.py
  tests/unit/modules/test_chocolatey.py
Labels: 2019.2.1

#53141 Check for all non-word characters when calling secure_password
  salt/utils/pycrypto.py
  tests/unit/utils/test_pycrypto.py
Labels: Bugfix - back-port

#53157 Fix `unit.modules.test_win_file.WinFileTestCase.test_issue_52002_check_file_remove_symlink`
  salt/modules/win_file.py
  salt/platform/win.py
Labels: 2019.2.1

#52787 [2018.3] Fixes to test_pip state sls files
  salt/states/pip_state.py
  tests/integration/files/file/base/issue-2028-pip-installed.sls
  tests/integration/files/file/base/issue-46127-pip-env-vars.sls
  tests/integration/modules/test_state.py
  tests/integration/shell/test_minion.py
  tests/unit/states/test_pip_state.py
Labels: 2019.2.1, Neon

#52934 Update msgpack calls for newer msgpack
  salt/transport/ipc.py
Labels: 2019.2.1

#51840 Roster sshknownhosts
  doc/ref/roster/all/index.rst
  doc/ref/roster/all/salt.roster.sshknownhosts.rst
  salt/roster/sshknownhosts.py
  tests/unit/files/rosters/sshknownhosts/known_hosts
  tests/unit/roster/test_sshknownhosts.py
Labels: Feature, Pending Discussion, Salt-SSH

#53298 corrected html doc for host state argument clean
  salt/states/host.py
Labels: Bugfix - back-port
