Repository saltstack/salt, pull requests merged in 2019-06, with the labels that each got.

#51372 Use .NET to gather NIC information on newer systems
  salt/utils/network.py
  salt/utils/win_network.py
  tests/unit/utils/test_win_network.py
Labels: Neon

#53323 Fix for issue #53274, test on Amazon Linux 1
  tests/integration/states/test_pkg.py
Labels: 2019.2.1, Bugfix - back-port, Fixed Pending Verification

#53287 Fix win system
  salt/modules/win_system.py
Labels: 2019.2.1, Critical, Neon

#53145 zpool.present: Fix wrong output in test=true run
  salt/states/zpool.py
  tests/unit/states/test_zpool.py
Labels: Neon

#53437 Fix failing symlink test
  salt/modules/win_file.py
  tests/unit/modules/test_win_file.py
Labels: 2019.2.1

#53399 Fix test suite on develop
  salt/utils/network.py
  salt/utils/win_network.py
Labels: Bugfix - back-port, Neon

#53311 Add fully qualified cmd call
  salt/modules/win_service.py
Labels: 2019.2, Neon

#52856 Add note about new flatpak module
  doc/topics/releases/neon.rst
Labels: Neon

#53514 Revert logging changes from #53492
  tests/integration/files/log_handlers/runtests_log_handler.py
Labels: Reviewers Assigned

#53498 Fix broken documentation links
  doc/ref/modules/all/salt.modules.pkg.rst
  doc/ref/modules/all/salt.modules.service.rst
Labels: Reviewers Assigned

#53434 Update documentation for newer mac_service module.
  doc/ref/modules/all/salt.modules.service.rst
Labels: Reviewers Assigned

#53507 [neon] Run full test suite on PRs
  .ci/kitchen-centos6-py2
  .ci/kitchen-centos7-py2
  .ci/kitchen-centos7-py3
  .ci/kitchen-debian8-py2
  .ci/kitchen-debian8-py3
  .ci/kitchen-debian9-py2
  .ci/kitchen-debian9-py3
  .ci/kitchen-fedora29-py2
  .ci/kitchen-fedora29-py3
  .ci/kitchen-ubuntu1604-py2
  .ci/kitchen-ubuntu1604-py3
  .ci/kitchen-ubuntu1804-py2
  .ci/kitchen-ubuntu1804-py3
  .ci/kitchen-windows2016-py2
  .ci/kitchen-windows2016-py3
Labels: Reviewers Assigned

#53494 Always delete digital ocean key for test_key_management test
  tests/integration/cloud/clouds/test_digitalocean.py
Labels: Reviewers Assigned

#53491 Update test_gen_hash for macosx
  tests/unit/utils/test_pycrypto.py
Labels: Reviewers Assigned

#53467 Check valid username first (fixes failing symlink test)
  salt/log/setup.py
  salt/modules/file.py
  salt/modules/win_file.py
  salt/platform/win.py
  salt/states/file.py
  salt/states/zfs.py
  salt/states/zpool.py
  salt/utils/win_runas.py
  tests/integration/states/test_file.py
  tests/unit/modules/test_file.py
Labels: 2019.2.1, Neon, Reviewers Assigned

#53515 Support Heimdal Kerberos
  salt/modules/kerberos.py
Labels: Reviewers Assigned

#51677 2 enhancements to config.option
  doc/topics/releases/neon.rst
  salt/config/__init__.py
  salt/modules/config.py
  salt/modules/dockermod.py
  salt/states/docker_container.py
  tests/integration/states/test_docker_container.py
  tests/unit/modules/test_config.py
  tests/unit/modules/test_dockermod.py
Labels: Reviewers Assigned

#53524 [2017.7] Update pipelines to work on old and new jenkins
  .ci/docs
  .ci/kitchen-centos7-py2
  .ci/kitchen-centos7-py3
  .ci/kitchen-ubuntu1604-py2
  .ci/kitchen-ubuntu1604-py3
  .ci/kitchen-windows2016-py2
  .ci/kitchen-windows2016-py3
  .ci/lint
Labels: Reviewers Assigned

#53432 [2019.2.1] Various fixes for 2019.2.1 to ensure tests pass on Mac OS X
  salt/beacons/__init__.py
  salt/fileserver/roots.py
  salt/loader.py
  salt/modules/beacons.py
  salt/modules/mac_assistive.py
  salt/utils/decorators/__init__.py
  tests/integration/modules/test_cp.py
  tests/integration/modules/test_state.py
  tests/integration/states/test_file.py
  tests/integration/states/test_pip_state.py
  tests/integration/states/test_renderers.py
  tests/unit/utils/test_thin.py
Labels: Reviewers Assigned

#53427 add fedora 29 tests to pr's
  .ci/kitchen-fedora29-py2
  .ci/kitchen-fedora29-py3
Labels: Reviewers Assigned

#53522 [2017.7.9] Update pipelines to work on old and new jenkins
  .ci/docs
  .ci/kitchen-centos7-py2
  .ci/kitchen-centos7-py3
  .ci/kitchen-ubuntu1604-py2
  .ci/kitchen-ubuntu1604-py3
  .ci/kitchen-windows2016-py2
  .ci/kitchen-windows2016-py3
  .ci/lint
Labels: Reviewers Assigned

#53266 [2017.7] The flaky decorator should go through `(setUp|tearDown)()` at each attempt
  tests/support/helpers.py
Labels: Reviewers Assigned

#53265 [2017.7.9] The flaky decorator should go through `(setUp|tearDown)()` at each attempt
  tests/support/helpers.py
Labels: Reviewers Assigned

#53448 [2017.7] Merge forward from 2017.7.9 to 2017.7
  noxfile.py
  requirements/static/py2.7/tcp-arch.txt
  requirements/static/py2.7/tcp-centos-6.txt
  requirements/static/py2.7/tcp-centos-7.txt
  requirements/static/py2.7/tcp-debian-8.txt
  requirements/static/py2.7/tcp-debian-9.txt
  requirements/static/py2.7/tcp-fedora-28.txt
  requirements/static/py2.7/tcp-fedora-29.txt
  requirements/static/py2.7/tcp-opensuse-42.txt
  requirements/static/py2.7/tcp-opensuse-leap-15.txt
  requirements/static/py2.7/tcp-osx.txt
  requirements/static/py2.7/tcp-ubuntu-16.04.txt
  requirements/static/py2.7/tcp-ubuntu-18.04.txt
  requirements/static/py2.7/tcp-windows.txt
  requirements/static/py3.4/tcp-arch.txt
  requirements/static/py3.4/tcp-centos-7.txt
  requirements/static/py3.4/tcp-debian-8.txt
  requirements/static/py3.4/tcp-debian-9.txt
  requirements/static/py3.4/tcp-fedora-28.txt
  requirements/static/py3.4/tcp-fedora-29.txt
  requirements/static/py3.4/tcp-opensuse-42.txt
  requirements/static/py3.4/tcp-opensuse-leap-15.txt
  requirements/static/py3.4/tcp-ubuntu-16.04.txt
  requirements/static/py3.4/tcp-ubuntu-18.04.txt
  requirements/static/py3.5/tcp-arch.txt
  requirements/static/py3.5/tcp-centos-7.txt
  requirements/static/py3.5/tcp-debian-8.txt
  requirements/static/py3.5/tcp-debian-9.txt
  requirements/static/py3.5/tcp-fedora-28.txt
  requirements/static/py3.5/tcp-fedora-29.txt
  requirements/static/py3.5/tcp-opensuse-42.txt
  requirements/static/py3.5/tcp-opensuse-leap-15.txt
  requirements/static/py3.5/tcp-osx.txt
  requirements/static/py3.5/tcp-ubuntu-16.04.txt
  requirements/static/py3.5/tcp-ubuntu-18.04.txt
  requirements/static/py3.5/tcp-windows.txt
  requirements/static/py3.6/tcp-arch.txt
  requirements/static/py3.6/tcp-centos-7.txt
  requirements/static/py3.6/tcp-debian-8.txt
  requirements/static/py3.6/tcp-debian-9.txt
  requirements/static/py3.6/tcp-fedora-28.txt
  requirements/static/py3.6/tcp-fedora-29.txt
  requirements/static/py3.6/tcp-opensuse-42.txt
  requirements/static/py3.6/tcp-opensuse-leap-15.txt
  requirements/static/py3.6/tcp-osx.txt
  requirements/static/py3.6/tcp-ubuntu-16.04.txt
  requirements/static/py3.6/tcp-ubuntu-18.04.txt
Labels: Reviewers Assigned

#52936 Fix python3 get imageid
  salt/cloud/clouds/ec2.py
  tests/unit/cloud/clouds/test_ec2.py
Labels: Reviewers Assigned

#53602 CI pipelines fixes to support old and new jenkins
  .ci/docs
  .ci/kitchen-centos7-py2
  .ci/kitchen-centos7-py3
  .ci/kitchen-ubuntu1604-py2
  .ci/kitchen-ubuntu1604-py3
  .ci/kitchen-windows2016-py2
  .ci/kitchen-windows2016-py3
  .ci/lint
  tox.ini
Labels: Reviewers Assigned

#53605 Adds tests for states/win_iis.py
  salt/states/win_iis.py
  tests/unit/states/test_win_iis.py
Labels: Reviewers Assigned

#53370 Update access to str/bytes with to_unicode/to_bytes for Python 3 compatibility
  salt/modules/at_solaris.py
  salt/modules/gpg.py
  tests/unit/modules/test_gpg.py
Labels: 2018.3, 2019.2.1, Reviewers Assigned

#51971 Add gitfs and git_pillar fallback branch
  doc/topics/tutorials/gitfs.rst
  salt/config/__init__.py
  salt/fileserver/gitfs.py
  salt/modules/virtualenv_mod.py
  salt/pillar/git_pillar.py
  salt/utils/gitfs.py
  tests/integration/files/file/base/git_pillar/http/init.sls
  tests/integration/pillar/test_git_pillar.py
  tests/support/gitfs.py
  tests/unit/fileserver/test_gitfs.py
  tests/unit/modules/test_virtualenv_mod.py
Labels: Neon, Reviewers Assigned

#53413 Create a state for the cpan module
  doc/ref/modules/all/salt.modules.cpan.rst
  doc/ref/states/all/index.rst
  doc/ref/states/all/salt.states.cpan.rst
  salt/modules/cpan.py
  salt/states/cpan.py
  tests/integration/states/test_cpan.py
  tests/unit/modules/test_cpan.py
Labels: Reviewers Assigned

#53466 More robust beacon state test
  .ci/kitchen-amazon2-py2
  .ci/kitchen-amazon2-py3
  salt/beacons/__init__.py
  salt/modules/beacons.py
  tests/integration/shell/test_minion.py
  tests/integration/states/test_beacon.py
Labels: 2019.2.1, Reviewers Assigned

#53295 Recurse kwarg of state.directory state shall be a list or None
  tests/integration/states/test_file.py
Labels: 2019.2.1, Reviewers Assigned

#53587 Forward port from 2018.3 Add event_listen_queue_max_seconds to fix #53411
  conf/master
  doc/topics/releases/2018.3.5.rst
  salt/config/__init__.py
  salt/utils/event.py
Labels: Reviewers Assigned

#53412 Stale events 53411
  conf/master
  doc/topics/releases/2018.3.5.rst
  salt/config/__init__.py
  salt/utils/event.py
Labels: Needs Testcase, Reviewers Assigned

#53627 Cherry pick pr 53370 from 2018.3 into 2019.2.1
  salt/modules/at_solaris.py
  salt/modules/gpg.py
  tests/unit/modules/test_gpg.py
Labels: 2019.2.1
