Repository saltstack/salt, pull requests merged in 2019-11, with the labels that each got.

#54674 [master] Porting #52562 to master
  salt/modules/aptpkg.py
Labels: master-port

#54536 [master] Porting #52589 to master
  salt/states/blockdev.py
  tests/unit/states/test_blockdev.py
Labels: master-port

#54549 [master] Porting #50371 to master
  salt/modules/purefb.py
Labels: master-port

#54993 master-port 52187 and 52351
  doc/topics/releases/neon.rst
  doc/topics/slots/index.rst
  salt/state.py
  tests/unit/test_state.py
Labels: master-port

#54571 [master] Porting #54154 to master
  tests/integration/modules/test_cp.py
Labels: master-port

#54579 [master] Porting #52214 to master
  salt/states/beacon.py
Labels: master-port

#54596 [master] Porting #51343 to master
  salt/modules/debian_ip.py
  salt/modules/rh_ip.py
  tests/unit/modules/test_debian_ip.py
  tests/unit/modules/test_rh_ip.py
Labels: master-port

#54598 [master] Porting #51299 to master
  tests/unit/transport/test_zeromq.py
Labels: master-port

#54687 [master] Porting #52574 to master
  salt/modules/virt.py
  tests/unit/modules/test_virt.py
Labels: master-port

#54984 master-port 50197 and 51900
  doc/ref/states/all/index.rst
  doc/ref/states/all/salt.states.saltutil.rst
  doc/topics/development/modules/index.rst
  salt/states/saltutil.py
  tests/unit/states/test_saltutil.py
Labels: master-port

#54542 [master] Porting #50306 to master
  salt/modules/opkg.py
  tests/unit/modules/test_opkg.py
Labels: master-port

#54565 [master] Porting #53229 to master
  tests/integration/states/test_cmd.py
Labels: master-port

#54587 [master] Porting #50736 to master
  salt/loader.py
Labels: master-port

#54605 [master] Porting #50523 to master
  salt/utils/pkg/rpm.py
  tests/unit/utils/test_pkg.py
Labels: master-port

#55150 [master] Add 'ppc64le' as a valid RPM package architecture
  salt/utils/pkg/rpm.py
Labels: master-port

#54677 [master] Porting #49293 to master
  doc/ref/modules/index.rst
Labels: master-port

#54666 [master] Porting #49616 to master
  doc/topics/grains/index.rst
Labels: master-port

#54606 [master] Porting #52698 to master
  tests/conftest.py
Labels: master-port

#54588 [master] Porting #52786 to master
  salt/states/user.py
  tests/integration/states/test_user.py
Labels: master-port

#55190 [master] Port #52773 and #51427
  doc/topics/development/modules/index.rst
  salt/minion.py
  salt/modules/saltutil.py
  salt/runners/saltutil.py
  salt/states/saltutil.py
  tests/integration/executors/__init__.py
  tests/integration/files/file/base/_executors/arg.py
  tests/integration/minion/test_executor.py
  tests/integration/modules/test_saltutil.py
  tests/unit/test_module_names.py
Labels: master-port

#55001 (Backport 52150) mdadm_raid: Optionally ignore errors on examine.
  salt/modules/mdadm_raid.py
  salt/states/mdadm_raid.py
  tests/unit/modules/test_mdadm_raid.py
Labels: master-port

#54546 [master] Porting #49843 to master
  salt/states/file.py
  tests/unit/states/test_file.py
Labels: master-port

#54983 master-port 51949 and 51996
  doc/ref/engines/all/index.rst
  doc/ref/engines/all/salt.engines.hipchat.rst
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.hipchat.rst
  doc/ref/returners/all/index.rst
  doc/ref/returners/all/salt.returners.hipchat_return.rst
  doc/ref/states/all/index.rst
  doc/ref/states/all/salt.states.hipchat.rst
  doc/topics/releases/neon.rst
  salt/engines/hipchat.py
  salt/modules/hipchat.py
  salt/returners/hipchat_return.py
  salt/states/hipchat.py
  tests/unit/modules/test_hipchat.py
  tests/unit/states/test_hipchat.py
Labels: master-port

#54656 [master] Porting #51385 to master
  salt/states/disk.py
  tests/unit/states/test_disk.py
Labels: master-port

#55309 Skip `test_pkg_upgrade_has_pending_upgrades` on Arch Linux
  tests/integration/modules/test_pkg.py
Labels: Test Failure

#54576 [master] Porting #52933 to master
  salt/beacons/inotify.py
  tests/unit/beacons/test_inotify.py
Labels: master-port

#55351 Fix virt.get_hypervisor()
  salt/modules/virt.py
  tests/unit/modules/test_virt.py
Labels: Confirmed

#55411 [docs] fix documentation grammar about substring_in_list jinja filter
  doc/topics/jinja/index.rst
Labels: Documentation

#55342 Slack webhook returner
  salt/returners/slack_webhook_return.py
  tests/unit/returners/test_slack_webhook_return.py
Labels: master-port

#55422 Fix various typos in the comments
  salt/modules/zpool.py
  salt/states/zpool.py
  salt/utils/zfs.py
Labels: Documentation

#55423 Port #51245 to master
  salt/config/__init__.py
  salt/utils/immutabletypes.py
  tests/integration/grains/test_core.py
  tests/unit/beacons/test_status.py
  tests/unit/engines/test_slack.py
  tests/unit/modules/test_boto_apigateway.py
  tests/unit/modules/test_boto_cloudtrail.py
  tests/unit/modules/test_boto_cloudwatch_event.py
  tests/unit/modules/test_boto_cognitoidentity.py
  tests/unit/modules/test_boto_elasticsearch_domain.py
  tests/unit/modules/test_boto_elb.py
  tests/unit/modules/test_boto_iot.py
  tests/unit/modules/test_boto_lambda.py
  tests/unit/modules/test_boto_route53.py
  tests/unit/modules/test_boto_s3_bucket.py
  tests/unit/modules/test_boto_secgroup.py
  tests/unit/modules/test_boto_vpc.py
  tests/unit/modules/test_dockermod.py
  tests/unit/modules/test_nacl.py
  tests/unit/modules/test_solarisipspkg.py
  tests/unit/modules/test_state.py
  tests/unit/modules/test_zfs.py
  tests/unit/modules/test_zpool.py
  tests/unit/states/test_boto_apigateway.py
  tests/unit/states/test_boto_cloudfront.py
  tests/unit/states/test_boto_cloudtrail.py
  tests/unit/states/test_boto_cloudwatch_event.py
  tests/unit/states/test_boto_cognitoidentity.py
  tests/unit/states/test_boto_elasticsearch_domain.py
  tests/unit/states/test_boto_iot.py
  tests/unit/states/test_boto_lambda.py
  tests/unit/states/test_boto_s3_bucket.py
  tests/unit/states/test_boto_sqs.py
  tests/unit/states/test_boto_vpc.py
  tests/unit/states/test_saltmod.py
  tests/unit/states/test_zfs.py
  tests/unit/states/test_zpool.py
  tests/unit/test_minion.py
  tests/unit/test_proxy_minion.py
  tests/unit/utils/test_cache.py
  tests/unit/utils/test_parsers.py
Labels: master-port
