Repository saltstack/salt, pull requests merged in 2019-10, with the labels that each got.

#54778 fix broken salt-cloud openstack query
  salt/cloud/clouds/openstack.py
  tests/unit/cloud/clouds/test_openstack.py
Labels: Needs Testcase

#54845 Remove debug print
  tests/integration/master/test_event_return.py
Labels: 2019.2.1, 2019.2.2

#54684 [master] Porting #49257 to master
  doc/topics/tutorials/multimaster.rst
Labels: master-port

#54558 [master] Porting #52752 to master
  doc/Makefile
  doc/_ext/saltdomain.py
  doc/conf.py
Labels: master-port

#54672 [master] Porting #51362 to master
  salt/modules/pillar.py
Labels: master-port

#54671 [master] Porting #51506 to master
  salt/states/file.py
Labels: master-port

#54555 [master] Porting #52948 to master
  doc/_ext/saltdomain.py
Labels: master-port

#54914 Corrected grammar in cloud docs
  doc/man/salt-cloud.1
  doc/ref/cli/salt-cloud.rst
  salt/utils/parsers.py
Labels: Documentation

#54534 [master] Porting #49472 to master
  doc/topics/releases/neon.rst
Labels: master-port

#54537 [master] Porting #51856 to master
  salt/states/file.py
Labels: master-port

#54633 [master] Porting #51705 to master
  doc/topics/development/modules/external_pillars.rst
Labels: master-port

#54545 [master] Porting #49906 to master
  doc/ref/states/ordering.rst
Labels: master-port

#54659 [master] Porting #49664 to master
  salt/states/user.py
Labels: Documentation, master-port

#54554 [master] Porting #52608 to master
  doc/topics/thorium/index.rst
Labels: Documentation, master-port

#54561 [master] Porting #53892 to master
  .github/CODEOWNERS
Labels: master-port

#54562 [master] Porting #52633 to master
  .github/PULL_REQUEST_TEMPLATE.md
Labels: master-port

#54563 [master] Porting #51165 to master
  doc/topics/releases/releasecandidate.rst
Labels: Documentation, master-port

#54538 [master] Porting #51287 to master
  doc/topics/releases/2019.2.0.rst
Labels: master-port

#54548 [master] Porting #50953 to master
  doc/ref/configuration/minion.rst
  salt/grains/nvme.py
  tests/unit/grains/test_nvme.py
Labels: master-port
