Repository saltstack/salt, pull requests merged in 2019-08, with the labels that each got.

#51628 Update `formulas.rst` with new IRC channel and links to IRC logs
  doc/topics/development/conventions/formulas.rst
Labels: Reviewers Assigned

#53900 Fix inconsistent full names in LGPO
  salt/modules/win_lgpo.py
  tests/integration/modules/test_win_lgpo.py
Labels: 2019.2.1

#54033 Backport #53311 to 2019.2.1
  salt/modules/win_service.py
  tests/unit/modules/test_win_service.py
Labels: 2019.2.1

#53499 Updates to slsutil.banner
  salt/modules/slsutil.py
  tests/unit/modules/test_slsutil.py
Labels: Bugfix - back-port, Neon, Reviewers Assigned

#54270 [2019.2.1] Speedup testing helpers decorators
  tests/support/helpers.py
Labels: WarRoom

#54263 [2019.2.1] Exit test suite if test daemons fail to start
  tests/integration/__init__.py
  tests/runtests.py
  tests/support/parser/__init__.py
Labels: WarRoom

#54278 Correctly detect when an ms_azure instance is deleted
  tests/integration/cloud/helpers/cloud_test_base.py
Labels: WarRoom

#54277 Win runas plus
  salt/utils/process.py
  salt/utils/win_runas.py
  tests/unit/utils/test_process.py
Labels: WarRoom

#54252 [2019.2.1] More control on spun test deamons on git pillar tests
  tests/integration/files/file/base/git_pillar/http/files/nginx.conf
  tests/integration/files/file/base/git_pillar/http/files/uwsgi.yml
  tests/integration/files/file/base/git_pillar/http/init.sls
  tests/integration/files/file/base/git_pillar/ssh/server/init.sls
  tests/support/gitfs.py
  tests/support/helpers.py
  tests/support/unit.py
Labels: WarRoom

#54247 2019.2.1 with multimaster bb fixes
  salt/minion.py
  salt/modules/beacons.py
  tests/integration/__init__.py
  tests/integration/files/conf/mm_master
  tests/integration/files/conf/mm_minion
  tests/integration/files/conf/mm_sub_master
  tests/integration/files/conf/mm_sub_minion
  tests/integration/files/engines/runtests_engine.py
  tests/integration/modules/test_beacons.py
  tests/multimaster/__init__.py
  tests/multimaster/beacons/__init__.py
  tests/multimaster/beacons/test_inotify.py
  tests/multimaster/minion/__init__.py
  tests/multimaster/minion/test_event.py
  tests/multimaster/modules/__init__.py
  tests/multimaster/modules/test_test.py
  tests/runtests.py
  tests/support/case.py
  tests/support/mixins.py
  tests/support/parser/__init__.py
  tests/support/paths.py
  tests/support/runtests.py
  tests/unit/test_module_names.py
Labels: WarRoom

#54259 Call os.fork less to avoid race conditions
  salt/master.py
  salt/metaproxy/proxy.py
  salt/minion.py
  salt/utils/process.py
  salt/utils/schedule.py
  tests/integration/shell/test_call.py
  tests/unit/utils/test_process.py
Labels: WarRoom
