Repository saltstack/salt, pull requests merged in 2020-09, with the labels that each got.

#57519 Fixed ec2 cloud unit test.
  salt/cloud/clouds/ec2.py
  salt/crypt.py
  tests/unit/cloud/clouds/test_ec2.py
  tests/unit/test_crypt.py
Labels: Has Testcase

#57608 Add/update changelog entries
  CHANGELOG.md
Labels: Documentation

#57503 Documentation update on baredocs
  salt/modules/baredoc.py
Labels: Documentation, has-failing-test

#57825 Pass cmd.run arguments to onlyif/unless cmd execution
  changelog/57760.fixed
  salt/state.py
  tests/unit/test_state.py
Labels: has-failing-test

#58299 Force version type to string in deb_postgres module
  changelog/50899.fixed
  salt/modules/deb_postgres.py
  tests/unit/modules/test_deb_postgres.py
Labels: Bug, Magnesium, Severity: Medium

#58072 [merge jam] port 48954 - Add beacon log tag example
  salt/beacons/log_beacon.py
Labels: Documentation, master-port

#58215 Fix docstring examples that had been erroneously changed
  salt/modules/salt_version.py
Labels: Documentation

#58136 kubeadm: detect empty token lists
  changelog/58116.fixed
  salt/modules/kubeadm.py
  tests/unit/modules/test_kubeadm.py
Labels: Bug, Magnesium, Severity: Medium, has-failing-test

#58385 Fix Docs: Salt 3000 onlyif targeting with grains cannot have a space in function query
  doc/ref/states/requisites.rst
Labels: Documentation

#58106 [merge jam] Master Port #54069
  tests/unit/modules/test_win_iis.py
Labels: master-port

#58105 [merge jam] Master port 54157
  tests/integration/states/test_cmd.py
Labels: master-port

#58419 add newer versions of google custom search engines
  doc/conf.py
Labels: Documentation, Magnesium

#58414 Add Welcome bot
  .github/config.yml
Labels: Magnesium

#58341 Bump timelib to 0.2.5 to fix Mac OSX build issues
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.5/freebsd.txt
  requirements/static/py3.5/linux.txt
  requirements/static/py3.5/windows.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.6/freebsd.txt
  requirements/static/py3.6/linux.txt
  requirements/static/py3.6/windows.txt
  requirements/static/py3.7/darwin.txt
  requirements/static/py3.7/freebsd.txt
  requirements/static/py3.7/linux.txt
  requirements/static/py3.7/windows.txt
  requirements/static/py3.8/darwin.txt
  requirements/static/py3.8/freebsd.txt
  requirements/static/py3.8/linux.txt
  requirements/static/py3.9/darwin.txt
  requirements/static/py3.9/freebsd.txt
  requirements/static/py3.9/linux.txt
Labels: Magnesium

#58495 Fail gracefully in case of failure to get the AutoUpdate object
  salt/utils/win_update.py
Labels: Magnesium

#58540 Automatically remove import comments
  .pre-commit-config.yaml
  cicd/jenkins/pre-commit
  tasks/__init__.py
  tasks/imports.py
Labels: Magnesium

#58545 Fix typo in documentation
  doc/ref/states/requisites.rst
Labels: Documentation, Magnesium

#58465 Fix virt update when cpu and memory are changed
  salt/modules/virt.py
  tests/unit/modules/test_virt.py
Labels: Bug, Magnesium, Regression, Severity: High

#58491 virt: use the pool path in case the volume doesn't exist
  salt/modules/virt.py
  tests/pytests/unit/modules/virt/conftest.py
  tests/pytests/unit/modules/virt/test_domain.py
  tests/unit/modules/test_virt.py
Labels: Magnesium

#58509 Keep support for both authentication configurations in kubernetes
  salt/modules/kubernetesmod.py
Labels: Magnesium, Needs Testcase

#58569 Properly fix memory setting regression in virt.update
  salt/modules/virt.py
  tests/unit/modules/test_virt.py
Labels: Magnesium

#58457 Correct typo in spelling enable_fqdns_grains
  conf/minion
Labels: Documentation, Magnesium

#53415 Add usage example to documentation of file.copy state
  salt/states/file.py
Labels: Documentation, Magnesium, has-failing-test, master-port

#58556 fix spot instance creation
  Gemfile
Labels: Magnesium

#58562 use spot instance for windows2019
  cicd/jenkins/kitchen-windows2019-py3
  cicd/jenkins/kitchen-windows2019-py3-pytest
Labels: Magnesium

#58532 Update issue templates docs
  .github/ISSUE_TEMPLATE/docs.md
Labels: Documentation, Magnesium

#56893 Port #49697 and #49926 to master
  requirements/static/linux.in
  requirements/static/py3.5/linux.txt
  requirements/static/py3.6/linux.txt
  requirements/static/py3.7/linux.txt
  requirements/static/py3.8/linux.txt
  requirements/static/py3.9/linux.txt
  salt/modules/nilrt_ip.py
  tests/integration/modules/test_nilrt_ip.py
  tests/unit/modules/test_nilrt_ip.py
Labels: Has Testcase, master-port

#57288 Allow to override git_pillar_base per-remote (Port #51640 to master)
  salt/pillar/git_pillar.py
  salt/utils/gitfs.py
  tests/integration/pillar/test_git_pillar.py
Labels: Magnesium, has-failing-test, master-port

#58040 Fix multijobs executors
  salt/minion.py
  tests/integration/minion/test_executor.py
Labels: Magnesium

#58396 modules/opkg: create restartcheck state if it's dir doesn't exist
  salt/modules/opkg.py
  tests/unit/modules/test_opkg.py
Labels: Magnesium

#58179 Rename _schedule.conf on YAML parse error
  changelog/56216.fixed
  changelog/58177.fixed
  salt/config/__init__.py
  salt/modules/boto_elbv2.py
  salt/modules/boto_ssm.py
  salt/modules/network.py
  tests/unit/test_config.py
Labels: Magnesium

#58525 Add refresh arg to update() docs; pre-commit fixes
  salt/modules/aptpkg.py
Labels: Bug, Documentation, Magnesium, Severity: Low, docstring-update

#55653 Fix for #55652 - Proc file naming
  salt/utils/minion.py
  tests/unit/utils/test_minion.py
Labels: Magnesium, Proxy Minion, ZD, has-failing-test

#58013 Fix __mount_device wrapper
  changelog/58012.fixed
  salt/states/btrfs.py
  tests/unit/states/test_btrfs.py
Labels: Magnesium, Severity: Medium

#58390 Updating to v2.0 of contributor covenant
  CODE_OF_CONDUCT.md
Labels: Documentation

#58530 Remove old documented pending reboot key
  changelog/58530.fixed
  salt/utils/win_system.py
Labels: Magnesium

#58523 Add restart delay when minion fails to start
  pkg/windows/installer/Salt-Minion-Setup.nsi
Labels: Magnesium

#58505 fix: minor clarification in the grains docs
  salt/grains/fibre_channel.py
  salt/grains/iscsi.py
  salt/grains/junos.py
  salt/grains/metadata.py
  salt/grains/nvme.py
  salt/grains/opts.py
Labels: Documentation, Magnesium

#57646 Improve macOS service naming support
  changelog/57878.fixed
  salt/modules/mac_service.py
  tests/unit/modules/test_mac_service.py
Labels: Bug, Mac OS, Magnesium, Severity: High, has-failing-test

#58144 Fix mac_service failures on Big Sur.
  changelog/58143.fixed
  tests/unit/utils/test_mac_utils.py
Labels: Bug, Mac OS, Magnesium, Severity: High

#55876 Fixed regex in 'save_config' to avoid issue if device name is md1, PA…
  salt/modules/mdadm_raid.py
  tests/unit/modules/test_mdadm_raid.py
Labels: has-failing-test

#57911 Remove incorrect documentation
  doc/topics/development/modules/developing.rst
Labels: Documentation, Magnesium, has-failing-test
