Repository saltstack/salt, pull requests merged in 2020-04, with the labels that each got.

#56492 Remove Py2 Pipelines
  .ci/kitchen-amazon1-py2
  .ci/kitchen-amazon2-py2
  .ci/kitchen-archlts-py2
  .ci/kitchen-centos6-py2
  .ci/kitchen-centos7-py2
  .ci/kitchen-centos7-py2-cloud
  .ci/kitchen-centos7-py2-m2crypto
  .ci/kitchen-centos7-py2-proxy
  .ci/kitchen-centos7-py2-pycryptodomex
  .ci/kitchen-centos7-py2-tcp
  .ci/kitchen-centos7-py2-tornado
  .ci/kitchen-debian8-py2
  .ci/kitchen-debian9-py2
  .ci/kitchen-fedora30-py2
  .ci/kitchen-macosxhighsierra-py2
  .ci/kitchen-macosxmojave-py2
  .ci/kitchen-macosxsierra-py2
  .ci/kitchen-opensuse15-py2
  .ci/kitchen-ubuntu1604-py2
  .ci/kitchen-ubuntu1604-py2-m2crypto
  .ci/kitchen-ubuntu1604-py2-proxy
  .ci/kitchen-ubuntu1604-py2-pycryptodomex
  .ci/kitchen-ubuntu1604-py2-tcp
  .ci/kitchen-ubuntu1604-py2-tornado
  .ci/kitchen-ubuntu1804-py2
  .ci/kitchen-windows2016-py2
  .ci/kitchen-windows2019-py2
Labels: Sodium

#56518 Fixed typo in requisites.rst
  doc/ref/states/requisites.rst
Labels: Merge Ready

#56520 Fixed typo in requisites.rst
  doc/ref/states/requisites.rst
Labels: Merge Ready

#56459 Add grains_cache_expiration to minion conf doc
  doc/ref/configuration/minion.rst
Labels: Documentation

#56485 Update issue and PR templates, add config, stale bot not
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/stale.yml
Labels: Community, Merge Ready

#56493 [docs] Fix incorrect smartos.vm_present example
  salt/states/smartos.py
Labels: Documentation, Merge Ready

#56474 Add virtual module documentation for sysctl
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.sysctl.rst
Labels: Documentation, Merge Ready

#56550 56449 fetch master pubkey
  salt/wheel/key.py
  tests/integration/wheel/test_key.py
Labels: Merge Ready

#56488 Add new ssh_pre_flight roster option
  conf/master
  doc/ref/cli/salt-ssh.rst
  doc/ref/configuration/master.rst
  doc/topics/releases/sodium.rst
  doc/topics/ssh/roster.rst
  salt/client/ssh/__init__.py
  salt/config/__init__.py
  salt/utils/parsers.py
  tests/integration/ssh/test_pre_flight.py
  tests/support/case.py
  tests/unit/client/test_ssh.py
  tests/unit/test_module_names.py
Labels: Merge Ready, Sodium

#56463 Fix typo on msgpack version when sanitizing msgpack kwargs
  salt/utils/msgpack.py
Labels: Merge Ready

#56392 virt._get_domain: don't raise an exception if there is no VM
  salt/modules/virt.py
  tests/unit/modules/test_virt.py
Labels: Merge Ready

#56382 doc: Update kiwi url
  doc/topics/tutorials/cloud_controller.rst
Labels: Documentation, Merge Ready

#56432 [DOC] Fix example for `defaults.merge` function
  salt/modules/defaults.py
Labels: Documentation, Merge Ready

#56420 Fixed documentation of docker_image.load
  salt/states/docker_image.py
Labels: Documentation, Merge Ready

#52504 Add header for clean_dynamic_modules
  doc/ref/configuration/minion.rst
Labels: Documentation, Merge Ready, Reviewers Assigned

#55095 Docs: Add SSH Key auth section to libvirt #55094
  doc/ref/clouds/all/index.rst
  doc/ref/clouds/all/salt.cloud.clouds.libvirt.rst
  doc/topics/cloud/libvirt.rst
Labels: Documentation, Low-Hanging Fruit

#54699 Clarify how to get the master fingerprint
  doc/ref/configuration/minion.rst
Labels: Documentation, Merge Ready

#55895 Fix broken documentation examples
  salt/wheel/key.py
Labels: Documentation, Merge Ready

#56281 Doc: 2018.3.0 availability for sdb yaml gpg render
  salt/sdb/yaml.py
Labels: Documentation, Merge Ready, ZD

#56286 Remove dbus warnings from snapper __virtual__
  salt/modules/snapper.py
Labels: Merge Ready, ZD

#56136 Fix typo in installation docs
  doc/topics/installation/index.rst
Labels: Documentation

#56374 Fix docs in win_wua
  salt/modules/win_wua.py
Labels: Documentation

#56608 [master] Only set createhome to False on Windows
  salt/states/user.py
  tests/integration/states/test_user.py
Labels: Merge Ready

#56011 Small typo in napalm.junos_rpc docstring
  salt/modules/napalm_mod.py
Labels: Documentation, Merge Ready, Sodium

#56303 doc: fix typo in windows-package-manager.rst
  doc/topics/windows/windows-package-manager.rst
Labels: Documentation, Merge Ready

#56026 Skip test_drift_detector if required test file is missing
  tests/unit/test_zypp_plugins.py
Labels: Core

#56162 Change documented x509 salt mine example, fixes #56142
  salt/states/x509.py
Labels: Documentation, Merge Ready

#56193 Update check_password function for newer RabbitMQ versions.
  salt/modules/rabbitmq.py
  tests/unit/modules/test_rabbitmq.py
Labels: Needs Testcase

#56194 Update salt icon
  pkg/windows/buildenv/salt.ico
Labels: Sodium

#56481 Support annotated tags in pygit2 git provider
  salt/utils/gitfs.py
  tests/unit/utils/test_gitfs.py
Labels: Merge Ready

#56396 Master fix aptpkg systemd call
  salt/modules/aptpkg.py
  tests/unit/modules/test_aptpkg.py
Labels: Merge Ready

#56282 Fix token modules doc header
  doc/ref/tokens/all/index.rst
Labels: Documentation, Merge Ready, Sodium

#56274 Add salt-api log file to log rotation
  pkg/salt-common.logrotate
Labels: Merge Ready

#56237 docs(index.rst): fix alphabetical ordering and remove duplicates
  CHANGELOG.md
  doc/ref/cli/index.rst
  doc/ref/grains/all/index.rst
  doc/ref/modules/all/index.rst
  doc/ref/proxy/all/index.rst
  doc/ref/states/all/index.rst
Labels: Documentation, Merge Ready

#55206 Update to more current SLE version numbers
  doc/topics/installation/suse.rst
Labels: Documentation

#55126 Respect argline passed into jinja renderer
  salt/renderers/jinja.py
  tests/integration/files/file/base/_renderers/issue55124.py
  tests/integration/files/file/base/issue-55124.sls
  tests/integration/modules/test_state.py
  tests/unit/utils/test_jinja.py
Labels: Sodium

#54683 [master] Porting #49494 to master
  salt/renderers/gpg.py
Labels: Documentation, Sodium, master-port

#56462 Fix parsing of 'renew' parameter in acme.cert
  salt/modules/acme.py
  tests/unit/modules/test_acme.py
Labels: Merge Ready

#54717 Use correct keys from group_info in group_install.
  salt/modules/yumpkg.py
  tests/unit/modules/test_yumpkg.py
Labels: Has Testcase

#54371 Better support comments in mysql files
  salt/modules/mysql.py
  tests/integration/files/file/base/mysql/update_query.sql
  tests/unit/modules/test_mysql.py
Labels: Merge Ready

#56616 Move all PR requirements under same heading
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#56355 Fix versionlock plugin detection for yum/dnf - RHEL/CentOS 8
  salt/modules/yumpkg.py
  tests/unit/modules/test_kernelpkg_linux_yum.py
  tests/unit/modules/test_yumpkg.py
Labels: Merge Ready

#56370 Add systempath grain
  doc/topics/releases/sodium.rst
  salt/grains/core.py
  tests/unit/grains/test_core.py
Labels: Merge Ready

#56004 Ensure the disk is free to use after seed.apply
  salt/modules/guestfs.py
  salt/modules/mount.py
  salt/modules/seed.py
  tests/unit/modules/test_guestfs.py
  tests/unit/modules/test_mount.py
  tests/unit/modules/test_seed.py
Labels: File Servers

#55806 Add custom grain information to salt-ssh index page
  doc/topics/ssh/index.rst
Labels: Documentation

#54985 Master-port #52441
  salt/modules/cron.py
  tests/unit/modules/test_cron.py
Labels: master-port

#56230 hide duplicate function in saltcheck docs
  doc/ref/modules/all/salt.modules.saltcheck.rst
Labels: Merge Ready

#56369 Make "salt.ext.tornado.gen" to use "salt.ext.backports_abc" on Python 2
  salt/ext/tornado/gen.py
Labels: Merge Ready

#55386 Port 54636
  salt/states/zpool.py
  tests/unit/states/test_zpool.py
Labels: Merge Ready

#56630 Add warning about resource useage for git python
  doc/topics/tutorials/gitfs.rst
Labels: Documentation

#56334 Fix bad RST in consul_pillar docstring
  salt/pillar/consul_pillar.py
Labels: Documentation

#56221 Make slots work with parallel=true
  salt/state.py
  tests/unit/test_state.py
Labels: Merge Ready

#56643 Add warning in doc about issue #56642
  doc/topics/development/contributing.rst
Labels: Documentation, Merge Ready

#56558 Fix file.get_selinux_context with directories
  salt/modules/file.py
  tests/integration/modules/test_file.py
Labels: Merge Ready

#56379 Fixes AzureRM create_object_model util
  salt/utils/azurearm.py
  tests/unit/utils/test_azurearm.py
Labels: Merge Ready

#56075 change URLs for contributing to point to master branch of docs
  .github/CONTRIBUTING.md
Labels: Documentation

#56641 [WIP] Add towncrier to manage CHANGELOG.md
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  CHANGELOG.md
  changelog/55836.added
  doc/topics/development/changelog.rst
  noxfile.py
  pyproject.toml
  requirements/static/changelog.in
  requirements/static/py3.5/changelog.txt
  requirements/static/py3.6/changelog.txt
  requirements/static/py3.7/changelog.txt
Labels: Awesome

#56614 [master] Support in host module and state module for comments
  salt/modules/hosts.py
  salt/states/host.py
  tests/integration/modules/test_hosts.py
  tests/unit/modules/test_hosts.py
  tests/unit/states/test_host.py
Labels: Merge Ready

#53443 (Backport 53381) systemd_service: add firstboot function
  salt/modules/systemd_service.py
  tests/unit/modules/test_systemd_service.py
Labels: Reviewers Assigned

#56352 Removal of Windows msi installer related function
  salt/version.py
Labels: Critical, P1, Sodium

#56381 Fix 54501
  salt/state.py
  tests/unit/test_state.py
Labels: Merge Ready

#56414 Remove deprecated bits for Sodium in virt
  salt/modules/virt.py
  salt/states/virt.py
  tests/unit/modules/test_virt.py
  tests/unit/states/test_virt.py
Labels: Merge Ready

#56581 update panos/commit task in module example
  salt/states/panos.py
Labels: Documentation, Merge Ready

#56626 [master] Updating fail_with and succeed_with functions to use comment argument
  salt/states/test.py
  tests/unit/states/test_test.py
Labels: High Severity, Release Blocker, Sodium

#56627 Add new salt-ssh set_path option
  .ci/kitchen-macosxhighsierra-py3
  .ci/kitchen-macosxmojave-py3
  .ci/kitchen-macosxsierra-py3
  CHANGELOG.md
  doc/topics/releases/sodium.rst
  doc/topics/ssh/roster.rst
  salt/client/ssh/__init__.py
  tests/integration/__init__.py
  tests/integration/ssh/test_deploy.py
  tests/integration/ssh/test_master.py
  tests/unit/client/test_ssh.py
Labels: Sodium

#56635 [master] check kwargs for expected arguments in salt.utils.functools.call_function
  salt/states/module.py
  salt/utils/functools.py
  tests/unit/states/test_module.py
Labels: Sodium

#56671 update sphinx to 3.0.1
  doc/conf.py
  doc/glossary.rst
  doc/ref/configuration/index.rst
  doc/ref/configuration/master.rst
  doc/ref/configuration/minion.rst
  doc/topics/beacons/index.rst
  doc/topics/cloud/openstack.rst
  doc/topics/grains/index.rst
  doc/topics/targeting/compound.rst
  doc/topics/targeting/globbing.rst
  doc/topics/targeting/index.rst
  doc/topics/targeting/nodegroups.rst
  doc/topics/tutorials/http.rst
  doc/topics/tutorials/modules.rst
  doc/topics/tutorials/pillar.rst
  requirements/static/docs.in
  requirements/static/py3.5/docs.txt
  requirements/static/py3.6/docs.txt
  requirements/static/py3.7/docs.txt
Labels: Documentation

#56453 Docs: Add link from saltutil.refresh_pillar to pillar topic.
  salt/modules/saltutil.py
Labels: Documentation

#56340 Update virtualenv_mod.py
  salt/states/virtualenv_mod.py
Labels: Documentation

#56663 Backport #53480 to master branch
  salt/states/archive.py
Labels: master-port

#56717 Fix broken link regarding the 1024 character limit for YAML keys
  doc/topics/troubleshooting/yaml_idiosyncrasies.rst
Labels: Documentation

#56662 Port #49066 to master branch
  doc/ref/returners/all/index.rst
  doc/ref/returners/all/salt.returners.appoptics_return.rst
  salt/returners/appoptics_return.py
  tests/integration/returners/test_appoptics_return.py
Labels: master-port

#55140 Split monit status fields on monit version
  salt/modules/monit.py
Labels: Needs Testcase

#54976 master-port 49201
  salt/states/file.py
  tests/unit/states/test_file.py
Labels: master-port

#54541 [master] Porting #49624 to master
  salt/modules/nilrt_ip.py
  tests/unit/modules/test_nilrt_ip.py
Labels: master-port

#53992 cmdmod: fix runas and group in run_chroot
  salt/modules/cmdmod.py
  tests/unit/modules/test_cmdmod.py
Labels: Merge Ready

#53404 Bugfix: Handle multibyte characters spanning blocks of received data (2018.3)
  salt/utils/vt.py
  tests/unit/utils/test_vt.py
Labels: Reviewers Assigned

#53326 core.py: ignore wrong product_name files
  salt/grains/core.py
  tests/unit/grains/test_core.py
Labels: Reviewers Assigned

#52935 Rewrite x509.certificate_managed to be easier to use
  salt/states/x509.py
  tests/integration/files/file/base/x509/cert_signing.sls
  tests/integration/files/file/base/x509/self_signed.sls
  tests/integration/files/file/base/x509/self_signed_different_properties.sls
  tests/integration/files/file/base/x509/self_signed_expiry.sls
  tests/integration/states/test_x509.py
Labels: Reviewers Assigned

#55862 Write docs for SEP 10 - PR Merge Requirements
  doc/topics/development/pull_requests.rst
Labels: Documentation

#56044 shadow.set_password: handle case where user has no shadow entry
  salt/modules/linux_shadow.py
  tests/unit/modules/test_linux_shadow.py
Labels: Execution Module

#56784 Port #53324 to master
  salt/states/slack.py
Labels: Documentation, master-port

#56780 Port #53571 into master
  salt/modules/pillar.py
Labels: Documentation, master-port

#56756 Fix a typo in the intro_scale tutorial
  doc/topics/tutorials/intro_scale.rst
Labels: Documentation, Merge Ready

#56781 Port #53481 to master
  doc/topics/troubleshooting/master.rst
Labels: Documentation, master-port

#56762 Fix master roots master
  conf/master
  doc/ref/configuration/master.rst
Labels: Documentation

#56760 Port #49216 to master
  tests/filename_map.yml
Labels: master-port

#56789 Port #52763 to master
  salt/pillar/__init__.py
  salt/utils/cache.py
Labels: master-port

#56791 Port #52546 to master
  salt/utils/master.py
Labels: master-port

#56790 Port #52560 to master
  doc/topics/development/modules/index.rst
  doc/topics/development/modules/ssh_wrapper.rst
Labels: Documentation

#56778 Port #53628 into master
  salt/utils/job.py
Labels: master-port

#56802 Port #49097 to master
  salt/pillar/ec2_pillar.py
Labels: master-port

#56786 Port #52854 to master
  doc/topics/event/events.rst
Labels: Documentation, master-port

#56793 [master] Port #50704 to master
  salt/client/__init__.py
  tests/integration/client/test_standard.py
Labels: master-port

#56766 Port #50779 to master
  tests/integration/cli/test_grains.py
Labels: master-port

#56768 Port #50410 to master
  salt/modules/drbd.py
  tests/unit/modules/test_drbd.py
Labels: master-port

#56767 Port #50230 to master
  tests/filename_map.yml
Labels: master-port

#56770 Port #50627 to master
  salt/states/file.py
  tests/integration/states/test_file.py
  tests/unit/states/test_file.py
Labels: master-port

#56777 Port #54018 into master
  salt/payload.py
  tests/unit/test_payload.py
Labels: master-port

#56775 Port #54016 to master
  tests/integration/modules/test_beacons.py
Labels: master-port

#56759 Port #49146 to master
  salt/modules/pf.py
  tests/unit/modules/test_pf.py
Labels: master-port

#56801 Port #49094 to master
  salt/templates/rh_ip/rh7_eth.jinja
Labels: master-port

#56794 Port #52324 to master
  salt/modules/glusterfs.py
Labels: master-port

#56799 [master] Port #51670 to master
  salt/modules/file.py
  tests/unit/modules/test_file.py
Labels: master-port

#56753 Backport #51095
  CHANGELOG.md
  salt/modules/win_timezone.py
  tests/unit/modules/test_win_timezone.py
Labels: master-port

#56769 Port #50516 to master
  salt/modules/opkg.py
  tests/unit/modules/test_opkg.py
Labels: master-port

#56761 Port #49396 to master
  salt/modules/slsutil.py
  tests/unit/modules/test_slsutil.py
Labels: master-port

#56763 Port #50102 to master
  tests/integration/modules/test_vault.py
  tests/support/case.py
Labels: master-port

#56712 Port #50135 to master
  salt/cloud/clouds/saltify.py
  tests/unit/cloud/clouds/test_saltify.py
Labels: master-port

#56697 Port #51253 to master
  salt/states/boto_lambda.py
Labels: master-port

#56695 Port #51923, #50591, #50661, #50694 to master
  salt/modules/boto3_sns.py
  salt/modules/boto_lambda.py
  salt/modules/boto_secgroup.py
  salt/states/boto3_sns.py
  salt/states/boto_lambda.py
Labels: master-port

#56694 Port #51470 to master
  salt/cloud/__init__.py
  salt/utils/azurearm.py
Labels: master-port

#56765 Port #50152 to master
  doc/topics/jinja/index.rst
  salt/utils/jinja.py
  tests/unit/utils/test_jinja.py
Labels: master-port

#56731 Backport #53994
  CHANGELOG.md
  tests/unit/daemons/test_masterapi.py
Labels: master-port

#56751 Backport 49981
  CHANGELOG.md
  salt/modules/win_task.py
  tests/integration/modules/test_win_task.py
  tests/unit/modules/test_win_task.py
Labels: master-port

#56711 Port #50177 to master
  salt/cloud/clouds/vmware.py
  tests/unit/cloud/clouds/test_vmware.py
Labels: master-port

#56707 Port #51002 to master
  salt/cloud/clouds/proxmox.py
  tests/unit/cloud/clouds/test_proxmox.py
Labels: master-port

#56705 Port #51013 to master
  salt/cloud/clouds/proxmox.py
Labels: master-port

#56795 Port #48990 to master
  salt/modules/nilrt_ip.py
  tests/integration/modules/test_nilrt_ip.py
Labels: Has Testcase, master-port

#56681 Implicitly ignore epoch when no epoch in desired version, and ignore_epoch not passed
  salt/modules/yumpkg.py
  salt/states/pkg.py
  tests/integration/states/test_pkg.py
Labels: Merge Ready

#52699 btrfs: Add properties state
  doc/ref/states/all/index.rst
  doc/ref/states/all/salt.states.btrfs.rst
  salt/states/btrfs.py
  tests/unit/states/test_btrfs.py
Labels: Reviewers Assigned

#53100 salt.modules.network: Add functions to get minion's networks
  salt/modules/network.py
  salt/utils/network.py
  tests/unit/modules/test_network.py
  tests/unit/utils/test_network.py
Labels: Reviewers Assigned, Sodium

#54468 Lazily gather the lists of available sls data from the master
  salt/state.py
  tests/unit/test_state.py
Labels: Awesome

#56270 Force bytestrings to string in tomcat module
  salt/modules/tomcat.py
  tests/unit/modules/test_tomcat.py
Labels: Has Testcase

#55814 Add virt.*defined states
  salt/modules/virt.py
  salt/states/virt.py
  tests/unit/modules/test_virt.py
  tests/unit/states/test_virt.py
Labels: Merge Ready

#56838 Port #52138 to master
  salt/modules/mdadm_raid.py
Labels: Has Testcase, master-port

#56835 Port #53537 to master
  salt/states/pkgrepo.py
  tests/unit/states/test_pkgrepo.py
Labels: master-port

#56832 Port #53517 to master
  salt/utils/job.py
  tests/unit/utils/test_job.py
Labels: master-port

#56280 Allow skipping test cases that need Internet access
  tests/support/helpers.py
  tests/unit/modules/test_zcbuildout.py
  tests/unit/states/test_pip_state.py
  tests/unit/states/test_zcbuildout.py
  tests/unit/utils/test_dns.py
  tests/unit/utils/test_jinja.py
Labels: Sodium

#56408 Uses correct zero value for lgpo LockoutDuration
  salt/modules/win_lgpo.py
  tests/integration/modules/test_win_lgpo.py
Labels: Sodium

#56856 [master] Port #50053 to master
  salt/runners/reactor.py
  salt/utils/reactor.py
  tests/integration/__init__.py
  tests/integration/files/reactor-test.sls
  tests/integration/reactor/test_reactor.py
Labels: master-port

#56842 Port #48971 to master
  salt/modules/nilrt_ip.py
  tests/integration/modules/test_nilrt_ip.py
Labels: master-port

#56837 Port #49492 to master
  salt/grains/core.py
  tests/unit/grains/test_core.py
Labels: Has Testcase, master-port

#56804 Port #53381 to master
  salt/modules/systemd_service.py
  tests/unit/modules/test_systemd_service.py
Labels: master-port

#56827 [master] Port #50139 to master
  tests/integration/__init__.py
Labels: master-port

#56829 Port #47960 to master
  COPYING
  LICENSE
  README.rst
  salt/ext/__init__.py
Labels: master-port

#56834 Port #48907 to master
  salt/utils/network.py
  tests/unit/utils/test_network.py
Labels: master-port

#56846 Add a note about service.running (port #51511 to master)
  doc/ref/states/requisites.rst
Labels: Documentation, master-port

#56848 Backport #52342
  salt/modules/beacons.py
  salt/states/beacon.py
  tests/integration/modules/test_beacons.py
Labels: master-port

#56850 Port 51461 to master
  changelog/7424.added
  salt/modules/tls.py
  tests/integration/modules/test_tls.py
Labels: master-port

#56855 Backport #52673
  tests/integration/modules/test_system.py
Labels: master-port

#56730 Backport #52992
  CHANGELOG.md
  salt/modules/win_system.py
  tests/unit/modules/test_win_system.py
Labels: master-port

#55968 Fix several bugs in slack_webhook returner
  salt/returners/slack_webhook_return.py
  tests/unit/returners/test_slack_webhook_return.py
Labels: Sodium

#56439 Add docker logout
  salt/modules/dockermod.py
  tests/unit/modules/test_dockermod.py
Labels: Merge Ready

#56725 Correct firewalld.reload_rules docstring
  salt/modules/firewalld.py
Labels: Documentation, Merge Ready

#56782 Port changes from #48704
  salt/modules/useradd.py
  salt/states/user.py
  tests/integration/files/file/base/git_pillar/ssh/user/init.sls
  tests/integration/states/test_user.py
  tests/unit/modules/test_useradd.py
Labels: master-port

#56816 Port changes from #51007
  salt/modules/match.py
  tests/unit/modules/test_match.py
Labels: master-port

#56844 Port #53508 to master
  changelog/56844.fixed
  salt/utils/network.py
Labels: master-port

#56839 Port #48936 into master
  salt/grains/core.py
  tests/unit/grains/test_core.py
Labels: master-port

#56810 Backport #51769
  salt/states/reg.py
  tests/unit/states/test_reg.py
Labels: master-port
