Repository saltstack/salt, pull requests merged in 2020-06, with the labels that each got.

#57492 [RC1 Sodium] Update to the latest salt-bootstrap release, v2020.05.28
  salt/cloud/deploy/bootstrap-salt.sh
Labels: Sodium

#57533 [RC1 Sodium] update gpg key signature
  doc/security/index.rst
Labels: Documentation, Merge Ready, Sodium

#57548 [BUG] [RC1 Sodium] update pyzmq requirement
  requirements/zeromq.txt
Labels: Bug, Merge Ready, Severity: Medium, Sodium

#57539 [RC1 Sodium] Uncap msgpack version
  requirements/base.txt
Labels: Merge Ready, Sodium

#57507 [RC1 Sodium] sphinx 3.0.2 has bugs
  requirements/static/docs.in
  requirements/static/py3.8/docs.txt
  requirements/static/py3.9/docs.txt
Labels: Documentation, Merge Ready, Sodium

#57553 Fix dupes and name in changelog
  CHANGELOG.md
Labels: Sodium

#57556 Corrected example code documentation for run_commands (had send_commands)
  salt/modules/arista_pyeapi.py
Labels: Bug, Documentation, Merge Ready, Sodium, doc-correction

#57475 [RC1 Sodium] Move .ci folder
  .ci/docs
  .ci/kitchen-amazon2-py3
  .ci/kitchen-amazon2-py3-pytest
  .ci/kitchen-archlts-py3
  .ci/kitchen-archlts-py3-pytest
  .ci/kitchen-centos7-py3
  .ci/kitchen-centos7-py3-cloud
  .ci/kitchen-centos7-py3-cloud-pytest
  .ci/kitchen-centos7-py3-m2crypto
  .ci/kitchen-centos7-py3-m2crypto-pytest
  .ci/kitchen-centos7-py3-proxy
  .ci/kitchen-centos7-py3-pycryptodome
  .ci/kitchen-centos7-py3-pycryptodome-pytest
  .ci/kitchen-centos7-py3-pytest
  .ci/kitchen-centos7-py3-tcp
  .ci/kitchen-centos7-py3-tcp-pytest
  .ci/kitchen-centos8-py3
  .ci/kitchen-centos8-py3-pytest
  .ci/kitchen-debian10-py3
  .ci/kitchen-debian10-py3-pytest
  .ci/kitchen-debian9-py3
  .ci/kitchen-debian9-py3-pytest
  .ci/kitchen-fedora31-py3
  .ci/kitchen-fedora31-py3-pytest
  .ci/kitchen-fedora32-py3
  .ci/kitchen-fedora32-py3-pytest
  .ci/kitchen-macosxhighsierra-py3
  .ci/kitchen-macosxhighsierra-py3-pytest
  .ci/kitchen-macosxmojave-py3
  .ci/kitchen-macosxmojave-py3-pytest
  .ci/kitchen-opensuse15-py3
  .ci/kitchen-opensuse15-py3-pytest
  .ci/kitchen-ubuntu1604-py3
  .ci/kitchen-ubuntu1604-py3-m2crypto
  .ci/kitchen-ubuntu1604-py3-m2crypto-pytest
  .ci/kitchen-ubuntu1604-py3-proxy
  .ci/kitchen-ubuntu1604-py3-pycryptodome
  .ci/kitchen-ubuntu1604-py3-pycryptodome-pytest
  .ci/kitchen-ubuntu1604-py3-pytest
  .ci/kitchen-ubuntu1604-py3-tcp
  .ci/kitchen-ubuntu1604-py3-tcp-pytest
  .ci/kitchen-ubuntu1804-py3
  .ci/kitchen-ubuntu1804-py3-pytest
  .ci/kitchen-ubuntu2004-py3
  .ci/kitchen-ubuntu2004-py3-pytest
  .ci/kitchen-windows2016-py3
  .ci/kitchen-windows2016-py3-pytest
  .ci/kitchen-windows2019-py3
  .ci/kitchen-windows2019-py3-pytest
  .ci/lint
  .ci/pre-commit
Labels: Merge Ready, Sodium

#57483 [RC1 Sodium] Add changelog keep file
  changelog/.keep
Labels: Sodium

#57572 fix pre-commit pr tests
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.5/freebsd.txt
  requirements/static/py3.5/linux.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.6/freebsd.txt
  requirements/static/py3.6/linux.txt
  requirements/static/py3.7/darwin.txt
  requirements/static/py3.7/freebsd.txt
  requirements/static/py3.7/linux.txt
  requirements/static/py3.8/darwin.txt
  requirements/static/py3.8/freebsd.txt
  requirements/static/py3.8/linux.txt
  requirements/static/py3.9/darwin.txt
  requirements/static/py3.9/freebsd.txt
  requirements/static/py3.9/linux.txt
Labels: Sodium

#57575 don't overwrite rst files with autodoc
  doc/conf.py
  doc/ref/modules/all/salt.modules.nxos_upgrade.rst
  doc/ref/states/all/salt.states.nxos_upgrade.rst
Labels: Documentation, Sodium

#57549 Change pygit2 to 1.1.1 as required by FreeBSD-12.1 RELEASE
  requirements/static/freebsd.in
  requirements/static/py3.5/freebsd.txt
  requirements/static/py3.6/freebsd.txt
  requirements/static/py3.7/freebsd.txt
  requirements/static/py3.8/freebsd.txt
  requirements/static/py3.9/freebsd.txt
Labels: Sodium

#57588 Fix macOS static requirements
  .pre-commit-config.yaml
  pkg/osx/req.txt
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.7/darwin.txt
  requirements/static/py3.8/darwin.txt
  requirements/static/py3.9/darwin.txt
Labels: Sodium

#57590 Changelog typo fixes
  CHANGELOG.md
Labels: Sodium

#57578 Add folder initialization $PLUGINSDIR
  pkg/windows/installer/Salt-Minion-Setup.nsi
Labels: Merge Ready, Sodium

#57595 Add missing ChangeLog entries
  CHANGELOG.md
Labels: Sodium

#57604 Add missing changelog entries
  CHANGELOG.md
Labels: Sodium
