Repository saltstack/salt, pull requests merged in 2020-10, with the labels that each got.

#53954 Fix line number
  doc/topics/tutorials/starting_states.rst
Labels: Documentation, Magnesium

#57642 Remove comment referencing _supported_dists from salt/grains/core.py
  salt/grains/core.py
Labels: Documentation, Magnesium

#56054 SMTP documentation update
  salt/modules/smtp.py
Labels: Documentation, Magnesium

#58599 clarifying the pillar_opts is configured on both master and minion.
  doc/topics/tutorials/pillar.rst
Labels: Documentation, Magnesium

#57589 Adding some missing entries to the changelog.
  CHANGELOG.md
Labels: Documentation, Magnesium, has-failing-test

#57651 Six thousand, not six million
  conf/minion
Labels: Documentation, Magnesium

#58140 Remove security advisor now that we depend on PyCryptodomex
  README.rst
Labels: Documentation, Magnesium, has-failing-test

#58441 Fix when multiple sources include HTTP and are missing
  changelog/58441.fixed
  salt/modules/file.py
  tests/integration/modules/test_file.py
  tests/unit/modules/test_file.py
Labels: Magnesium, ZD

#56906 iptables: document 'chain' kwarg for 'flush' state
  salt/states/iptables.py
Labels: Documentation, Magnesium

#58151 Corrected a section title
  doc/ref/states/requisites.rst
Labels: Documentation, Magnesium, has-failing-test

#58307 [master] Ensure proxy_config reads proxy specific configuration
  changelog/58307.fixed
  tests/unit/test_proxy_minion.py
Labels: Magnesium

#58479 modules/nilrt_ip.py: Make DNS optional in set_static_all
  salt/modules/nilrt_ip.py
  tests/unit/modules/test_nilrt_ip.py
Labels: Magnesium

#58617 update pycryptodomex
  requirements/crypto.txt
  requirements/static/ci/py3.5/darwin.txt
  requirements/static/ci/py3.5/freebsd.txt
  requirements/static/ci/py3.5/linux.txt
  requirements/static/ci/py3.5/windows.txt
  requirements/static/ci/py3.6/darwin.txt
  requirements/static/ci/py3.6/freebsd.txt
  requirements/static/ci/py3.6/linux.txt
  requirements/static/ci/py3.6/windows.txt
  requirements/static/ci/py3.7/darwin.txt
  requirements/static/ci/py3.7/freebsd.txt
  requirements/static/ci/py3.7/linux.txt
  requirements/static/ci/py3.7/windows.txt
  requirements/static/ci/py3.8/darwin.txt
  requirements/static/ci/py3.8/freebsd.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.9/darwin.txt
  requirements/static/ci/py3.9/freebsd.txt
  requirements/static/ci/py3.9/linux.txt
  requirements/static/pkg/py3.5/darwin.txt
  requirements/static/pkg/py3.5/freebsd.txt
  requirements/static/pkg/py3.5/linux.txt
  requirements/static/pkg/py3.5/windows.txt
  requirements/static/pkg/py3.6/darwin.txt
  requirements/static/pkg/py3.6/freebsd.txt
  requirements/static/pkg/py3.6/linux.txt
  requirements/static/pkg/py3.6/windows.txt
  requirements/static/pkg/py3.7/darwin.txt
  requirements/static/pkg/py3.7/freebsd.txt
  requirements/static/pkg/py3.7/linux.txt
  requirements/static/pkg/py3.7/windows.txt
  requirements/static/pkg/py3.8/darwin.txt
  requirements/static/pkg/py3.8/freebsd.txt
  requirements/static/pkg/py3.8/linux.txt
  requirements/static/pkg/py3.9/darwin.txt
  requirements/static/pkg/py3.9/freebsd.txt
  requirements/static/pkg/py3.9/linux.txt
  salt/modules/cmdmod.py
Labels: Magnesium, ZD

#57669 State mount.fstab_present respects mount parameter
  salt/modules/disk.py
  salt/modules/mount.py
  salt/states/mount.py
  tests/unit/states/test_mount.py
Labels: Bug, Magnesium, Severity: High

#57912 debian_service: remove support for old, EOL debian releases
  salt/modules/debian_service.py
  tests/unit/modules/test_debian_service.py
Labels: Bug, Magnesium, Severity: High

#58034 #58033 `file.read` return binary data in binary mode
  changelog/58033.md
  salt/modules/file.py
  tests/integration/modules/test_file.py
Labels: Bug, Confirmed, Magnesium, Severity: High

#56689 filter_by supports list fix
  salt/utils/data.py
  tests/unit/utils/test_data.py
Labels: Magnesium

#57764 Support testing against system installed version
  tests/support/paths.py
  tests/support/runtests.py
  tests/unit/modules/test_baredoc.py
  tests/unit/test_module_names.py
  tests/unit/test_virtualname.py
  tests/unit/utils/test_thin.py
  tests/unit/utils/test_versions.py
Labels: Magnesium

#57471 Update win_task.py
  salt/modules/win_task.py
Labels: Documentation, Magnesium

#57566 Ignore ValueError when loading pickled s3 cache
  salt/fileserver/s3fs.py
  tests/unit/fileserver/test_s3fs.py
Labels: Bug, Help Wanted, Magnesium, Needs Testcase, Severity: Medium, ZD

#57759 Fix for zipped custom modules
  changelog/57674.fixed
  salt/loader.py
  tests/unit/test_loader.py
Labels: Has Testcase, Magnesium, ZD

#58626 Fix pre-commit pip-tools-compile regexes
  .pre-commit-config.yaml
Labels: Magnesium

#58656 Disable CI concurrency
  cicd/jenkins/kitchen-amazon2-py3-pytest
  cicd/jenkins/kitchen-archlts-py3-pytest
  cicd/jenkins/kitchen-centos7-py3-m2crypto-pytest
  cicd/jenkins/kitchen-centos7-py3-pycryptodome-pytest
  cicd/jenkins/kitchen-centos7-py3-pytest
  cicd/jenkins/kitchen-centos7-py3-tcp-pytest
  cicd/jenkins/kitchen-centos8-py3-pytest
  cicd/jenkins/kitchen-debian10-py3-pytest
  cicd/jenkins/kitchen-debian9-py3-pytest
  cicd/jenkins/kitchen-fedora31-py3-pytest
  cicd/jenkins/kitchen-fedora32-py3-pytest
  cicd/jenkins/kitchen-freebsd121-py3-pytest
  cicd/jenkins/kitchen-macosxcatalina-py3-pytest
  cicd/jenkins/kitchen-macosxhighsierra-py3-pytest
  cicd/jenkins/kitchen-macosxmojave-py3-pytest
  cicd/jenkins/kitchen-opensuse15-py3-pytest
  cicd/jenkins/kitchen-ubuntu1604-py3-m2crypto-pytest
  cicd/jenkins/kitchen-ubuntu1604-py3-pycryptodome-pytest
  cicd/jenkins/kitchen-ubuntu1604-py3-pytest
  cicd/jenkins/kitchen-ubuntu1604-py3-tcp-pytest
  cicd/jenkins/kitchen-ubuntu1804-py3-pytest
  cicd/jenkins/kitchen-ubuntu2004-py3-pytest
  cicd/jenkins/kitchen-windows2016-py3-pytest
  cicd/jenkins/kitchen-windows2019-py3-pytest
Labels: Magnesium

#58630 Namespaced loader cleanup
  salt/loader.py
  tests/unit/test_loader.py
Labels: Magnesium

#58657 Switch to the remove-import-headers pre-commit hook
  .pre-commit-config.yaml
  tasks/__init__.py
  tasks/imports.py
Labels: Magnesium

#57738 Fix link to Proxmox website
  doc/topics/cloud/proxmox.rst
Labels: Documentation, Magnesium

#57996 fix typo in CloudTest#setUp docstring
  tests/integration/cloud/helpers/cloud_test_base.py
Labels: Documentation, Magnesium

#58422 Revert "Make def private"
  salt/cloud/clouds/ec2.py
Labels: Magnesium

#58153 [Documentation] IRC logs are no longer available.
  doc/topics/index.rst
Labels: Documentation, Magnesium

#57072 Port #50553 to master
  rfcs/sls-alternative-syntax.md
Labels: Documentation, has-failing-test, master-port

#58076 [merge jam] #49503 - fix typo in kernelpkg example
  salt/states/kernelpkg.py
Labels: Documentation, has-failing-test, master-port

#58671 [PyTest Migration] PyTest now uses argparse.
  tests/conftest.py
Labels: Magnesium

#58238 Cleanup calculation of template sls/tpl context
  changelog/56410.fixed
  changelog/58249.fixed
  changelog/58250.fixed
  changelog/58652.added
  doc/ref/states/vars.rst
  salt/config/__init__.py
  salt/features.py
  salt/utils/parsers.py
  salt/utils/templates.py
  tests/integration/modules/test_jinja.py
  tests/unit/test_config.py
  tests/unit/utils/test_templates.py
Labels: Bug, Magnesium, Severity: Medium

#57699 Do not fallback to 127.0.0.1 for un-resolvable masters in failover mode
  salt/minion.py
  tests/unit/test_minion.py
Labels: Bug, Magnesium, ZD, has-failing-test

#58660 Fix/enable boto tests
  tests/unit/modules/test_boto_cognitoidentity.py
  tests/unit/modules/test_boto_elasticsearch_domain.py
  tests/unit/modules/test_boto_elb.py
  tests/unit/modules/test_boto_secgroup.py
  tests/unit/modules/test_boto_vpc.py
Labels: Magnesium

#58066 Update url link in documentation in vault.py
  salt/modules/vault.py
Labels: Documentation, Magnesium

#58283 fix msgpack max_buffer_size being to low in ver >= 0.6 and < 1.0
  salt/utils/msgpack.py
  tests/unit/utils/test_msgpack.py
Labels: Magnesium, ZD

#58637 Update RC Install Instructions
  doc/topics/releases/releasecandidate.rst
Labels: Magnesium

#58685 Skip tests depending on the `ssl_webserver` fixture if on Py < 3.5.3
  tests/conftest.py
Labels: Magnesium

#58701 move_dep_from_module_run
  salt/states/module.py
Labels: Deprecation

#58728 Cleanup for contacts
  .github/config.yml
Labels: Magnesium

#58675 Start checking rst files at pre-commit level with `rstcheck`
  .pre-commit-config.yaml
  .rstcheck.cfg
  cicd/jenkins/pre-commit
  doc/ref/configuration/master.rst
  doc/ref/modules/index.rst
  doc/ref/runners/index.rst
  doc/ref/states/requisites.rst
  doc/ref/states/writing.rst
  doc/topics/cloud/aws.rst
  doc/topics/cloud/cloudstack.rst
  doc/topics/cloud/config.rst
  doc/topics/cloud/dimensiondata.rst
  doc/topics/cloud/gogrid.rst
  doc/topics/cloud/joyent.rst
  doc/topics/cloud/qs.rst
  doc/topics/cloud/scaleway.rst
  doc/topics/cloud/troubleshooting.rst
  doc/topics/cloud/vagrant.rst
  doc/topics/development/hacking.rst
  doc/topics/development/package_providers.rst
  doc/topics/development/tests/integration.rst
  doc/topics/development/tutorial.rst
  doc/topics/event/events.rst
  doc/topics/grains/index.rst
  doc/topics/installation/eos.rst
  doc/topics/installation/nxos.rst
  doc/topics/jinja/index.rst
  doc/topics/releases/2016.11.0.rst
  doc/topics/releases/2019.2.0.rst
  doc/topics/releases/3000.rst
  doc/topics/releases/releasecandidate.rst
  doc/topics/spm/dev.rst
  doc/topics/troubleshooting/index.rst
  doc/topics/troubleshooting/master.rst
  doc/topics/troubleshooting/minion.rst
  doc/topics/tutorials/cloud_controller.rst
  doc/topics/tutorials/gitfs.rst
  doc/topics/tutorials/http.rst
  doc/topics/tutorials/intro_scale.rst
  doc/topics/tutorials/libcloud.rst
  doc/topics/tutorials/packaging_modules.rst
  doc/topics/windows/windows-package-manager.rst
Labels: Magnesium

#58756 Add some more packaging requirements for Linux and FreeBSD
  requirements/static/ci/freebsd.in
  requirements/static/ci/linux.in
  requirements/static/ci/py3.5/freebsd.txt
  requirements/static/ci/py3.5/linux.txt
  requirements/static/ci/py3.6/freebsd.txt
  requirements/static/ci/py3.6/linux.txt
  requirements/static/ci/py3.7/freebsd.txt
  requirements/static/ci/py3.7/linux.txt
  requirements/static/ci/py3.8/freebsd.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.9/freebsd.txt
  requirements/static/ci/py3.9/linux.txt
  requirements/static/pkg/freebsd.in
  requirements/static/pkg/linux.in
  requirements/static/pkg/py3.5/freebsd.txt
  requirements/static/pkg/py3.5/linux.txt
  requirements/static/pkg/py3.6/freebsd.txt
  requirements/static/pkg/py3.6/linux.txt
  requirements/static/pkg/py3.7/freebsd.txt
  requirements/static/pkg/py3.7/linux.txt
  requirements/static/pkg/py3.8/freebsd.txt
  requirements/static/pkg/py3.8/linux.txt
  requirements/static/pkg/py3.9/freebsd.txt
  requirements/static/pkg/py3.9/linux.txt
Labels: Magnesium

#58761 Downgrade to pycparser==2.17 to un-break tiamat builds
  requirements/static/ci/py3.5/freebsd.txt
  requirements/static/ci/py3.5/linux.txt
  requirements/static/ci/py3.6/freebsd.txt
  requirements/static/ci/py3.6/linux.txt
  requirements/static/ci/py3.7/freebsd.txt
  requirements/static/ci/py3.7/linux.txt
  requirements/static/ci/py3.8/freebsd.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.9/freebsd.txt
  requirements/static/ci/py3.9/linux.txt
  requirements/static/pkg/py3.5/freebsd.txt
  requirements/static/pkg/py3.5/linux.txt
  requirements/static/pkg/py3.6/freebsd.txt
  requirements/static/pkg/py3.6/linux.txt
  requirements/static/pkg/py3.7/freebsd.txt
  requirements/static/pkg/py3.7/linux.txt
  requirements/static/pkg/py3.8/freebsd.txt
  requirements/static/pkg/py3.8/linux.txt
  requirements/static/pkg/py3.9/freebsd.txt
  requirements/static/pkg/py3.9/linux.txt
Labels: Magnesium

#58832 Add FreeBSD 12.2-RELEASE AMI
  cicd/jenkins/kitchen-freebsd122-py3
  cicd/jenkins/kitchen-freebsd122-py3-pytest
Labels: 3002.1

#58836 kitchen-ec2 >=3.8 is fixed
  Gemfile
Labels: 3002.1
