Repository saltstack/salt, pull requests merged in 2020-02, with the labels that each got.

#56047 Move the `salt-unity` implementation to `salt.scripts`
  salt/scripts.py
  scripts/salt-unity
Labels: Neon, Release Blocker

#56092 Add LGPO and Network PRs to changelogs
  CHANGELOG.md
  doc/topics/releases/3000.rst
Labels: Documentation, Neon

#56095 Provide security advisory for PyCrypto
  README.rst
  doc/topics/hardening.rst
  doc/topics/installation/index.rst
  doc/topics/releases/3000.rst
Labels: Documentation
