Repository saltstack/salt, pull requests merged in 2020-05, with the labels that each got.

#56979 Port #51444 to master
  rfcs/0006-py2-deprecation.md
Labels: Documentation, master-port

#56985 Port #51060 to master
  salt/states/pip_state.py
Labels: master-port

#56986 Port #51032 to master
  rfcs/0004-dunder-runner.md
Labels: Documentation, master-port

#57006 Port #50954 to master
  doc/topics/development/contributing.rst
Labels: Documentation, master-port

#57012 Fix failing ec2 Cloud tests
  tests/integration/cloud/helpers/cloud_test_base.py
Labels: Test Failure

#54931 merge nxos-specific work from develop into master.
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.nxos_upgrade.rst
  doc/ref/states/all/index.rst
  doc/ref/states/all/salt.states.nxos_upgrade.rst
  doc/topics/installation/index.rst
  doc/topics/installation/nxos.rst
  salt/exceptions.py
  salt/grains/nxos.py
  salt/modules/nxos.py
  salt/modules/nxos_upgrade.py
  salt/proxy/nxos.py
  salt/states/nxos.py
  salt/states/nxos_upgrade.py
  salt/utils/nxos.py
  salt/utils/pycrypto.py
  tests/unit/modules/nxos/__init__.py
  tests/unit/modules/nxos/nxos_config.py
  tests/unit/modules/nxos/nxos_grains.py
  tests/unit/modules/nxos/nxos_n36k.py
  tests/unit/modules/nxos/nxos_n3k.py
  tests/unit/modules/nxos/nxos_n5k.py
  tests/unit/modules/nxos/nxos_n7k.py
  tests/unit/modules/nxos/nxos_n93k.py
  tests/unit/modules/nxos/nxos_n93klxc.py
  tests/unit/modules/nxos/nxos_n95k.py
  tests/unit/modules/nxos/nxos_platform.py
  tests/unit/modules/nxos/nxos_show_cmd_output.py
  tests/unit/modules/nxos/nxos_show_run.py
  tests/unit/modules/test_nxos.py
  tests/unit/modules/test_nxos_upgrade.py
  tests/unit/proxy/test_nxos.py
  tests/unit/states/test_nxos.py
  tests/unit/test_module_names.py
  tests/unit/utils/test_pycrypto.py
Labels: Merge Ready, Sodium, master-port

#54930 Add method to remove circular references in data objects and add test
  salt/utils/data.py
  tests/unit/utils/test_data.py
Labels: Merge Ready, Sodium

#55402 Decide if the source should be actually skipped
  salt/modules/aptpkg.py
  tests/unit/modules/test_aptpkg.py
Labels: Merge Ready, master-port

#57068 Uninstall msi-installed salt
  pkg/windows/installer/Salt-Minion-Setup.nsi
Labels: Packaging, Sodium

#55824 Bug fixes in Junos-related components
  requirements/static/darwin.in
  requirements/static/linux.in
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.5/linux.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.6/linux.txt
  requirements/static/py3.7/darwin.txt
  requirements/static/py3.7/linux.txt
  requirements/static/py3.8/darwin.txt
  requirements/static/py3.8/linux.txt
  requirements/static/py3.9/darwin.txt
  requirements/static/py3.9/linux.txt
  salt/engines/junos_syslog.py
  salt/modules/junos.py
  salt/proxy/junos.py
  salt/states/junos.py
  tests/unit/modules/test_junos.py
Labels: Merge Ready, Sodium

#56703 Port #51096 to master
  salt/cloud/clouds/ec2.py
Labels: master-port

#57128 Port #49617 to master
  doc/ref/publisheracl.rst
  doc/topics/eauth/access_control.rst
  doc/topics/eauth/index.rst
Labels: Documentation, master-port

#56372 Fix for #41858
  salt/modules/x509.py
  tests/integration/files/conf/master
  tests/integration/files/file/base/issue-41858/check.sls
  tests/integration/files/file/base/issue-41858/gen_cert.sls
  tests/integration/files/file/base/x509_compound_match/check.sls
  tests/integration/files/file/base/x509_compound_match/gen_ca.sls
  tests/integration/states/test_x509.py
  tests/support/case.py
Labels: Merge Ready

#57132 Added syndic to log rotation
  pkg/salt-common.logrotate
Labels: Sodium

#56938 Port #51754 to master
  doc/topics/releases/2019.2.0.rst
Labels: master-port

#57024 Port #50930 to master
  salt/runners/virt.py
Labels: master-port

#57023 Port #50946 to master
  salt/auth/__init__.py
Labels: Merge Ready, master-port

#56981 Port #51134 to master
  salt/states/file.py
Labels: master-port

#57086 improve boot parameter documentation
  salt/modules/virt.py
  salt/states/virt.py
Labels: Documentation

#57156 Port #49612 to master
  salt/netapi/rest_cherrypy/app.py
Labels: Documentation, master-port

#57114 Add arpcheck to RH8 IP
  changelog/57047.fixed
  salt/templates/rh_ip/rh8_eth.jinja
Labels: Sodium

#57112 Fix a typo within salt/transport/tcp.py
  salt/transport/tcp.py
Labels: Documentation, Merge Ready

#57094 Port #50338 to master
  salt/modules/pkgin.py
Labels: master-port

#57093 Port #50353 to master
  rfcs/0003-api-unification.md
Labels: Documentation, Merge Ready, master-port

#57091 Port #50078 to master
  rfcs/0003-job-retry.md
Labels: Documentation, master-port

#57169 Put Py3 back
  pkg/windows/build.bat
  pkg/windows/build_env.ps1
  pkg/windows/build_pkg.bat
  pkg/windows/clean_env.bat
  pkg/windows/installer/Salt-Minion-Setup.nsi
  pkg/windows/modules/get-settings.psm1
Labels: Merge Ready, Sodium

#57062 Only inspect one frame in depends decorator
  salt/utils/decorators/__init__.py
Labels: Awesome

#57153 Port #49651 to master
  rfcs/0002-adding-minion-id-to-fileserver-calls.md
Labels: Documentation, master-port

#57177 Port #47767 to master
  doc/topics/cloud/vmware.rst
Labels: Documentation, master-port

#54078 Fixed salt key management with eauth
  salt/auth/__init__.py
  salt/key.py
  tests/integration/shell/test_key.py
  tests/support/case.py
  tests/support/helpers.py
Labels: Sodium

#57042 Port #50614 to master
  salt/modules/ini_manage.py
Labels: master-port

#57106 Port #54844 to master
  salt/states/git.py
  tests/integration/states/test_git.py
Labels: Has Testcase, master-port

#57075 Port #50510 to master
  salt/modules/swarm.py
Labels: Documentation, Merge Ready, master-port

#57052 Clarify custom module sync requirements
  changelog/55514.fixed
  doc/ref/modules/index.rst
Labels: Documentation, Merge Ready

#57045 Fix idempotency in reg with None REG_SZ
  salt/utils/win_reg.py
  tests/unit/states/test_reg.py
  tests/unit/utils/test_win_reg.py
Labels: Has Testcase, Merge Ready, Sodium

#57165 Port #49563 to master
  salt/cloud/clouds/proxmox.py
Labels: master-port

#56129 Fix spm http py3 install
  salt/spm/__init__.py
  salt/utils/http.py
  tests/integration/spm/test_install.py
  tests/unit/utils/test_http.py
Labels: Sodium

#56881 [WIP] Port #50168 to master
  salt/defaults/events.py
  salt/loader.py
  salt/minion.py
  salt/modules/saltutil.py
  tests/integration/modules/test_saltutil.py
Labels: master-port

#57151 Distro is now a hard dependency
  .pylintrc
  doc/conf.py
  pkg/osx/req.txt
  pkg/windows/req.txt
  requirements/base.txt
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.5/linux.txt
  requirements/static/py3.5/windows.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.6/linux.txt
  requirements/static/py3.6/windows.txt
  requirements/static/py3.7/darwin.txt
  requirements/static/py3.7/linux.txt
  requirements/static/py3.7/windows.txt
  requirements/static/py3.8/darwin.txt
  requirements/static/py3.8/linux.txt
  requirements/static/py3.9/darwin.txt
  requirements/static/py3.9/linux.txt
  salt/grains/core.py
  salt/utils/platform.py
  salt/utils/thin.py
  salt/version.py
  tests/unit/utils/test_thin.py
Labels: Merge Ready

#57321 Fix issue with venv_dir path on Windows
  tests/integration/states/test_pip_state.py
Labels: Sodium

#57350 Virt disks fixes
  salt/modules/virt.py
  tests/unit/modules/test_virt.py
Labels: Sodium

#56079 Allow bypassing requirements installattion.
  noxfile.py
Labels: Sodium

#55975 Fixed the skip_files_list_verify in archive.extracted state
  salt/states/archive.py
  tests/integration/states/test_archive.py
Labels: has-failing-test

#53345 kubeadm: add initial module for kubeadm
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.kubeadm.rst
  salt/modules/kubeadm.py
  tests/unit/modules/test_kubeadm.py
Labels: Reviewers Assigned

#54964 (Backport 50706) blkid: add search by token
  tests/unit/modules/test_disk.py
Labels: master-port

#56605 Port #53622 to master (runners.git_pillar: Also match the repo parameter against the repo name)
  salt/runners/git_pillar.py
  tests/unit/runners/test_git_pillar.py
Labels: master-port

#53447 xfs: do not fails if type is not present
  salt/modules/xfs.py
  tests/unit/modules/test_xfs.py
Labels: Reviewers Assigned

#57234 Port #51200 to master
  salt/auth/ldap.py
  salt/auth/pki.py
  salt/beacons/__init__.py
  salt/beacons/adb.py
  salt/beacons/log_beacon.py
  salt/beacons/napalm_beacon.py
  salt/beacons/status.py
  salt/beacons/twilio_txt_msg.py
  salt/utils/cloud.py
  salt/utils/dictdiffer.py
  salt/utils/dns.py
  salt/utils/etcd_util.py
  salt/utils/event.py
  salt/utils/extmods.py
  salt/utils/find.py
  salt/utils/github.py
  salt/utils/http.py
  salt/utils/kickstart.py
  salt/utils/master.py
  salt/utils/minions.py
  salt/utils/network.py
  salt/utils/nxos.py
  salt/utils/openstack/neutron.py
  salt/utils/oset.py
  salt/utils/parsers.py
  salt/utils/process.py
  salt/utils/pyobjects.py
  salt/utils/reclass.py
  salt/utils/saltclass.py
  salt/utils/sdb.py
  salt/utils/thin.py
  salt/utils/timeutil.py
  salt/utils/win_dacl.py
  salt/utils/win_lgpo_netsh.py
  salt/utils/xmlutil.py
Labels: master-port

#56243 Updated dict .keys() and .values() indexed calls for py3
  salt/beacons/cert_info.py
  salt/beacons/napalm_beacon.py
  salt/cli/batch.py
  salt/modules/acme.py
  salt/modules/bamboohr.py
  salt/modules/capirca_acl.py
  salt/modules/disk.py
  salt/modules/glance.py
  salt/modules/highstate_doc.py
  salt/modules/opkg.py
  salt/modules/postgres.py
  salt/modules/rabbitmq.py
  salt/modules/rpm_lowpkg.py
  salt/modules/win_lgpo.py
  salt/modules/zabbix.py
  salt/pillar/vmware_pillar.py
  salt/runners/virt.py
  salt/states/boto_dynamodb.py
  salt/states/dellchassis.py
  salt/states/mdadm_raid.py
  salt/states/mount.py
  salt/states/pyrax_queues.py
  salt/utils/dns.py
Labels: Merge Ready, Needs Testcase, Sodium

#57394 Move the coverage DB to artifacts/coverage in order for it to be archived by CI
  noxfile.py
Labels: Sodium

#57122 msgpack: support versions >= 1.0.0
  salt/utils/msgpack.py
  tests/unit/utils/test_msgpack.py
Labels: Merge Ready

#57287 doc: Fix document linking in requisites.rst (Port #52019 to master)
  doc/ref/states/requisites.rst
Labels: Documentation, Needs Testcase, master-port

#57291 Changed all references of python 3.6 to 3.7.
  doc/topics/installation/freebsd.rst
Labels: Documentation, Sodium

#55170 Fixes #37709
  salt/cloud/clouds/vmware.py
Labels: Needs Testcase, has-failing-test

#57389 Repair template_vars functionality and allow for dest keyword in rpc on Junos
  salt/modules/junos.py
Labels: Merge Ready, Sodium

#56620 [master] postfix.show_queue fixes
  salt/modules/postfix.py
  tests/unit/modules/test_postfix.py
Labels: Bug, Fixed Pending Verification, has-failing-test

#56404 Fix mismatch function argument between cassandra_cql and cassandra_cql_return
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.cassandra.rst
  doc/ref/modules/all/salt.modules.cassandra_mod.rst
  requirements/static/darwin.in
  requirements/static/linux.in
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.5/linux.txt
  requirements/static/py3.5/windows.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.6/linux.txt
  requirements/static/py3.6/windows.txt
  requirements/static/py3.7/darwin.txt
  requirements/static/py3.7/linux.txt
  requirements/static/py3.7/windows.txt
  requirements/static/py3.8/darwin.txt
  requirements/static/py3.8/linux.txt
  requirements/static/py3.9/darwin.txt
  requirements/static/py3.9/linux.txt
  requirements/static/windows.in
  salt/modules/cassandra_cql.py
  salt/modules/cassandra_mod.py
  tests/unit/modules/test_cassandra_cql.py
  tests/unit/modules/test_cassandra_mod.py
Labels: Merge Ready

#57355 Pycrypto gen hash rewrite
  requirements/static/linux.in
  requirements/static/py3.5/linux.txt
  requirements/static/py3.6/linux.txt
  requirements/static/py3.7/linux.txt
  requirements/static/py3.8/linux.txt
  requirements/static/py3.9/linux.txt
  salt/modules/nxos.py
  salt/utils/pycrypto.py
  tests/unit/utils/test_pycrypto.py
Labels: Sodium

#55798 Reenable the pkg states integration tests
  tests/integration/states/test_pkg.py
Labels: Merge Ready

#55421 Update net.py and bgp.py
  salt/runners/bgp.py
  salt/runners/net.py
  salt/utils/napalm.py
  tests/unit/runners/test_bgp.py
  tests/unit/runners/test_net.py
Labels: Sodium

#57370 Sodium deprecations
  changelog/57361.removed
  changelog/57362.removed
  changelog/57363.removed
  changelog/57366.removed
  changelog/57367.removed
  changelog/57368.removed
  doc/topics/releases/sodium.rst
  salt/modules/mac_brew_pkg.py
  salt/modules/napalm_network.py
  salt/modules/selinux.py
  salt/states/module.py
  salt/states/pkgrepo.py
  salt/transport/__init__.py
  salt/transport/zeromq.py
  salt/utils/cloud.py
  salt/utils/context.py
  salt/utils/locales.py
  salt/utils/minions.py
  salt/utils/smb.py
  tests/integration/utils/test_smb.py
  tests/unit/transport/test_zeromq.py
Labels: Sodium

#56203 pass timeout to 'cmd_subset' and 'cmd_batch', subset correctly
  salt/client/__init__.py
  salt/client/ssh/client.py
  salt/modules/saltutil.py
  tests/unit/modules/test_saltutil.py
  tests/unit/test_client.py
Labels: Merge Ready, Sodium

#56295 Fix 56287
  salt/modules/selinux.py
  tests/unit/modules/test_selinux.py
Labels: Has Testcase, Sodium, has-failing-test

#55491 Fix for Solaris virtual grain detection
  salt/grains/core.py
Labels: Bug, Needs Testcase, Sodium

#57273 Add legacy python deprecation FAQ
  doc/topics/development/faq-py2-deprecation.rst
  doc/topics/development/index.rst
Labels: Needs Testcase, Sodium

#57401 Add docs for the build.bat
  pkg/windows/build.bat
Labels: Documentation, Sodium

#57387 Update Python for OSX Builds
  pkg/osx/build_env.sh
  pkg/osx/build_sig.sh
  pkg/osx/shasums/Python-3.5.4.tar.xz.sha512
  pkg/osx/shasums/Python-3.7.4.tar.xz.sha512
  pkg/osx/shasums/libsodium-1.0.17.tar.gz.sha512
  pkg/osx/shasums/libsodium-1.0.18.tar.gz.sha512
  pkg/osx/shasums/openssl-1.0.2q.tar.gz.sha512
  pkg/osx/shasums/openssl-1.0.2u.tar.gz.sha512
  pkg/osx/shasums/zeromq-4.1.6.tar.gz.sha512
  pkg/osx/shasums/zeromq-4.1.7.tar.gz.sha512
Labels: Mac OS, Sodium

#56913 Port #51820 to master
  salt/states/test.py
Labels: Documentation, has-failing-test, master-port

#57385 Update RC Installation Instructions
  doc/topics/releases/releasecandidate.rst
Labels: Documentation, High Severity, Merge Ready, P1, Sodium

#57419 Change Sodium reference to 3001
  doc/ref/configuration/minion.rst
  doc/ref/states/requisites.rst
  doc/topics/cloud/windows.rst
  doc/topics/development/deprecations.rst
  doc/topics/jinja/index.rst
  doc/topics/releases/2019.2.0.rst
  doc/topics/releases/2019.2.4.rst
  doc/topics/releases/3000.2.rst
  doc/topics/ssh/index.rst
  doc/topics/ssh/roster.rst
  doc/topics/ssh/ssh_ext_alternatives.rst
  doc/topics/tutorials/gitfs.rst
  salt/config/__init__.py
  salt/minion.py
  salt/modules/baredoc.py
  salt/modules/cassandra_cql.py
  salt/modules/chocolatey.py
  salt/modules/file.py
  salt/modules/junos.py
  salt/modules/keystone.py
  salt/modules/kubernetesmod.py
  salt/modules/mac_brew_pkg.py
  salt/modules/mandrill.py
  salt/modules/network.py
  salt/modules/nxos.py
  salt/modules/pkg_resource.py
  salt/modules/ps.py
  salt/modules/salt_version.py
  salt/modules/state.py
  salt/modules/vault.py
  salt/modules/virt.py
  salt/modules/win_system.py
  salt/modules/win_wua.py
  salt/modules/x509.py
  salt/modules/yumpkg.py
  salt/modules/zfs.py
  salt/pillar/azureblob.py
  salt/pillar/git_pillar.py
  salt/runners/cache.py
  salt/runners/git_pillar.py
  salt/runners/manage.py
  salt/scripts.py
  salt/states/cmd.py
  salt/states/file.py
  salt/states/host.py
  salt/states/junos.py
  salt/states/module.py
  salt/states/pkg.py
  salt/states/user.py
  salt/states/virt.py
  salt/states/win_system.py
  salt/states/x509.py
  salt/utils/jid.py
  salt/utils/minions.py
  salt/utils/win_dotnet.py
  salt/utils/win_system.py
  salt/utils/win_update.py
Labels: Documentation, Sodium

#56027 Replace deprecated inspect.formatargspec
  salt/utils/args.py
  salt/utils/decorators/path.py
  salt/utils/decorators/signature.py
Labels: Core, Sodium

#56191 Fix mac softwareupdate for catalina
  salt/modules/mac_softwareupdate.py
  tests/unit/modules/test_mac_softwareupdate.py
Labels: Merge Ready, Sodium

#57116 fix unsubscribe
  salt/utils/event.py
  tests/unit/utils/test_event.py
Labels: Merge Ready, Sodium

#57437 Fix `warn_until` calls for the Sodium release
  salt/modules/keystone.py
  salt/modules/kubernetesmod.py
  salt/modules/mac_brew_pkg.py
  salt/modules/mandrill.py
  salt/modules/zfs.py
  salt/runners/manage.py
  salt/scripts.py
  salt/utils/jid.py
  salt/utils/minions.py
  tests/filename_map.yml
Labels: Sodium
