Repository saltstack/salt, pull requests merged in 2020-08, with the labels that each got.

#58118 fix gce cloudtest
  tests/integration/files/conf/cloud.profiles.d/gce.conf
Labels: Magnesium, Merge Ready, Salt-Cloud, has-failing-test

#58152 Fix broken slow and destructive tests on FreeBSD
  tests/integration/files/file/base/git_pillar/http/files/nginx.conf
  tests/integration/files/file/base/git_pillar/http/init.sls
  tests/integration/files/file/base/git_pillar/ssh/server/init.sls
  tests/integration/files/file/base/git_pillar/ssh/user/init.sls
  tests/integration/pillar/test_git_pillar.py
  tests/support/gitfs.py
Labels: Merge Ready

#58113 Add minion_id_lowercase details to minion conf
  conf/minion
Labels: Documentation, has-failing-test

#58117 fix linode cloudtest
  tests/integration/files/conf/cloud.profiles.d/linode.conf
Labels: Magnesium, Merge Ready, Salt-Cloud

#57895 Teach coverage a bit more about salt paths.
  .coveragerc
  noxfile.py
Labels: Magnesium, Merge Ready, Needs Testcase

#58161 Disable locale related test on FreeBSD
  tests/integration/modules/test_localemod.py
Labels: Merge Ready

#58119 Add idem exec and state modules
  changelog/57969.added
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.idem.rst
  doc/ref/states/all/index.rst
  doc/ref/states/all/salt.states.idem.rst
  salt/modules/idem.py
  salt/states/idem.py
  salt/utils/idem.py
  tests/integration/modules/test_idem.py
  tests/integration/states/test_idem.py
  tests/integration/utils/test_idem.py
Labels: Merge Ready

#56140 Link salt-ssh python requirement to install docs
  doc/topics/installation/index.rst
  doc/topics/ssh/index.rst
Labels: Documentation, Magnesium, Salt-SSH

#55857 add macos-catalina ci file
  cicd/jenkins/kitchen-macosxcatalina-py3
  cicd/jenkins/kitchen-macosxcatalina-py3-pytest
Labels: Mac OS, Magnesium

#57833 fix missing quotation mark in salt.states.cmd docs
  salt/states/cmd.py
Labels: Documentation, Merge Ready

#58189 Use a test class specific temp directory. Make sure to clean up after each test
  tests/integration/states/test_file.py
Labels: Merge Ready

#58236 Disable docker integration states tests on FreeBSD
  tests/integration/states/test_docker_container.py
  tests/integration/states/test_docker_network.py
Labels: Merge Ready

#58240 Fix broken cron slow test on FreeBSD
  tests/integration/states/test_cron.py
Labels: Merge Ready

#58166 Improve toml docs
  salt/serializers/toml.py
Labels: Documentation, Merge Ready

#56996 Changes for BUG opened: 56995
  salt/modules/zabbix.py
  tests/unit/modules/test_zabbix.py
Labels: Merge Ready

#57450 Remove buggy start parameter from virt.pool_running docstring
  changelog/57275.fixed
  salt/states/virt.py
Labels: Bug, Documentation, Magnesium, Merge Ready, Severity: Medium

#57489 Avoid HAS_DOCKER true if import messes with "salt.utils.docker"
  salt/modules/swarm.py
  tests/unit/modules/test_swarm.py
Labels: Magnesium, has-failing-test

#58275 Skip test on FreeBSD as there's limited inotify/watchdog support on it
  tests/unit/beacons/test_watchdog.py
Labels: Merge Ready

#58290 Fix broken slow test on FreeBSD
  tests/integration/states/test_virtualenv_mod.py
Labels: Merge Ready

#58292 Skip beacon test on FreeBSD
  tests/multimaster/beacons/test_inotify.py
Labels: Merge Ready

#58295 Fix broken slow test on FreeBSD
  tests/integration/states/test_user.py
Labels: Merge Ready

#58092 [merge jam] port 53224
  tests/unit/test_loader.py
Labels: master-port

#57861 Sync OpenBSD installation documentation with reality
  doc/topics/installation/openbsd.rst
Labels: Documentation, has-failing-test
