Repository saltstack/salt, pull requests merged in 2020-03, with the labels that each got.

#56333 add pylint ignore in django returner
  salt/returners/django_return.py
Labels: 3000.1, Merge Ready

#56285 Add missing colon.
  salt/runners/f5.py
Labels: 3000.1, Documentation, Merge Ready

#56082 Fix saltversioninfo grain for new version
  salt/version.py
  tests/unit/grains/test_core.py
  tests/unit/test_version.py
Labels: 3000.1, Merge Ready

#56143 Use encoding when caching pillar data
  salt/minion.py
  tests/integration/minion/test_minion_cache.py
  tests/unit/test_module_names.py
Labels: 3000.1, Merge Ready

#56172 Only change mine data if using new allow_tgt feature
  doc/topics/releases/3000.rst
  doc/topics/releases/sodium.rst
  salt/daemons/masterapi.py
  salt/modules/mine.py
  tests/integration/files/conf/minion
  tests/integration/files/conf/sub_minion
  tests/integration/modules/test_mine.py
  tests/support/case.py
  tests/unit/modules/test_mine.py
Labels: 3000.1, Merge Ready

#56094 Fix type error in TornadoImporter
  salt/__init__.py
  tests/unit/test_ext.py
Labels: 3000.1

#56174 [master] MySQL module fixes
  salt/modules/mysql.py
  salt/states/mysql_user.py
  tests/unit/modules/test_mysql.py
Labels: 3000.1, Merge Ready

#55888 Disable codecov PR comments and status checks
  .codecov.yml
Labels: 3000.1

#56345 Bump Windows Py3 builds timeout to 10 hours
  .ci/kitchen-windows2019-py3
Labels: 3000.1

#56149 [master] Fix to scheduler for use of when and splay
  salt/utils/schedule.py
  tests/integration/scheduler/test_eval.py
Labels: 3000.1, Merge Ready

#56197 Allows use of inline powershell for cmd.script args
  salt/modules/cmdmod.py
  tests/integration/files/file/base/issue-56195/test.ps1
  tests/integration/modules/test_cmdmod.py
Labels: 3000.1, Merge Ready

#55894 #55185 pdbedit module should check for version 4.8.x or newer
  salt/modules/pdbedit.py
  tests/unit/modules/test_pdbedit.py
Labels: 3000.1, Merge Ready

#55906 smartos.vm_present could not handle nics with vrrp_vrid property
  salt/states/smartos.py
  tests/unit/states/test_smartos.py
Labels: 3000.1, Merge Ready

#55937 Update windows build scripts
  pkg/windows/build_env_2.ps1
  pkg/windows/build_env_3.ps1
  pkg/windows/modules/start-process-and-test-exitcode.psm1
Labels: 3000.1, Merge Ready

#56128 Update CHANGELOG with release date and unreleased.
  CHANGELOG.md
Labels: 3000.1, Documentation

#56218 Changed StrictVersion checking of setuptools to LooseVersion
  setup.py
Labels: 3000.1

#56099 Fix Windows and macOS requirements handling in setup.py
  setup.py
Labels: 3000.1

#56336 Fix test_issue_2594_non_invalidated_cache test (update zope.interface)
  tests/integration/states/test_virtualenv_mod.py
Labels: 3000.1

#56321 Tidy up formatting in boto_secgroup docs
  salt/modules/boto_secgroup.py
Labels: 3000.1, Documentation, ZD

#56068 Update the bootstrap script to latest version, v2020.02.24
  salt/cloud/deploy/bootstrap-salt.sh
Labels: 3000.1

#56185 Fix regression in service states with reload argument
  salt/states/service.py
  tests/unit/states/test_service.py
Labels: 3000.1

#56341 Revert "Don't remove one directory level from slspath"
  doc/ref/states/vars.rst
  salt/utils/templates.py
  tests/unit/utils/test_templates.py
Labels: 3000.1

#56290 Ensures popping lgpo.secedit_data does not throw KeyError
  salt/modules/win_lgpo.py
  tests/integration/modules/test_win_lgpo.py
Labels: 3000.1, Merge Ready

#56339 Fix win_dns_client when used with scheduler
  salt/modules/win_dns_client.py
  tests/unit/modules/test_win_dns_client.py
Labels: 3000.1, Merge Ready

#56215 Fix for unless requisite when pip is not installed
  salt/states/pip_state.py
  tests/integration/files/file/base/issue-56131.sls
  tests/integration/files/file/base/issue-56131.zip
  tests/integration/modules/test_state.py
Labels: 3000.1

#56060 Fix regex string for **Del and **DelVals
  salt/modules/win_lgpo.py
  tests/unit/modules/test_win_lgpo.py
Labels: 3000.1, Merge Ready

#56337 Handle Adapter Type 53 and Undefined Types
  salt/utils/win_network.py
  tests/unit/utils/test_win_network.py
Labels: 3000.1, Merge Ready, Release Blocker

#56160 Fix issue with existing reg_dword entries
  salt/states/reg.py
  tests/unit/states/test_reg.py
  tests/unit/utils/test_win_reg.py
Labels: 3000.1, Merge Ready

#56358 Fix version instantiation when minor is an empty string
  salt/version.py
  tests/unit/test_version.py
Labels: 3000.1

#56272 Properly resolve the policy name
  salt/modules/win_lgpo.py
  salt/states/win_lgpo.py
  tests/unit/modules/test_win_lgpo.py
  tests/unit/states/test_win_lgpo.py
Labels: 3000.1, Merge Ready

#56310 Only process ADMX files when loading policies
  salt/modules/win_lgpo.py
  tests/unit/modules/test_win_lgpo.py
Labels: 3000.1, Merge Ready

#56023 add fix for bin_env
  salt/modules/pip.py
  tests/unit/modules/test_pip.py
Labels: 3000.1

#56327 keep cache_copied_files variable a list
  salt/modules/saltcheck.py
  tests/integration/files/file/base/validate-saltcheck/directory/init.sls
  tests/integration/files/file/base/validate-saltcheck/directory/level1.sls
  tests/integration/files/file/base/validate-saltcheck/init.sls
Labels: 3000.1

#56360 Use virtualenv 20.0.10 for macosx tests
  requirements/static/darwin.in
  requirements/static/py2.7/darwin.txt
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.7/darwin.txt
  salt/modules/virtualenv_mod.py
  tests/integration/states/test_pip_state.py
  tests/unit/modules/test_virtualenv_mod.py
  tests/unit/modules/test_zcbuildout.py
  tests/unit/states/test_zcbuildout.py
Labels: 3000.1

#56365 Update 3000.1 changelog
  CHANGELOG.md
Labels: 3000.1

#56373 update 3000.1 releasenotes
  doc/topics/releases/3000.1.rst
Labels: 3000.1

#55822 fix_Indefinitely_code
  salt/modules/win_task.py
  tests/unit/modules/test_win_task.py
Labels: 3000.1

#56387 update gpg key expiration date
  doc/security/index.rst
Labels: 3000.1, Merge Ready

#56378 Include _version.py if building wheel
  salt/version.py
  setup.py
  tests/integration/setup/__init__.py
  tests/integration/setup/test_bdist.py
  tests/runtests.py
  tests/unit/test_module_names.py
  tests/unit/test_version.py
Labels: 3000.1

#56376 Fix win deps
  pkg/windows/req.txt
Labels: 3000.1

#56398 Add additional PRs to 3000.1 changelog
  CHANGELOG.md
Labels: 3000.1, Documentation

#56403 update 3000.1 releasenotes
  doc/topics/releases/3000.1.rst
Labels: 3000.1, Documentation

#56418 Ensure version.py included before we install
  setup.py
  tests/integration/setup/test_egg.py
  tests/unit/test_module_names.py
Labels: 3000.1, Merge Ready

#56417 Update mac build scripts
  .pre-commit-config.yaml
  noxfile.py
  pkg/osx/build_env.sh
  pkg/osx/req.txt
  pkg/osx/req_ext.txt
  pkg/osx/req_pyobjc.txt
  requirements/static/py2.7/darwin.txt
  requirements/static/py2.7/windows.txt
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.5/windows.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.6/windows.txt
  requirements/static/py3.7/darwin.txt
  requirements/static/py3.7/windows.txt
  setup.py
Labels: 3000.1

#56423 Update changelog with package fixes
  CHANGELOG.md
Labels: 3000.1, Merge Ready

#56436 Fix #56433 - test_pip_installed_specific_env
  salt/states/pip_state.py
  tests/unit/states/test_pip_state.py
Labels: 3000.1

#56435 Update mac build scripts
  .gitignore
  .pre-commit-config.yaml
  noxfile.py
  pkg/osx/build_env.sh
  pkg/osx/req.txt
  pkg/osx/req_ext.txt
  pkg/osx/req_pyobjc.in
  pkg/osx/req_pyobjc.txt
  requirements/static/py2.7/darwin.txt
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.7/darwin.txt
  setup.py
Labels: 3000.1

#56446 3000.1 releasenotes updates
  doc/topics/releases/3000.1.rst
Labels: 3000.1, Documentation

#56455 Fix gitpython windows requirement
  pkg/windows/req.txt
  requirements/static/py2.7/windows.txt
  requirements/static/py3.5/windows.txt
  requirements/static/py3.6/windows.txt
  requirements/static/py3.7/windows.txt
Labels: 3000.1

#56464 3000.1 releasenotes
  doc/topics/releases/3000.1.rst
Labels: 3000.1, Documentation
