Repository saltstack/salt, pull requests merged in 2020-07, with the labels that each got.

#57611 Update links to Jinja docs
  doc/topics/jinja/index.rst
  salt/utils/jinja.py
  salt/utils/templates.py
Labels: 3001.1, Documentation, Merge Ready

#57679 Fix typo by adding device_write_iops in documentation.
  salt/modules/dockermod.py
  salt/states/docker_container.py
Labels: 3001.1, Bug, Documentation, Merge Ready, doc-correction

#57708 Dropped != Deprecated
  doc/topics/releases/3001.rst
Labels: 3001.1, Documentation, Merge Ready

#57892 Add documentation for double-indentation of multi-line strings
  doc/topics/troubleshooting/yaml_idiosyncrasies.rst
Labels: 3001.1, Documentation

#53518 Run boto_route53 test on Python 3.7+
  tests/unit/modules/test_boto_route53.py
Labels: 3001.1, Reviewers Assigned, python3

#56610 [master] Fix to thin.generate runner function
  salt/utils/thin.py
  tests/unit/utils/test_thin.py
Labels: 3001.1, Merge Ready

#56945 [#56901] network.managed state failed to bring down lo ip alias
  changelog/56901.fixed
  salt/states/network.py
  tests/unit/states/test_network.py
Labels: 3001.1, Merge Ready

#57737 remove duplicate line
  salt/roster/ansible.py
Labels: 3001.1, Merge Ready

#57605 [PyTest] Resolve paths when checking from filenames functionality.
  tests/conftest.py
Labels: 3001.1, Merge Ready

#57867 Add require docs to cloud maps
  doc/topics/cloud/map.rst
Labels: Documentation, Magnesium

#54740 Update dpkg_lowpkg to handle deb files that have spaces in `dpkg -I` output
  salt/modules/dpkg_lowpkg.py
  tests/unit/modules/test_dpkg_lowpkg.py
Labels: 3001.1, Merge Ready

#57613 Disk grains should not show virtual devices fix issue 57612
  changelog/57612.changed
  changelog/57612.fixed
  salt/grains/disks.py
  tests/unit/grains/test_disks.py
Labels: 3001.1, Merge Ready

#57798 Use atomic open to write cache
  changelog/57798.fixed
  salt/utils/cache.py
  tests/unit/renderers/test_gpg.py
Labels: 3001.1, Merge Ready

#57805 Fix tuned module on RHEL/CentOS 7.8
  salt/modules/tuned.py
  tests/unit/modules/test_tuned.py
Labels: 3001.1, Merge Ready

#57812 Partially revert "Port #53452 to master"
  salt/states/zpool.py
Labels: 3001.1, Merge Ready, Regression

#57816 Add winrepo_fallback option
  salt/config/__init__.py
  salt/runners/winrepo.py
Labels: 3001.1

#57869 Fix dict being changed during iteration
  changelog/57845.fixed
  salt/utils/kickstart.py
  tests/unit/utils/test_kickstart.py
Labels: 3001.1, Merge Ready

#57870 user.present: Restore "gid_from_name" and put on a deprecation path
  changelog/57843.fixed
  salt/states/user.py
  tests/integration/states/test_user.py
Labels: 3001.1, Merge Ready

#57896 Revert "Add ShiftLeft Scan to the pipeline"
  .gitlab-ci.yml
Labels: 3001.1

#57571 fix msg_pack
  pkg/osx/req.txt
  requirements/base.txt
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.5/freebsd.txt
  requirements/static/py3.5/linux.txt
  requirements/static/py3.5/windows.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.6/freebsd.txt
  requirements/static/py3.6/linux.txt
  requirements/static/py3.6/windows.txt
  requirements/static/py3.7/darwin.txt
  requirements/static/py3.7/freebsd.txt
  requirements/static/py3.7/linux.txt
  requirements/static/py3.7/windows.txt
  requirements/static/py3.8/darwin.txt
  requirements/static/py3.8/freebsd.txt
  requirements/static/py3.8/linux.txt
  requirements/static/py3.9/darwin.txt
  requirements/static/py3.9/freebsd.txt
  requirements/static/py3.9/linux.txt
  salt/serializers/msgpack.py
  salt/utils/msgpack.py
  tests/unit/utils/test_msgpack.py
Labels: 3001.1, Merge Ready

#57774 Update to the latest salt-bootstrap release, v2020.06.23
  salt/cloud/deploy/bootstrap-salt.sh
Labels: 3001.1

#57943 Update Changelog and Releasenotes for the 3001.1 release
  CHANGELOG.md
  changelog/32780.added
  changelog/56296.changed
  changelog/56556.fixed
  changelog/56901.fixed
  changelog/57285.fixed
  changelog/57493.fixed
  changelog/57529.changed
  changelog/57529.fixed
  changelog/57550.fixed
  changelog/57583.fixed
  changelog/57591.fixed
  changelog/57594.changed
  changelog/57612.changed
  changelog/57612.fixed
  changelog/57714.fixed
  changelog/57718.fixed
  changelog/57743.fixed
  changelog/57766.fixed
  changelog/57787.fixed
  changelog/57798.fixed
  changelog/57843.fixed
  changelog/57845.fixed
  doc/topics/releases/3001.1.rst
Labels: 3001.1

#57953 Changelog update
  CHANGELOG.md
  changelog/57941.fixed
  doc/topics/releases/3001.1.rst
Labels: 3001.1

#58018 Bump psutil to 5.6.7. The 5.6.6 version has a vulnerability.
  pkg/osx/req.txt
  pkg/windows/req.txt
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.5/freebsd.txt
  requirements/static/py3.5/linux.txt
  requirements/static/py3.5/windows.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.6/freebsd.txt
  requirements/static/py3.6/linux.txt
  requirements/static/py3.6/windows.txt
  requirements/static/py3.7/darwin.txt
  requirements/static/py3.7/freebsd.txt
  requirements/static/py3.7/linux.txt
  requirements/static/py3.7/windows.txt
  requirements/static/py3.8/darwin.txt
  requirements/static/py3.9/darwin.txt
Labels: 3001.1

#58019 Bump PyYAML version, 5.2.1 has a vulnerability
  pkg/osx/req.txt
  pkg/windows/req.txt
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.5/freebsd.txt
  requirements/static/py3.5/linux.txt
  requirements/static/py3.5/windows.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.6/freebsd.txt
  requirements/static/py3.6/linux.txt
  requirements/static/py3.6/windows.txt
  requirements/static/py3.7/darwin.txt
  requirements/static/py3.7/freebsd.txt
  requirements/static/py3.7/linux.txt
  requirements/static/py3.7/windows.txt
  requirements/static/py3.8/darwin.txt
  requirements/static/py3.8/freebsd.txt
  requirements/static/py3.8/linux.txt
  requirements/static/py3.9/darwin.txt
  requirements/static/py3.9/freebsd.txt
  requirements/static/py3.9/linux.txt
Labels: 3001.1

#58016 Fix static requirements
  requirements/static/py3.5/darwin.txt
  requirements/static/py3.6/darwin.txt
  requirements/static/py3.7/darwin.txt
Labels: 3001.1

#57955 Fix build scripts for Windows
  pkg/windows/build_pkg.bat
  pkg/windows/installer/Salt-Minion-Setup.nsi
Labels: 3001.1, Severity: Critical, Windows, has-failing-test

#56691 Port PR #48989 to master
  salt/modules/file.py
  salt/states/file.py
  tests/unit/modules/test_file.py
Labels: Merge Ready, master-port

#57936 Start upgrading codebase to Py3 for every changed file
  .ci/pre-commit
  .pre-commit-config.yaml
  .pylintrc
  cicd/jenkins/pre-commit
  salt/client/ssh/ssh_py_shim.py
Labels: Magnesium, Merge Ready

#52378 fix 46902: wait dpkg lock
  salt/modules/aptpkg.py
  tests/unit/modules/test_aptpkg.py
Labels: Reviewers Assigned

#57643 Skip 2 tests on FreeBSD.
  tests/unit/beacons/test_inotify.py
Labels: Merge Ready

#57623 Fix test_acme on FreeBSD
  tests/unit/modules/test_acme.py
Labels: Merge Ready

#57622 Skip blkid test on FreeBSD.
  tests/unit/modules/test_disk.py
Labels: Merge Ready

#57620 Skip tests for Linux ACLs on FreeBSD
  tests/integration/modules/test_linux_acl.py
Labels: Merge Ready

#57616 Fix failing test on FreeBSD
  tests/integration/states/test_archive.py
Labels: Merge Ready

#57615 Fix broken test and disable another (temporary) on FreeBSD
  tests/integration/states/test_file.py
Labels: Merge Ready

#57427 Cover pkgng module with new tests.
  tests/unit/modules/test_pkgng.py
Labels: Merge Ready

#57457 Add some new tests and fix 1 wrong test name.
  tests/unit/modules/test_pf.py
Labels: Merge Ready

#55980 Added support of GRANTS with per column privileges to MYSQL module
  salt/modules/mysql.py
  tests/unit/modules/test_mysql.py
Labels: Bug, Magnesium

#57684 test_git_pillar: passphrase-protected actually works on current Debian
  tests/integration/pillar/test_git_pillar.py
Labels: Merge Ready

#57598 Filterwarning overide previously defined filters ISSUE:57582
  salt/__init__.py
  salt/cli/daemons.py
  salt/matchers/__init__.py
Labels: Bug, Needs Testcase, Severity: Low

#57800 Update postgres_initdb state doc
  salt/states/postgres_initdb.py
Labels: Documentation, Merge Ready

#58046 [merge jam] port 50159
  salt/utils/network.py
  tests/unit/utils/test_network.py
Labels: master-port

#57724 virt: Update dependencies
  salt/modules/virt.py
Labels: Documentation, Magnesium, Merge Ready, doc-correction

#58090 Fix network unit.states.test_network.test_managed
  tests/unit/states/test_network.py
Labels: Magnesium, Severity: Low, Test Failure

#58060 [PR port] Port #49922 - Update cloud_controller.rst
  doc/topics/tutorials/cloud_controller.rst
Labels: Documentation, Help Wanted, master-port

#57663 Fixed issue #53887
  salt/modules/slsutil.py
Labels: Documentation, Magnesium

#57751 Fix parsing version of virtualenv
  salt/modules/virtualenv_mod.py
  tests/unit/modules/test_virtualenv_mod.py
Labels: Bug, Magnesium, Severity: Low

#57971 Documentation: Update incorrect example code in x509.py
  salt/states/x509.py
Labels: Documentation, Magnesium, Merge Ready

#57747 libvirt events engine: constant fixes
  changelog/57746.fixed
  salt/engines/libvirt_events.py
  tests/unit/engines/test_libvirt_events.py
Labels: Bug, Magnesium, Merge Ready, Severity: High, has-failing-test

#57498 virt.init: fix the name of volumes reused in disk-types pools
  changelog/57497.fixed
  salt/modules/virt.py
  tests/unit/modules/test_virt.py
Labels: Bug, Magnesium, Merge Ready, Severity: High, has-failing-test

#58068 [merge jam] port 52856
  doc/topics/releases/3000.rst
Labels: Documentation, Merge Ready, doc-correction, master-port

#58073 [merge jam] #49289 - Update reactor docs with small formatting fixes
  doc/topics/reactor/index.rst
Labels: Documentation, master-port
