Repository saltstack/salt, pull requests merged in 2020-12, with the labels that each got.

#59095 netapi/rest_cherrypy: fix doc for access/error log config
  salt/netapi/rest_cherrypy/app.py
Labels: Documentation

#58664 [DOCS]: Add topic describing Salt System Architecture for newbies
  doc/_incl/requisite_incl.rst
  doc/_static/salt-architecture.png
  doc/contents.rst
  doc/topics/index.rst
  doc/topics/salt_system_architecture.rst
Labels: Documentation

#59071 Fix error when running svn.latest in test mode
  changelog/59069.fixed
  salt/states/svn.py
  tests/unit/states/test_svn.py
Labels: Aluminium

#57692 Fix test_pkgrepo_01_managed and test_pkgrepo_02_absent for Ubuntu.
  tests/integration/files/file/base/pkgrepo/absent.sls
  tests/integration/files/file/base/pkgrepo/managed.sls
  tests/integration/states/test_pkgrepo.py
Labels: Aluminium

#59164 [DOCS] Sync state_aggregate option in minion and master config docs
  doc/ref/configuration/master.rst
  doc/ref/configuration/minion.rst
Labels: Documentation, doc-rst-update
