Repository saltstack/salt, pull requests merged in 2021-09, with the labels that each got.

#60811 templates: move the globals up to the Environment (Jinja2 3.0.0)
  changelog/55159.fixed
  salt/utils/jinja.py
  salt/utils/templates.py
  tests/unit/utils/test_jinja.py
Labels: Silicon

#60844 Rename zsh_completion.zsh to salt.zsh to be in sync with another shell completion namings
  pkg/salt.zsh
  pkg/suse/salt.spec
Labels: Silicon v3004.0

#60879 Delete no longer used state files, missed in #60869
  tests/integration/files/file/base/issue-1959-virtualenv-runas/init.sls
  tests/integration/files/file/base/issue-1959-virtualenv-runas/requirements.txt
Labels: Silicon v3004.0

#60804 update aws api so salt-cloud can create VMs with ipv6 addresses
  changelog/60804.fixed
  salt/cloud/clouds/ec2.py
  salt/utils/aws.py
  tests/integration/cloud/clouds/test_ec2.py
Labels: Salt-Cloud, Silicon v3004.0

#60542 Allow module_refresh to also refresh available beacons
  changelog/60541.added
  salt/minion.py
  tests/pytests/unit/test_minion.py
  tests/unit/test_minion.py
  tests/unit/utils/test_gitfs.py
Labels: Silicon v3004.0

#60922 Fix cloud requirements
  .pre-commit-config.yaml
  requirements/static/ci/py3.10/cloud.txt
  requirements/static/ci/py3.5/cloud.txt
  requirements/static/ci/py3.6/cloud.txt
  requirements/static/ci/py3.7/cloud.txt
  requirements/static/ci/py3.8/cloud.txt
  requirements/static/ci/py3.9/cloud.txt
Labels: Silicon v3004.0

#60901 add debian 11 arm64
  cicd/amis.yml
  cicd/jenkins/pr-debian-11-arm64-py3-pytest
Labels: Silicon v3004.0

#60918 Reverting PR 60456 for the MYSQL module
  changelog/59754.fixed
  salt/modules/mysql.py
  tests/pytests/integration/modules/test_mysql.py
  tests/pytests/unit/modules/test_mysql.py
Labels: Silicon v3004.0

#60904 Update salt-boostrap to 2021.09.17 release
  salt/cloud/deploy/bootstrap-salt.sh
Labels: Silicon v3004.0

#60940 Fix docs and cloud requirements
  .pre-commit-config.yaml
  noxfile.py
  requirements/static/ci/py3.10/cloud.txt
  requirements/static/ci/py3.5/cloud.txt
  requirements/static/ci/py3.6/cloud.txt
  requirements/static/ci/py3.7/cloud.txt
  requirements/static/ci/py3.8/cloud.txt
  requirements/static/ci/py3.9/cloud.txt
  requirements/static/ci/py3.9/docs.txt
  requirements/static/ci/py3.9/lint.txt
Labels: Silicon v3004.0

#60967 Redirect imports of ``salt.ext.six`` to ``six``
  changelog/60966.fixed
  salt/__init__.py
  tests/pytests/unit/test_ext_importers.py
  tests/unit/test_ext.py
Labels: Silicon v3004.0

#60972 [3004] Handle signals and properly exit, instead of raising exceptions.
  changelog/60391.fixed
  changelog/60963.fixed
  salt/scripts.py
  tests/pytests/integration/cli/test_salt.py
Labels: Silicon v3004.0
