Repository saltstack/salt, pull requests merged in 2021-04, with the labels that each got.

#59699 DOCS: Add example usage of rich rules to states.firewalld
  salt/states/firewalld.py
Labels: Documentation

#59886 update setup.py
  setup.py
Labels: Silicon

#59197 Note security concerns with grains for targeting
  salt/modules/vault.py
Labels: Documentation

#59563 Fix 20789 - Window's user creation and password policy requirements
  changelog/20789.fixed
  salt/modules/win_useradd.py
  salt/states/user.py
  tests/integration/modules/test_useradd.py
  tests/pytests/integration/modules/test_useradd.py
Labels: Aluminium, point-release

#59649 DOCS: Update link to Doug Hellman's blog entry on dictionary initalization performance in Salt Coding Style guide
  doc/topics/development/conventions/style.rst
Labels: Documentation

#59968 update releasenotes 3003
  doc/topics/releases/3003.rst
Labels: Documentation

#59967 fix 59946
  doc/topics/releases/3003.rst
Labels: Documentation, Release Notes

#59913 Drop ubuntu 16.04, add arch names to jenkinsfiles, add ubuntu 20.04 additional tests
  changelog/59913.removed
  cicd/jenkins/kitchen-centos7-py3-m2crypto-pytest
  cicd/jenkins/kitchen-centos7-py3-pycryptodome-pytest
  cicd/jenkins/kitchen-debian10-py3-pytest
  cicd/jenkins/kitchen-ubuntu1604-py3-m2crypto-pytest
  cicd/jenkins/pr-amazon-2-x86_64-py3-pytest
  cicd/jenkins/pr-arch-lts-x86_64-py3-pytest
  cicd/jenkins/pr-centos-7-x86_64-py3-cloud-pytest
  cicd/jenkins/pr-centos-7-x86_64-py3-m2crypto-pytest
  cicd/jenkins/pr-centos-7-x86_64-py3-pycryptodome-pytest
  cicd/jenkins/pr-centos-7-x86_64-py3-pytest
  cicd/jenkins/pr-centos-7-x86_64-py3-tcp-pytest
  cicd/jenkins/pr-centos-8-x86_64-py3-pytest
  cicd/jenkins/pr-debian-10-amd64-py3-pytest
  cicd/jenkins/pr-debian-9-amd64-py3-pytest
  cicd/jenkins/pr-docs
  cicd/jenkins/pr-fedora-32-x86_64-py3-pytest
  cicd/jenkins/pr-fedora-33-x86_64-py3-pytest
  cicd/jenkins/pr-freebsd-122-amd64-py3-pytest
  cicd/jenkins/pr-lint
  cicd/jenkins/pr-macosx-catalina-x86_64-py3-pytest
  cicd/jenkins/pr-macosx-mojave-x86_64-py3-pytest
  cicd/jenkins/pr-opensuse-15-x86_64-py3-pytest
  cicd/jenkins/pr-pre-commit
  cicd/jenkins/pr-ubuntu-1804-amd64-py3-pytest
  cicd/jenkins/pr-ubuntu-2004-amd64-py3-pytest
  cicd/jenkins/pr-windows-2016-x64-py3-pytest
  cicd/jenkins/pr-windows-2019-x64-py3-pytest
Labels: point-release

#59869 add distro_arch
  changelog/59869.removed
  cicd/jenkins/kitchen-centos7-py3-m2crypto-pytest
  cicd/jenkins/kitchen-centos7-py3-pycryptodome-pytest
  cicd/jenkins/kitchen-debian10-py3-pytest
  cicd/jenkins/kitchen-ubuntu1604-py3-m2crypto-pytest
  cicd/jenkins/pr-amazon-2-x86_64-py3-pytest
  cicd/jenkins/pr-arch-lts-x86_64-py3-pytest
  cicd/jenkins/pr-centos-7-x86_64-py3-cloud-pytest
  cicd/jenkins/pr-centos-7-x86_64-py3-m2crypto-pytest
  cicd/jenkins/pr-centos-7-x86_64-py3-pycryptodome-pytest
  cicd/jenkins/pr-centos-7-x86_64-py3-pytest
  cicd/jenkins/pr-centos-7-x86_64-py3-tcp-pytest
  cicd/jenkins/pr-centos-8-x86_64-py3-pytest
  cicd/jenkins/pr-debian-10-amd64-py3-pytest
  cicd/jenkins/pr-debian-9-amd64-py3-pytest
  cicd/jenkins/pr-docs
  cicd/jenkins/pr-fedora-32-x86_64-py3-pytest
  cicd/jenkins/pr-fedora-33-x86_64-py3-pytest
  cicd/jenkins/pr-freebsd-122-amd64-py3-pytest
  cicd/jenkins/pr-lint
  cicd/jenkins/pr-macosx-catalina-x86_64-py3-pytest
  cicd/jenkins/pr-macosx-mojave-x86_64-py3-pytest
  cicd/jenkins/pr-opensuse-15-x86_64-py3-pytest
  cicd/jenkins/pr-pre-commit
  cicd/jenkins/pr-ubuntu-1804-amd64-py3-pytest
  cicd/jenkins/pr-ubuntu-2004-amd64-py3-pytest
  cicd/jenkins/pr-windows-2016-x64-py3-pytest
  cicd/jenkins/pr-windows-2019-x64-py3-pytest
Labels: Silicon, has-failing-test

#59999 changing the cloud platforms file missed in 1a9b7be0e2f300d87924731dc5816fd1000cd22b
  cicd/jenkins/pr-centos-7-x86_64-py3-cloud-pytest
Labels: point-release

#60000 changing the cloud platforms file missed in 24b69a9e389939d543b2b2b98318820da88ece66
  cicd/jenkins/pr-centos-7-x86_64-py3-cloud-pytest
Labels: Silicon

#57881 Parsing Epoch out of version provided during pkg remove
  changelog/57881.changed
  salt/modules/yumpkg.py
  tests/unit/modules/test_yumpkg.py
Labels: Needs Testcase, has-failing-test

#59629 Add missing newline in doc
  doc/ref/states/vars.rst
Labels: Documentation, Silicon
