Repository saltstack/salt, pull requests merged in 2021-08, with the labels that each got.

#60633 Add detect_remote_minions and remote_minions_port options to detect minions connected on other ports
  changelog/60612.added
  doc/ref/configuration/master.rst
  salt/config/__init__.py
  salt/utils/minions.py
  tests/pytests/unit/utils/test_minions.py
Labels: Silicon

#60584 Bump to ``urllib3==1.26.6``
  requirements/static/ci/py3.10/cloud.txt
  requirements/static/ci/py3.10/darwin.txt
  requirements/static/ci/py3.10/docs.txt
  requirements/static/ci/py3.10/freebsd.txt
  requirements/static/ci/py3.10/linux.txt
  requirements/static/ci/py3.10/windows.txt
  requirements/static/ci/py3.5/cloud.txt
  requirements/static/ci/py3.5/docs.txt
  requirements/static/ci/py3.5/linux.txt
  requirements/static/ci/py3.6/cloud.txt
  requirements/static/ci/py3.6/docs.txt
  requirements/static/ci/py3.6/linux.txt
  requirements/static/ci/py3.7/cloud.txt
  requirements/static/ci/py3.7/darwin.txt
  requirements/static/ci/py3.7/docs.txt
  requirements/static/ci/py3.7/freebsd.txt
  requirements/static/ci/py3.7/linux.txt
  requirements/static/ci/py3.7/windows.txt
  requirements/static/ci/py3.8/cloud.txt
  requirements/static/ci/py3.8/darwin.txt
  requirements/static/ci/py3.8/docs.txt
  requirements/static/ci/py3.8/freebsd.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.8/windows.txt
  requirements/static/ci/py3.9/cloud.txt
  requirements/static/ci/py3.9/darwin.txt
  requirements/static/ci/py3.9/docs.txt
  requirements/static/ci/py3.9/freebsd.txt
  requirements/static/ci/py3.9/linux.txt
  requirements/static/ci/py3.9/windows.txt
  requirements/static/pkg/py3.10/darwin.txt
  requirements/static/pkg/py3.10/freebsd.txt
  requirements/static/pkg/py3.10/linux.txt
  requirements/static/pkg/py3.10/windows.txt
  requirements/static/pkg/py3.5/linux.txt
  requirements/static/pkg/py3.6/linux.txt
  requirements/static/pkg/py3.7/darwin.txt
  requirements/static/pkg/py3.7/freebsd.txt
  requirements/static/pkg/py3.7/linux.txt
  requirements/static/pkg/py3.7/windows.txt
  requirements/static/pkg/py3.8/darwin.txt
  requirements/static/pkg/py3.8/freebsd.txt
  requirements/static/pkg/py3.8/linux.txt
  requirements/static/pkg/py3.8/windows.txt
  requirements/static/pkg/py3.9/darwin.txt
  requirements/static/pkg/py3.9/freebsd.txt
  requirements/static/pkg/py3.9/linux.txt
  requirements/static/pkg/py3.9/windows.txt
Labels: Silicon

#59956 [DOCS] Update nxos installation docs to use python3
  doc/topics/installation/nxos.rst
Labels: Documentation, Silicon

#60709 fix https://github.com/saltstack/salt/issues/60682
  doc/topics/tutorials/gitfs.rst
Labels: Documentation

#60604 Fixing the state aggregation system to properly handle requisities
  changelog/47628.fixed
  salt/state.py
  salt/states/pkg.py
  tests/pytests/unit/state/test_multi_env_highstate.py
  tests/pytests/unit/state/test_state_compiler.py
  tests/pytests/unit/state/test_state_format_slots.py
  tests/pytests/unit/state/test_state_highstate.py
  tests/pytests/unit/state/test_state_returns.py
  tests/pytests/unit/state/test_sub_state_returns.py
  tests/pytests/unit/states/test_pkg.py
  tests/unit/test_state.py
Labels: Silicon

#60726 update PULL_REQUEST_TEMPLATE with docs.saltproject.io urls
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation, Silicon

#60725 change repo.saltstack.com to repo.saltproject.io
  doc/_themes/saltstack2/layout.html
  doc/conf.py
  doc/topics/cloud/windows.rst
  doc/topics/development/conventions/release.rst
  doc/topics/installation/debian.rst
  doc/topics/installation/osx.rst
  doc/topics/installation/suse.rst
  doc/topics/installation/ubuntu.rst
  doc/topics/installation/windows.rst
  doc/topics/tutorials/docker_sls.rst
  pkg/windows/build_pkg.bat
  pkg/windows/modules/get-settings.psm1
  salt/modules/saltutil.py
  salt/runners/manage.py
  tests/integration/modules/test_cp.py
  tests/integration/modules/test_pkg.py
  tests/support/win_installer.py
Labels: Silicon

#60447 Fixes to mysql cache
  changelog/60398.fixed
  salt/cache/mysql_cache.py
  tests/pytests/unit/cache/test_mysql_cache.py
Labels: Silicon

#60255 update bug_template.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Documentation, has-failing-test

#60415 Fix windows file recurse with clean true
  changelog/47969.fixed
  salt/states/file.py
  salt/utils/files.py
  tests/pytests/unit/utils/test_files.py
  tests/unit/states/test_file.py
  tests/unit/utils/test_files.py
Labels: ZD, Silicon

#60489 Only show the filename of a URL when something goes wrong
  changelog/60203.fixed
  salt/fileclient.py
  tests/pytests/integration/states/test_file.py
Labels: Silicon

#60778 Fix RuntimeError in process mangager
  changelog/60749.fixed
  salt/utils/process.py
  tests/pytests/functional/utils/test_process.py
Labels: Silicon

#59435 Fix 59063
  changelog/59063.fixed
  salt/utils/pycrypto.py
  tests/pytests/unit/utils/test_pycrypto.py
  tests/unit/utils/test_pycrypto.py
Labels: Silicon

#60502 Fixing various functions in the file state module that use user.info
  changelog/57786.fixed
  salt/states/file.py
  tests/filename_map.yml
  tests/pytests/unit/states/file/test_absent.py
  tests/pytests/unit/states/file/test_comment.py
  tests/pytests/unit/states/file/test_copy.py
  tests/pytests/unit/states/file/test_directory.py
  tests/pytests/unit/states/file/test_filestate.py
  tests/pytests/unit/states/file/test_find_keep_files.py
  tests/pytests/unit/states/file/test_hardlink.py
  tests/pytests/unit/states/file/test_keyvalue.py
  tests/pytests/unit/states/file/test_managed.py
  tests/pytests/unit/states/file/test_mod_beacon.py
  tests/pytests/unit/states/file/test_prepend.py
  tests/pytests/unit/states/file/test_private_functions.py
  tests/pytests/unit/states/file/test_rename.py
  tests/pytests/unit/states/file/test_retention_schedule.py
  tests/pytests/unit/states/file/test_selinux.py
  tests/pytests/unit/states/file/test_symlink.py
  tests/pytests/unit/states/file/test_tidied.py
  tests/unit/states/test_file.py
Labels: Silicon

#60303 Consolidating beacon configuration mapping code
  changelog/60241.fixed
  salt/beacons/adb.py
  salt/beacons/avahi_announce.py
  salt/beacons/bonjour_announce.py
  salt/beacons/btmp.py
  salt/beacons/cert_info.py
  salt/beacons/glxinfo.py
  salt/beacons/haproxy.py
  salt/beacons/inotify.py
  salt/beacons/journald.py
  salt/beacons/load.py
  salt/beacons/log_beacon.py
  salt/beacons/memusage.py
  salt/beacons/network_info.py
  salt/beacons/network_settings.py
  salt/beacons/proxy_example.py
  salt/beacons/ps.py
  salt/beacons/salt_monitor.py
  salt/beacons/salt_proxy.py
  salt/beacons/sensehat.py
  salt/beacons/service.py
  salt/beacons/smartos_imgadm.py
  salt/beacons/smartos_vmadm.py
  salt/beacons/swapusage.py
  salt/beacons/telegram_bot_msg.py
  salt/beacons/twilio_txt_msg.py
  salt/beacons/wtmp.py
  salt/utils/beacons.py
  tests/pytests/unit/utils/test_beacons.py
Labels: Silicon

#60774 Push dep neut
  salt/utils/openstack/neutron.py
Labels: Silicon, Deprecation

#60257 Update pcs support for > 0.10
  changelog/56924.fixed
  salt/modules/pcs.py
  salt/states/pcs.py
  tests/pytests/unit/modules/test_pcs.py
Labels: Feature

#60788 Minor doc updates for service.mod_watch
  salt/states/service.py
Labels: Documentation, doc-rework

#60812 Setting up CSE search values through 3006
  doc/conf.py
Labels: Documentation, Silicon
