Repository saltstack/salt, pull requests merged in 2021-02, with the labels that each got.

#59104 Schedule Items in Pillar Refresh Fixes
  changelog/59104.fixed
  salt/minion.py
  salt/modules/schedule.py
  salt/utils/schedule.py
  tests/pytests/integration/modules/test_pillar.py
  tests/unit/modules/test_schedule.py
Labels: Aluminium

#58960 Fix issue with MySQL 8 and "all privileges" grant
  changelog/58933.fixed
  salt/modules/mysql.py
  tests/unit/modules/test_mysql.py
Labels: Aluminium

#58443 Fix Pop!_OS 20.04 not using aptpkg
  changelog/58395.fixed
  salt/grains/core.py
  tests/unit/grains/test_core.py
Labels: Aluminium, Bug, severity-medium

#56479 Fix digitalocean reboot action error messaging
  salt/cloud/clouds/digitalocean.py
  tests/unit/cloud/clouds/test_digitalocean.py
Labels: Aluminium

#59261 Fix docs for auth_timeout
  changelog/59175.fixed
  doc/ref/configuration/minion.rst
Labels: Aluminium, Documentation

#59118 removing duplicate python 2 deprecation faq from development doc
  doc/topics/development/index.rst
Labels: Aluminium

#59423 Prevent badly named changelog files from being committed
  .pre-commit-hooks/check-changelog-entries.py
Labels: Aluminium

#59291 Add twine check to GitHub Actions
  .github/workflows/twine-check.yml
Labels: Aluminium

#59445 use sphinx.ext.imgconverter
  .github/workflows/docs.yml
  doc/conf.py
Labels: Aluminium, Documentation

#59465 Supress noisy warnings
  changelog/50327.fixed
  salt/transport/__init__.py
Labels: Aluminium

#59463 Updates to pkg beacon, fire when installed or removed
  changelog/59463.changed
  salt/beacons/pkg.py
  salt/modules/aixpkg.py
  salt/modules/apkpkg.py
  salt/modules/aptpkg.py
  salt/modules/beacons.py
  salt/modules/ebuildpkg.py
  salt/modules/freebsdpkg.py
  salt/modules/mac_brew_pkg.py
  salt/modules/mac_portspkg.py
  salt/modules/openbsdpkg.py
  salt/modules/opkg.py
  salt/modules/pacmanpkg.py
  salt/modules/pkg_resource.py
  salt/modules/pkgin.py
  salt/modules/pkgng.py
  salt/modules/pkgutil.py
  salt/modules/solarisipspkg.py
  salt/modules/solarispkg.py
  salt/modules/yumpkg.py
  salt/modules/zypperpkg.py
  tests/pytests/unit/modules/test_aptpkg.py
  tests/pytests/unit/modules/test_openbsdpkg.py
  tests/pytests/unit/modules/test_pacmanpkg.py
  tests/pytests/unit/modules/test_pkgutil.py
  tests/pytests/unit/modules/test_yumpkg.py
  tests/pytests/unit/modules/test_zypperpkg.py
  tests/unit/modules/test_aptpkg.py
  tests/unit/modules/test_mac_brew_pkg.py
  tests/unit/modules/test_openbsdpkg.py
  tests/unit/modules/test_pacmanpkg.py
  tests/unit/modules/test_pkgutil.py
  tests/unit/modules/test_zypperpkg.py
Labels: Aluminium

#59385 Fix: code quality issues
  doc/_ext/saltautodoc.py
  doc/_ext/saltdomain.py
  salt/modules/ipset.py
  salt/modules/vmctl.py
  salt/modules/win_lgpo.py
  scripts/suse/yum/plugins/yumnotify.py
Labels: Aluminium

#58959 Correct capitalization in service state comment
  salt/states/service.py
  tests/unit/states/test_service.py
Labels: Aluminium

#59521 Fix 'write' references under the 'read' function for macdefaults.py in documentation
  salt/modules/macdefaults.py
Labels: Aluminium, Documentation, doc-rework, docstring-update

#59532 Upgrade to `pytest-salt-factories==0.121.0`
  requirements/pytest.txt
  requirements/static/ci/py3.5/darwin.txt
  requirements/static/ci/py3.5/freebsd.txt
  requirements/static/ci/py3.5/linux.txt
  requirements/static/ci/py3.5/windows.txt
  requirements/static/ci/py3.6/darwin.txt
  requirements/static/ci/py3.6/freebsd.txt
  requirements/static/ci/py3.6/linux.txt
  requirements/static/ci/py3.6/windows.txt
  requirements/static/ci/py3.7/darwin.txt
  requirements/static/ci/py3.7/freebsd.txt
  requirements/static/ci/py3.7/linux.txt
  requirements/static/ci/py3.7/windows.txt
  requirements/static/ci/py3.8/darwin.txt
  requirements/static/ci/py3.8/freebsd.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.9/darwin.txt
  requirements/static/ci/py3.9/freebsd.txt
  requirements/static/ci/py3.9/linux.txt
Labels: dependency

#55062 Fix empty reactor traceback in reactor.py
  changelog/53334.fixed
  salt/runners/reactor.py
  tests/unit/runners/test_reactor.py
Labels: help-wanted

#59411 Adding the ability to clear and show the pillar cache enabled when pillar_cache is True.
  changelog/37080.added
  salt/pillar/__init__.py
  salt/runners/cache.py
  salt/runners/pillar.py
  salt/utils/cache.py
  tests/pytests/unit/runners/test_pillar.py
Labels: Aluminium

#57770 modules.postgres: pass waldir to init
  salt/modules/postgres.py
  tests/unit/modules/test_postgres.py
Labels: Aluminium

#59022 Update ignored revisions for git-blame
  .git-blame-ignore-revs
Labels: Aluminium

#59577 [DOCS] Fix contrib links: Point to master branch for development docs links
  .github/config.yml
  README.rst
  SECURITY.md
Labels: Aluminium, Documentation

#59468 Bump `cryptography` requirement to 3.3.2 due to CVE-2020-36242
  requirements/static/ci/py3.5/cloud.txt
  requirements/static/ci/py3.5/darwin.txt
  requirements/static/ci/py3.5/freebsd.txt
  requirements/static/ci/py3.5/linux.txt
  requirements/static/ci/py3.5/windows.txt
  requirements/static/ci/py3.6/cloud.txt
  requirements/static/ci/py3.6/darwin.txt
  requirements/static/ci/py3.6/freebsd.txt
  requirements/static/ci/py3.6/linux.txt
  requirements/static/ci/py3.6/windows.txt
  requirements/static/ci/py3.7/cloud.txt
  requirements/static/ci/py3.7/darwin.txt
  requirements/static/ci/py3.7/freebsd.txt
  requirements/static/ci/py3.7/linux.txt
  requirements/static/ci/py3.7/windows.txt
  requirements/static/ci/py3.8/cloud.txt
  requirements/static/ci/py3.8/darwin.txt
  requirements/static/ci/py3.8/freebsd.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.9/cloud.txt
  requirements/static/ci/py3.9/darwin.txt
  requirements/static/ci/py3.9/freebsd.txt
  requirements/static/ci/py3.9/linux.txt
  requirements/static/pkg/py3.5/darwin.txt
  requirements/static/pkg/py3.5/freebsd.txt
  requirements/static/pkg/py3.5/linux.txt
  requirements/static/pkg/py3.5/windows.txt
  requirements/static/pkg/py3.6/darwin.txt
  requirements/static/pkg/py3.6/freebsd.txt
  requirements/static/pkg/py3.6/linux.txt
  requirements/static/pkg/py3.6/windows.txt
  requirements/static/pkg/py3.7/darwin.txt
  requirements/static/pkg/py3.7/freebsd.txt
  requirements/static/pkg/py3.7/linux.txt
  requirements/static/pkg/py3.7/windows.txt
  requirements/static/pkg/py3.8/darwin.txt
  requirements/static/pkg/py3.8/freebsd.txt
  requirements/static/pkg/py3.8/linux.txt
  requirements/static/pkg/py3.8/windows.txt
  requirements/static/pkg/py3.9/darwin.txt
  requirements/static/pkg/py3.9/freebsd.txt
  requirements/static/pkg/py3.9/linux.txt
  requirements/static/pkg/py3.9/windows.txt
Labels: Aluminium

#58380 Use default timezone offset in scheduler when correct timezone cannot be determined
  changelog/58379.fixed
  salt/utils/schedule.py
  tests/pytests/unit/utils/test_schedule.py
Labels: Aluminium, Windows, merge-conflict

#59591 Update RC installation instructions
  doc/topics/releases/releasecandidate.rst
Labels: Aluminium

#59548 Salt Versions E2E Backwards Compatibility Tests
  tests/pytests/scenarios/compat/__init__.py
  tests/pytests/scenarios/compat/conftest.py
  tests/pytests/scenarios/compat/test_with_versions.py
Labels: Aluminium

#59258 Update branding for Windows
  pkg/windows/installer/panel.bmp
  pkg/windows/installer/panel.xcf
  pkg/windows/installer/salt.ico
  pkg/windows/installer/salt.xcf
Labels: Aluminium

#59616 RHEL Installation updates: Remove RHEL 5 and 6 references, remove EPEL references
  doc/topics/installation/rhel.rst
Labels: Aluminium

#58962 Strip trailing "/" from repo.uri when comparing repos in "apktpkg.mod_repo"
  changelog/58962.fixed
  salt/modules/aptpkg.py
  tests/pytests/unit/modules/test_aptpkg.py
Labels: Aluminium
