Repository saltstack/salt, pull requests merged in 2021-03, with the labels that each got.

#59034 Add SCRAM-SHA-256 support to postgres states
  changelog/51271.added
  changelog/59034.fixed
  doc/topics/releases/3003.rst
  salt/ext/saslprep.py
  salt/modules/postgres.py
  salt/states/postgres_group.py
  salt/states/postgres_user.py
  tests/filename_map.yml
  tests/pytests/unit/modules/test_postgres.py
  tests/pytests/unit/states/test_postgres_group.py
  tests/pytests/unit/states/test_postgres_user.py
  tests/unit/states/test_postgres.py
  tests/unit/states/test_postgres_group.py
  tests/unit/states/test_postgres_user.py
Labels: Aluminium, Feature, Tests Passed

#59633 Updating Twitch links: Now https://www.twitch.tv/saltprojectoss
  .github/config.yml
  CONTRIBUTING.rst
  README.rst
Labels: Aluminium, Documentation

#56880 Always run check-docs hook to detect deleted files.
  .github/workflows/pre-commit.yml
  tasks/docs.py
Labels: Aluminium

#59681 Update to latest bootstrap-salt.sh, v2020.03.02
  salt/cloud/deploy/bootstrap-salt.sh
Labels: Aluminium

#59459 Wean off IOLoop.run_sync
  salt/__init__.py
  salt/transport/ipc.py
  salt/utils/event.py
  tests/pytests/functional/transport/ipc/test_subscriber.py
Labels: Aluminium

#59432 Implement tcp_reconnect_backoff minion option
  changelog/59431.added
  doc/ref/configuration/minion.rst
  salt/config/__init__.py
  salt/transport/tcp.py
  tests/pytests/unit/transport/test_tcp.py
Labels: Aluminium, Feature

#59710 Fix failing ssh tests on Windows Server 2019
  salt/fileserver/roots.py
Labels: Aluminium, Tests

#59723 Add back `minion_id`
  salt/matchers/glob_match.py
Labels: Aluminium

#59707 Clarify requirements for macOS builds
  pkg/osx/build.sh
  pkg/osx/notarize.sh
Labels: Aluminium

#59822 Merge 3002.6 bugfix changes
  CHANGELOG.md
  doc/topics/releases/3000.9.rst
  doc/topics/releases/3001.7.rst
  doc/topics/releases/3002.6.rst
  salt/client/ssh/client.py
  salt/modules/restartcheck.py
  tests/pytests/unit/client/test_ssh.py
  tests/unit/modules/test_restartcheck.py
  tests/unit/test_module_names.py
Labels: Aluminium

#59814 [freeze] Bump deprecation warning to Phosphorus.
  salt/modules/keystone.py
Labels: Aluminium

#59813 Bump keystone deprecation warning to Phosphorus.
  salt/modules/keystone.py
Labels: Aluminium

#59797 modules/match: add missing "minion_id" in Pillar example
  salt/modules/match.py
  tests/pytests/integration/modules/test_pillar.py
Labels: Aluminium, has-failing-test

#59862 Add #59797 to freeze branch
  salt/modules/match.py
  tests/pytests/integration/modules/test_pillar.py
Labels: Aluminium

#59883 [freeze] Fix warts in changelog
  CHANGELOG.md
Labels: Aluminium

#59881 Salt api honors --log-file correctly
  changelog/59880.fixed
  salt/cli/api.py
  tests/pytests/functional/cli/test_api.py
  tests/unit/cli/test_api.py
Labels: Silicon

#59897 add ubuntu-2004-amd64 m2crypto pycryptodome and tcp tests
  cicd/jenkins/pr-ubuntu-2004-amd64-py3-m2crypto-pytest
  cicd/jenkins/pr-ubuntu-2004-amd64-py3-pycryptodome-pytest
  cicd/jenkins/pr-ubuntu-2004-amd64-py3-tcp-pytest
Labels: Silicon

#59893 Adding mendel linux
  changelog/59892.fixed
  salt/grains/core.py
  tests/unit/grains/test_core.py
Labels: Feature, Silicon

#57662 add tiamat run.py script
  run.py
Labels: Silicon
