Repository saltstack/salt, pull requests merged in 2021-06, with the labels that each got.

#60295 fix github actions jobs on branch until bullseye comes out
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/pre-commit.yml
Labels: Silicon

#60277 doc: clarify TCP usage by zmq ports
  doc/topics/development/topology.rst
Labels: Documentation, Silicon

#60289 Document fix, with black changes for format
  salt/returners/redis_return.py
Labels: Documentation, Silicon, doc-ex-missing

#60133 Handle volumes on stopped pools in virt.vm_info
  changelog/60132.fixed
  salt/modules/virt.py
  tests/pytests/unit/modules/virt/test_domain.py
Labels: Silicon

#60305 Fix GitHub actions doc filter
  .github/workflows/docs.yml
Labels: Silicon

#60355 [DOCS] fix docstring typo in salt.utils.win_runas
  salt/utils/win_runas.py
Labels: Documentation, Silicon, docstring-update

#60369 Fix ValueError exception in state.show_state_usage
  changelog/60179.fixed
  salt/state.py
  tests/unit/test_state.py
Labels: Silicon

#60173 Ensure proper access to the created temporary file when ``runas`` is passed to ``cmd.exec_code_all``
  changelog/60072.fixed
  salt/modules/cmdmod.py
  tests/pytests/integration/modules/test_cmdmod.py
Labels: Silicon

#60455 Update banner images in docs HTML output
  doc/_themes/saltstack2/layout.html
Labels: Documentation
