Repository saltstack/salt, pull requests merged in 2021-07, with the labels that each got.

#60087 Fixes to mysql modules and state modules
  changelog/60031.fixed
  requirements/static/ci/linux.in
  requirements/static/ci/py3.10/linux.txt
  requirements/static/ci/py3.5/linux.txt
  requirements/static/ci/py3.6/linux.txt
  requirements/static/ci/py3.7/linux.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.9/linux.txt
  salt/modules/mysql.py
  tests/pytests/integration/modules/test_mysql.py
  tests/pytests/integration/states/test_mysql.py
  tests/pytests/unit/modules/test_mysql.py
  tests/support/pytest/mysql.py
  tests/unit/modules/test_mysql.py
Labels: Silicon

#60484 fix release notes about dropping ubuntu 16.04
  CHANGELOG.md
  doc/topics/releases/3003.1.rst
  doc/topics/releases/3003.rst
Labels: Documentation

#60342 The traceback.*_exc() functions do not have an exc argument.
  changelog/60330.fixed
  salt/modules/zcbuildout.py
  salt/netapi/rest_cherrypy/app.py
  salt/states/zcbuildout.py
  salt/utils/parsers.py
  tests/unit/modules/test_zcbuildout.py
  tests/unit/states/test_pip_state.py
  tests/unit/states/test_zcbuildout.py
Labels: Silicon, has-failing-test

#60517 update to opensuse 15.3
  cicd/jenkins/pr-opensuse-15-x86_64-py3-pytest
Labels: Silicon

#60570 [3003.2] Removing tmpfs from Fedora 33
  cicd/jenkins/pr-fedora-33-x86_64-py3-pytest
Labels: Tests

#60588 Port old test changes to new pytest test_core.py from PR 60514
  tests/pytests/unit/grains/test_core.py
Labels: Bug, solaris

#60608 Automatically add ``needs-triage`` label and assign new issues
  .github/workflows/scripts/label-and-assign.py
  .github/workflows/triage.yml
Labels: Silicon

#60598 run.py for Windows Singlebin
  run.py
Labels: Silicon

#60573 [3003.2] Add server alive
  changelog/60216.fixed
  salt/utils/cloud.py
  tests/pytests/unit/utils/test_cloud.py
Labels: v3003.2
