Repository saltstack/salt, pull requests merged in 2021-11, with the labels that each got.

#61025 Moving tests/integration/states/test_pkg.py to pytest
  tests/filename_map.yml
  tests/integration/states/test_pkg.py
  tests/pytests/functional/states/test_pkg.py
Labels: Phosphorus v3005.0

#60324 [FIX UNIT TEST] Mock ip_addrs() in utils/minions.py unit test
  tests/pytests/unit/utils/test_minions.py
Labels: test-fix

#60164 Refresh `mine.send` documentation
  salt/modules/mine.py
Labels: Documentation
