Repository saltstack/salt, pull requests merged in 2022-10, with the labels that each got.

#61897 Adding some additional tests that tests grants when using all privileges.
  tests/pytests/functional/states/test_mysql.py
Labels: Sulfur v3006.0

#60733 Fix link to module zypperpkg in docs
  salt/states/pkg.py
  salt/states/pkgrepo.py
Labels: Documentation

#61189 Fix cached pillar errors on `state.apply`
  changelog/52354.fixed
  changelog/57180.fixed
  changelog/59339.fixed
  salt/modules/state.py
  tests/pytests/integration/modules/state/test_state_pillar_errors.py
  tests/pytests/unit/modules/state/test_state.py
Labels: has-failing-test, Sulfur v3006.0

#58055 [merge jam] Master port 48609 - file.serialize
  changelog/48609.changed
  salt/states/file.py
  tests/integration/states/test_file.py
Labels: master-port, Sulfur v3006.0

#62475 Fixed parsing CDROM apt sources
  changelog/62474.fixed
  changelog/62485.deprecated
  salt/modules/aptpkg.py
  salt/states/pkgrepo.py
  tests/pytests/functional/modules/test_aptpkg.py
  tests/pytests/functional/states/pkgrepo/test_debian.py
  tests/pytests/unit/modules/test_aptpkg.py
Labels: merge-conflict

#62813 Fix vt.Terminal failing test: test_log_sanitize
  tests/pytests/unit/utils/test_vt.py
Labels: Sulfur v3006.0

#57426 Improve pkg.installed pkg_verify documentation
  salt/states/pkg.py
Labels: docstring-update

#61674 Update coverage version
  noxfile.py
Labels: P1, Sulfur v3006.0

#61356 avoids crash on cache corruption
  changelog/60170.fixed
  salt/returners/local_cache.py
  tests/pytests/unit/returners/test_local_cache.py
Labels: Sulfur v3006.0

#61311 update fix bug 60915 parse terraform.tfstate error
  changelog/60915.fixed
  salt/roster/terraform.py
  tests/pytests/unit/roster/terraform.data/terraform-new.tfstate
  tests/pytests/unit/roster/test_terraform.py
Labels: Needs-Testcase

#58022 State schedule doc formatting
  salt/states/schedule.py
Labels: Documentation

#61933 ipwrap() Jinja filter
  changelog/61931.added
  doc/topics/jinja/index.rst
  salt/utils/network.py
  tests/pytests/unit/utils/jinja/test_custom_extensions.py
Labels: Sulfur v3006.0

#62803 Fix schedule.list regression
  changelog/62795.fixed
  salt/modules/schedule.py
  tests/pytests/unit/modules/test_schedule.py
Labels: Sulfur v3006.0

#62863 Disable the setuptools user warning "Setuptools is replacing distutils."
  salt/__init__.py
  setup.py
Labels: Sulfur v3006.0

#61953 Mark test_list_available_packages requiring network
  tests/pytests/functional/modules/test_pip.py
Labels: Sulfur v3006.0

#62883 Http json add namespace
  changelog/61335.added
  salt/pillar/http_json.py
  tests/pytests/unit/pillar/test_http_json_pillar.py
Labels: Sulfur v3006.0

#62862 Fix extend+exclude interaction
  changelog/62082.fixed
  salt/state.py
  tests/pytests/unit/state/test_state_highstate.py
Labels: Sulfur v3006.0

#62885 Adding some additional rabbitmq test cases
  tests/pytests/functional/states/rabbitmq/conftest.py
  tests/pytests/functional/states/rabbitmq/test_user.py
Labels: Sulfur v3006.0

#61410 Add missing MariaDB Grants to mysql module
  changelog/61409.changed
  salt/modules/mysql.py
Labels: Needs-Testcase, Sulfur v3006.0, pending-close

#60711 Fix wrong filename and path name for matchers documentation
  doc/topics/matchers/index.rst
Labels: P1

#62887 Cosmetic fix in the cassandra_cql module
  changelog/62886.fixed
  salt/modules/cassandra_cql.py
Labels: Sulfur v3006.0

#62888 LGPO: Add support to apply registry settings directly to Registry.pol
  changelog/56013.added
  doc/ref/modules/all/index.rst
  doc/ref/modules/all/salt.modules.win_lgpo.rst
  doc/ref/modules/all/salt.modules.win_lgpo_reg.rst
  doc/ref/states/all/index.rst
  doc/ref/states/all/salt.states.win_lgpo.rst
  doc/ref/states/all/salt.states.win_lgpo_reg.rst
  salt/modules/win_lgpo.py
  salt/modules/win_lgpo_reg.py
  salt/states/win_lgpo_reg.py
  salt/utils/win_lgpo_reg.py
  salt/utils/win_reg.py
  tests/pytests/functional/modules/win_lgpo/test_write_regpol.py
  tests/pytests/functional/states/win_lgpo/test_admx_policy.py
  tests/pytests/functional/states/win_lgpo/test_adv_audit_settings_state.py
  tests/pytests/functional/states/win_lgpo/test_audit_settings_state.py
  tests/pytests/functional/states/win_lgpo/test_rights_assignment.py
  tests/pytests/unit/modules/test_win_lgpo_reg.py
  tests/pytests/unit/modules/win_lgpo/__init__.py
  tests/pytests/unit/modules/win_lgpo/test_admx_policies.py
  tests/pytests/unit/modules/win_lgpo/test_adv_audit_settings.py
  tests/pytests/unit/modules/win_lgpo/test_mechanisms.py
  tests/pytests/unit/modules/win_lgpo/test_point_print_enabled.py
  tests/pytests/unit/modules/win_lgpo/test_point_print_nc.py
  tests/pytests/unit/modules/win_lgpo/test_policy_info.py
  tests/pytests/unit/modules/win_lgpo/test_policy_info_functions.py
  tests/pytests/unit/modules/win_lgpo/test_policy_resources.py
  tests/pytests/unit/modules/win_lgpo/test_secedit_policy.py
  tests/pytests/unit/states/test_win_lgpo.py
  tests/pytests/unit/states/test_win_lgpo_reg.py
  tests/pytests/unit/utils/test_win_lgpo_reg.py
  tests/pytests/unit/utils/win_lgpo/__init__.py
  tests/pytests/unit/utils/win_lgpo/test_auditpol.py
  tests/pytests/unit/utils/win_lgpo/test_netsh.py
  tests/unit/modules/test_win_lgpo.py
  tests/unit/utils/test_win_lgpo_auditpol.py
  tests/unit/utils/test_win_lgpo_netsh.py
Labels: Sulfur v3006.0

#62832 Updates to mongo module, adding tests
  changelog/62900.fixed
  salt/modules/mongodb.py
  tests/pytests/unit/modules/test_mongodb.py
Labels: Sulfur v3006.0

#62906 Add new vault option config_location
  changelog/61857.added
  salt/modules/vault.py
  salt/utils/vault.py
  tests/pytests/unit/utils/test_vault.py
Labels: Sulfur v3006.0

#61657 test_pkg: Do not run refresh_db on every pkg test
  tests/pytests/functional/modules/test_pkg.py
Labels: Sulfur v3006.0

#62926 Removing manufacture grain which has been deprecated
  changelog/62914.deprecated
  salt/grains/core.py
Labels: Sulfur v3006.0

#62922 Removing deprecated utils/boto3_elasticsearch.py
  changelog/62915.deprecated
  salt/utils/boto3_elasticsearch.py
Labels: Sulfur v3006.0

#62921 Fix FutureWarning always displayed for Azure providers
  changelog/62845.fixed
  salt/cloud/clouds/azurearm.py
  salt/cloud/clouds/msazure.py
Labels: Sulfur v3006.0

#62919 Remove non-sequitur Jenkins configuraton
  salt/modules/event.py
Labels: Documentation

#62925 Fix bandit deps
  .pre-commit-config.yaml
Labels: Sulfur v3006.0

#62924 Removing all references to napalm-base which is no longer supported.
  changelog/61542.deprecated
  salt/utils/napalm.py
Labels: Sulfur v3006.0

#62943 Fix systemd_service.* functions hard code relative command name
  changelog/62942.fixed
  salt/modules/systemd_service.py
  tests/unit/modules/test_systemd_service.py
Labels: Sulfur v3006.0

#62958 Fix file.symlink backupname operation can copy remote contents to local disk
  changelog/62953.fixed
  salt/modules/file.py
  salt/states/file.py
  tests/pytests/unit/modules/file/test_file_module.py
Labels: Sulfur v3006.0

#62310 Update quickstart.rst
  doc/topics/tutorials/quickstart.rst
Labels: Documentation, Sulfur v3006.0

#60487 Change slightly order of doc/ref/index.rst
  doc/ref/index.rst
Labels: Sulfur v3006.0

#62760 Cachedisk corruption
  changelog/62527.fixed
  salt/utils/cache.py
  tests/pytests/unit/utils/test_cache.py
Labels: Sulfur v3006.0

#59619 Update to RE #59611 -- Server Core Grains issue
  CHANGELOG.md
  salt/grains/core.py
  tests/pytests/unit/grains/test_core.py
Labels: Windows

#58729 Compat cmp dict fix
  changelog/58729.fixed
  salt/utils/compat.py
  tests/pytests/unit/utils/test_compat.py
Labels: boto

#62644 Deprecate Django returner
  changelog/62644.deprecated
  salt/returners/django_return.py
Labels: Sulfur v3006.0

#60701 Fix minor errors in set_autostart()'s docstring
  salt/modules/virt.py
Labels: P1

#62928 Update requisite matching documentation
  doc/ref/states/requisites.rst
Labels: Documentation
