Repository saltstack/salt, pull requests merged in 2022-11, with the labels that each got.

#62987 Fix file.tidied FileNotFoundError
  changelog/62986.fixed
  salt/states/file.py
  tests/pytests/unit/states/file/test_tidied.py
Labels: Sulfur v3006.0

#62976 fixed test_gpg_sign unit test
  changelog/62974.fixed
Labels: Sulfur v3006.0

#61433 Ensure a sensible timeout for pgsql commands
  changelog/61433.added
  salt/modules/postgres.py
  tests/pytests/unit/modules/test_postgres.py
Labels: P1, Sulfur v3006.0

#62994 Allow win_wua to load if CryptSvc set to Manual Start
  changelog/62993.fixed
  salt/modules/win_wua.py
  tests/pytests/unit/modules/test_win_wua.py
  tests/unit/modules/test_win_wua.py
Labels: Sulfur v3006.0

#60078 mongodb: return False when user_create fails
  changelog/53377.fixed
  salt/modules/mongodb.py
  tests/pytests/unit/modules/test_mongodb.py
Labels: severity-medium, Confirmed

#62150 fix returners.postgres inability to handle byte string responses
  changelog/55226.fixed
  salt/returners/mysql.py
  salt/returners/pgjsonb.py
  salt/returners/postgres.py
  tests/pytests/unit/returners/test_mysql.py
  tests/pytests/unit/returners/test_pgjsonb.py
  tests/pytests/unit/returners/test_postgres.py
Labels: Sulfur v3006.0

#62996 Move from Mayflower to Relenv
  pkg/windows/build_python.ps1
Labels: Sulfur v3006.0

#63012 Always populate `__sls__`, `__id__` and `name` on state requirements
  changelog/63012.changed
  salt/state.py
  tests/pytests/unit/state/test_state_compiler.py
Labels: Sulfur v3006.0

#63003 Fix the fedora test that has been failing: tests.unit.utils.test_process.TestSignalHandlingProcess.test_signal_processing_handle_signals_called
  tests/unit/utils/test_process.py
Labels: Sulfur v3006.0

#63017 Bump to `pytest-salt-factories==1.0.0rc21`
  requirements/pytest.txt
  requirements/static/ci/py3.10/cloud.txt
  requirements/static/ci/py3.10/darwin.txt
  requirements/static/ci/py3.10/freebsd.txt
  requirements/static/ci/py3.10/linux.txt
  requirements/static/ci/py3.10/windows.txt
  requirements/static/ci/py3.6/cloud.txt
  requirements/static/ci/py3.6/linux.txt
  requirements/static/ci/py3.7/cloud.txt
  requirements/static/ci/py3.7/freebsd.txt
  requirements/static/ci/py3.7/linux.txt
  requirements/static/ci/py3.7/windows.txt
  requirements/static/ci/py3.8/cloud.txt
  requirements/static/ci/py3.8/freebsd.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.8/windows.txt
  requirements/static/ci/py3.9/cloud.txt
  requirements/static/ci/py3.9/darwin.txt
  requirements/static/ci/py3.9/freebsd.txt
  requirements/static/ci/py3.9/linux.txt
  requirements/static/ci/py3.9/windows.txt
  tests/pytests/functional/states/test_mysql.py
Labels: Sulfur v3006.0

#63034 Fix file.retention_schedule always reports changes
  changelog/63033.fixed
  salt/states/file.py
  tests/pytests/unit/states/file/test_retention_schedule.py
Labels: Sulfur v3006.0

#62809 Fix Salt Syndic return events missing fun_args
  changelog/45823.fixed
  salt/master.py
  salt/minion.py
  tests/pytests/unit/test_master.py
Labels: Needs-Testcase

#63043 Add ability to ignore symlinks in file.tidied
  changelog/63042.added
  salt/states/file.py
  tests/pytests/unit/states/file/test_tidied.py
Labels: Sulfur v3006.0

#63030 Fix old root_dir paths on Windows
  changelog/62968.fixed
  changelog/63024.fixed
  salt/utils/cloud.py
  tests/pytests/unit/utils/test_cloud.py
Labels: Sulfur v3006.0, VMware

#61240 Do not require contextvars for Python >= 3.7
  requirements/base.txt
Labels: Pending-Discussion

#62897 Deltaproxy concurrent
  changelog/61153.added
  salt/metaproxy/deltaproxy.py
  salt/minion.py
  salt/proxy/ssh_sample.py
  tests/pytests/integration/cli/test_salt_deltaproxy.py
  tests/pytests/integration/proxy/conftest.py
  tests/pytests/integration/proxy/test_deltaproxy.py
  tests/pytests/unit/proxy/test_ssh_sample.py
Labels: Sulfur v3006.0

#57435 Port #51203 to master
  salt/modules/namecheap_domains.py
  salt/modules/namecheap_ssl.py
  salt/modules/napalm_network.py
  salt/modules/openbsdpkg.py
  salt/modules/opkg.py
  salt/modules/oracle.py
  salt/modules/pacmanpkg.py
  salt/modules/pagerduty_util.py
  salt/modules/parallels.py
  salt/modules/pkg_resource.py
  salt/modules/pkgng.py
  salt/modules/pkgutil.py
  salt/modules/portage_config.py
  salt/modules/proxy.py
  salt/modules/publish.py
  salt/modules/rbac_solaris.py
  salt/modules/rh_ip.py
  salt/modules/schedule.py
  salt/modules/servicenow.py
  salt/modules/smartos_virt.py
  salt/modules/smbios.py
  salt/modules/solaris_fmadm.py
  salt/modules/solarisipspkg.py
  salt/modules/solarispkg.py
  salt/modules/splunk.py
  salt/modules/ssh.py
  salt/modules/syslog_ng.py
  salt/modules/telemetry.py
  salt/modules/vboxmanage.py
  salt/modules/vmctl.py
  salt/modules/vsphere.py
  salt/modules/win_groupadd.py
  salt/modules/x509.py
  salt/modules/xapi_virt.py
  salt/modules/xbpspkg.py
  salt/modules/yumpkg.py
  salt/modules/zabbix.py
  salt/modules/zypperpkg.py
Labels: master-port, Sulfur v3006.0

#63059 modify gpg.encrypt example
  salt/modules/gpg.py
Labels: Documentation

#57222 Port #49310 to master
  changelog/49310.fixed
  salt/modules/file.py
  tests/pytests/functional/modules/file/test_touch.py
Labels: master-port

#63084 Fix Deltaproxy Custom Proxy Modules
  changelog/61805.fixed
  salt/metaproxy/deltaproxy.py
  tests/pytests/integration/cli/test_salt_deltaproxy.py
Labels: Sulfur v3006.0

#62717 Add global_state_conditions handling
  changelog/62446.added
  conf/minion
  doc/ref/configuration/minion.rst
  salt/config/__init__.py
  salt/state.py
  tests/pytests/unit/state/test_global_state_conditions.py
Labels: Sulfur v3006.0

#63101 Add doc examples for salt.runners.test. Fix typo.
  salt/runners/test.py
Labels: Documentation, doc-correction, docstring-update, doc-ex-missing

#62674 Improve Vault templating (policies, ext_pillar paths)
  changelog/43287.added
  salt/modules/vault.py
  salt/pillar/vault.py
  salt/runners/vault.py
  salt/utils/vault.py
  tests/pytests/integration/runners/test_vault.py
  tests/pytests/unit/pillar/test_vault.py
  tests/pytests/unit/runners/vault/test_app_role_auth.py
  tests/pytests/unit/runners/vault/test_token_auth.py
  tests/pytests/unit/runners/vault/test_vault.py
  tests/pytests/unit/utils/test_vault.py
Labels: Sulfur v3006.0

#63118 Update to the newer AMIs
  cicd/amis.yml
  cicd/jenkins/pr-centos-7-x86_64-py3-m2crypto-pytest
  cicd/jenkins/pr-centos-7-x86_64-py3-pycryptodome-pytest
  cicd/jenkins/pr-centosstream-8-x86_64-py3-pytest
  cicd/jenkins/pr-freebsd-131-amd64-py3-pytest
  cicd/jenkins/pr-ubuntu-2004-amd64-py3-m2crypto-pytest
  cicd/jenkins/pr-ubuntu-2004-amd64-py3-pycryptodome-pytest
  cicd/jenkins/pr-ubuntu-2204-amd64-py3-m2crypto-pytest
  cicd/jenkins/pr-ubuntu-2204-amd64-py3-pycryptodome-pytest
  salt/modules/npm.py
  tests/conftest.py
  tests/integration/cli/test_custom_module.py
  tests/integration/states/test_npm.py
  tests/pytests/functional/states/test_npm.py
  tests/pytests/integration/_logging/test_multiple_processes_logging.py
Labels: Sulfur v3006.0

#63137 Add documentation for pygit2 on Debian
  doc/topics/tutorials/gitfs.rst
Labels: Sulfur v3006.0

#63138 migrate test_cpan to pytest
  tests/pytests/unit/modules/test_cpan.py
  tests/unit/modules/test_cpan.py
Labels: Sulfur v3006.0

#63140 migrate test_ddns to pytest
  tests/pytests/unit/modules/test_ddns.py
  tests/unit/modules/test_ddns.py
Labels: Sulfur v3006.0

#63139 migrate test_daemontools to pytest
  tests/pytests/unit/modules/test_daemontools.py
  tests/unit/modules/test_daemontools.py
Labels: Sulfur v3006.0
