Repository saltstack/salt, pull requests merged in 2022-01, with the labels that each got.

#61256 Fix salt-call event.send call with grains and pillar
  changelog/61252.fixed
  salt/modules/event.py
  tests/pytests/integration/modules/test_event.py
Labels: Phosphorus v3005.0

#61165 Fix misspelled import of M2Crypto in test_crypt.py
  tests/pytests/unit/utils/test_crypt.py
Labels: Phosphorus v3005.0

#61158 Fix test cases with PermissionError on /var/cache/salt
  tests/pytests/unit/state/test_state_compiler.py
  tests/pytests/unit/test_minion.py
Labels: Phosphorus v3005.0

#61442 Uses only LVM command's stdout to populate lvm grain
  changelog/61412.fixed
  salt/grains/lvm.py
  tests/unit/grains/test_lvm.py
Labels: Phosphorus v3005.0

#61383 Use "net" instead of "sc" to restart minion service
  changelog/61413.fixed
  salt/utils/cloud.py
Labels: Phosphorus v3005.0

#60727 Update formulas.rst to reference LogBot archives
  doc/topics/development/conventions/formulas.rst
Labels: Documentation, doc-correction

#55720 attempt at fixing 25721 on master
  changelog/25721.fixed
  requirements/pytest.txt
  requirements/static/ci/py3.10/cloud.txt
  requirements/static/ci/py3.10/darwin.txt
  requirements/static/ci/py3.10/freebsd.txt
  requirements/static/ci/py3.10/linux.txt
  requirements/static/ci/py3.5/linux.txt
  requirements/static/ci/py3.6/cloud.txt
  requirements/static/ci/py3.6/linux.txt
  requirements/static/ci/py3.7/cloud.txt
  requirements/static/ci/py3.7/darwin.txt
  requirements/static/ci/py3.7/freebsd.txt
  requirements/static/ci/py3.7/linux.txt
  requirements/static/ci/py3.7/windows.txt
  requirements/static/ci/py3.8/cloud.txt
  requirements/static/ci/py3.8/darwin.txt
  requirements/static/ci/py3.8/freebsd.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.8/windows.txt
  requirements/static/ci/py3.9/cloud.txt
  requirements/static/ci/py3.9/darwin.txt
  requirements/static/ci/py3.9/freebsd.txt
  requirements/static/ci/py3.9/linux.txt
  requirements/static/ci/py3.9/windows.txt
  salt/client/ssh/shell.py
  tests/integration/ssh/test_raw.py
Labels: master-port, Phosphorus v3005.0

#61441 Remove case sensitivity of Etag header for use_etag
  changelog/61440.fixed
  salt/fileclient.py
  tests/pytests/functional/states/test_file.py
Labels: Phosphorus v3005.0

#61491 Updates file.absent documentation to include details on how to clear contents of directory
  salt/states/file.py
Labels: Phosphorus v3005.0

#58101 [merge jam] Master port 49261 - consul modules
  changelog/58101.added
  doc/ref/states/all/index.rst
  doc/ref/states/all/salt.states.consul.rst
  salt/modules/consul.py
  salt/states/consul.py
  tests/pytests/unit/modules/test_consul.py
  tests/pytests/unit/states/test_consul.py
Labels: master-port, Phosphorus v3005.0

#60739 VMware expanded virtual hardware features
  changelog/56144.added
  doc/topics/cloud/vmware.rst
  salt/cloud/clouds/vmware.py
Labels: Phosphorus v3005.0

#61536 Remove 40 character limit to update Title
  changelog/61533.fixed
  salt/states/win_wua.py
  tests/pytests/unit/states/test_win_wua.py
Labels: Phosphorus v3005.0

#61467 Fake /proc/1/cgroups for Xen-Test running in kubernetes
  tests/pytests/unit/grains/test_core.py
Labels: Phosphorus v3005.0

#61539 Update sysctl docs to clarify value arg
  salt/states/sysctl.py
Labels: Phosphorus v3005.0
