Repository saltstack/salt, pull requests merged in 2022-12, with the labels that each got.

#63050 Add option to enable/disable netapi clients
  changelog/63050.changed
  conf/master
  doc/ref/configuration/master.rst
  doc/topics/netapi/index.rst
  doc/topics/releases/3006.rst
  salt/config/__init__.py
  salt/netapi/__init__.py
  tests/pytests/functional/netapi/rest_cherrypy/conftest.py
  tests/pytests/functional/netapi/rest_tornado/conftest.py
  tests/pytests/integration/netapi/rest_cherrypy/conftest.py
  tests/pytests/integration/netapi/rest_tornado/conftest.py
  tests/pytests/integration/netapi/test_client.py
  tests/pytests/integration/netapi/test_ssh_client.py
Labels: has-failing-test, Sulfur v3006.0

#63132 Add boardname grain
  changelog/63131.added
  salt/grains/core.py
  tests/pytests/unit/grains/test_core.py
Labels: Sulfur v3006.0

#63211 Also skip the same tests on AlmaLinux 9
  tests/integration/pillar/test_git_pillar.py
Labels: Sulfur v3006.0

#63135 remove boto dependency from boto3mod
  changelog/62672.fixed
  salt/utils/boto3mod.py
Labels: Sulfur v3006.0

#63184 Explicity pass context for salt-ssh state calls
  changelog/60003.fixed
  salt/client/ssh/wrapper/state.py
  salt/state.py
  tests/pytests/integration/ssh/test_state.py
Labels: Sulfur v3006.0

#62868 Add onchange configuration for script engine
  changelog/62867.added
  salt/engines/script.py
  tests/pytests/unit/engines/test_script.py
Labels: Sulfur v3006.0

#58987 Extend OpenVSwitch modules
  changelog/58986.added
  doc/ref/states/all/index.rst
  doc/ref/states/all/salt.states.openvswitch_db.rst
  salt/modules/openvswitch.py
  salt/states/openvswitch_bridge.py
  salt/states/openvswitch_db.py
  tests/pytests/unit/modules/test_openvswitch.py
  tests/pytests/unit/states/test_openvswitch_bridge.py
  tests/pytests/unit/states/test_openvswitch_db.py
Labels: Sulfur v3006.0

#63284 Bump to `certifi>=2022.12.7`
  requirements/static/ci/common.in
  requirements/static/ci/py3.10/cloud.txt
  requirements/static/ci/py3.10/darwin.txt
  requirements/static/ci/py3.10/docs.txt
  requirements/static/ci/py3.10/freebsd.txt
  requirements/static/ci/py3.10/lint.txt
  requirements/static/ci/py3.10/linux.txt
  requirements/static/ci/py3.10/windows.txt
  requirements/static/ci/py3.6/cloud.txt
  requirements/static/ci/py3.6/docs.txt
  requirements/static/ci/py3.6/lint.txt
  requirements/static/ci/py3.6/linux.txt
  requirements/static/ci/py3.7/cloud.txt
  requirements/static/ci/py3.7/docs.txt
  requirements/static/ci/py3.7/freebsd.txt
  requirements/static/ci/py3.7/lint.txt
  requirements/static/ci/py3.7/linux.txt
  requirements/static/ci/py3.7/windows.txt
  requirements/static/ci/py3.8/cloud.txt
  requirements/static/ci/py3.8/docs.txt
  requirements/static/ci/py3.8/freebsd.txt
  requirements/static/ci/py3.8/lint.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.8/windows.txt
  requirements/static/ci/py3.9/cloud.txt
  requirements/static/ci/py3.9/darwin.txt
  requirements/static/ci/py3.9/docs.txt
  requirements/static/ci/py3.9/freebsd.txt
  requirements/static/ci/py3.9/lint.txt
  requirements/static/ci/py3.9/linux.txt
  requirements/static/ci/py3.9/windows.txt
Labels: Sulfur v3006.0

#63295 Bump to `certifi>=2022.12.7`
  requirements/static/pkg/py3.10/darwin.txt
  requirements/static/pkg/py3.10/freebsd.txt
  requirements/static/pkg/py3.10/linux.txt
  requirements/static/pkg/py3.10/windows.txt
  requirements/static/pkg/py3.6/linux.txt
  requirements/static/pkg/py3.7/freebsd.txt
  requirements/static/pkg/py3.7/linux.txt
  requirements/static/pkg/py3.7/windows.txt
  requirements/static/pkg/py3.8/freebsd.txt
  requirements/static/pkg/py3.8/linux.txt
  requirements/static/pkg/py3.8/windows.txt
  requirements/static/pkg/py3.9/darwin.txt
  requirements/static/pkg/py3.9/freebsd.txt
  requirements/static/pkg/py3.9/linux.txt
  requirements/static/pkg/py3.9/windows.txt
  requirements/windows.txt
Labels: Sulfur v3006.0

#63067 Support IMDSv2 HttpTokens
  changelog/63067.added
  salt/utils/aws.py
  tests/pytests/unit/utils/test_aws.py
Labels: Needs-Testcase

#63290 Update python to 3.10.9 in MacOS
  pkg/osx/build_python.sh
Labels: Sulfur v3006.0

#63023 Remove uneeded binaries from Windows
  setup.py
Labels: Sulfur v3006.0

#63343 Update year in license, remove shasum directory
  pkg/osx/pkg-resources/license.rtf
  pkg/osx/pkg-resources/welcome_py2.rtf
  pkg/osx/shasums/libsodium-1.0.18.tar.gz.sha512
  pkg/osx/shasums/readme.md
  pkg/osx/shasums/zeromq-4.3.4.tar.gz.sha512
Labels: Sulfur v3006.0

#63342 Update license to 2023
  pkg/windows/installer/LICENSE.txt
Labels: Sulfur v3006.0

#63352 Import StrictVersion and LooseVersion from setuptools.distutils.verison or setuptools._distutils.version
  changelog/63350.fixed
  salt/utils/pkg/win.py
  salt/utils/versions.py
Labels: Sulfur v3006.0

#63365 Fix x509 execution module virtual func
  salt/modules/x509.py
Labels: Sulfur v3006.0

#63381 Implement `exec_module` to remove the deprecation warnings from output
  salt/__init__.py
Labels: Sulfur v3006.0

#63380 Account for `features` being `None`
  salt/modules/x509.py
  salt/modules/x509_v2.py
Labels: Sulfur v3006.0

#63389 The `TestGitPython*HTTP` and `TestPygit2*HTTP` tests now use a container
  tests/integration/files/file/base/git_pillar/http/files/nginx.conf
  tests/integration/files/file/base/git_pillar/http/files/users
  tests/integration/files/file/base/git_pillar/http/files/uwsgi.yml
  tests/integration/files/file/base/git_pillar/http/nginx.sls
  tests/integration/files/file/base/git_pillar/http/uwsgi.sls
  tests/integration/pillar/test_git_pillar.py
  tests/support/gitfs.py
Labels: Sulfur v3006.0

#63394 Bump to `gitpython==3.1.30` because of https://github.com/advisories/GHSA-hcpj-qp55-gfph
  requirements/darwin.txt
  requirements/static/ci/common.in
  requirements/static/ci/py3.10/cloud.txt
  requirements/static/ci/py3.10/darwin.txt
  requirements/static/ci/py3.10/docs.txt
  requirements/static/ci/py3.10/freebsd.txt
  requirements/static/ci/py3.10/lint.txt
  requirements/static/ci/py3.10/linux.txt
  requirements/static/ci/py3.10/windows.txt
  requirements/static/ci/py3.6/cloud.txt
  requirements/static/ci/py3.6/docs.txt
  requirements/static/ci/py3.6/lint.txt
  requirements/static/ci/py3.6/linux.txt
  requirements/static/ci/py3.7/cloud.txt
  requirements/static/ci/py3.7/docs.txt
  requirements/static/ci/py3.7/freebsd.txt
  requirements/static/ci/py3.7/lint.txt
  requirements/static/ci/py3.7/linux.txt
  requirements/static/ci/py3.7/windows.txt
  requirements/static/ci/py3.8/cloud.txt
  requirements/static/ci/py3.8/docs.txt
  requirements/static/ci/py3.8/freebsd.txt
  requirements/static/ci/py3.8/lint.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.8/windows.txt
  requirements/static/ci/py3.9/cloud.txt
  requirements/static/ci/py3.9/darwin.txt
  requirements/static/ci/py3.9/docs.txt
  requirements/static/ci/py3.9/freebsd.txt
  requirements/static/ci/py3.9/lint.txt
  requirements/static/ci/py3.9/linux.txt
  requirements/static/ci/py3.9/windows.txt
  requirements/static/pkg/py3.10/darwin.txt
  requirements/static/pkg/py3.10/windows.txt
  requirements/static/pkg/py3.6/linux.txt
  requirements/static/pkg/py3.7/windows.txt
  requirements/static/pkg/py3.8/windows.txt
  requirements/static/pkg/py3.9/darwin.txt
  requirements/static/pkg/py3.9/windows.txt
  requirements/windows.txt
Labels: Sulfur v3006.0
