Repository saltstack/salt, pull requests merged in 2023-05, with the labels that each got.

#64048 [master] remove dead line
  salt/matchers/compound_match.py
  salt/matchers/nodegroup_match.py
  salt/modules/match.py
Labels: backport:3006.x

#64176 [3006.x] saltutil.refresh_grains(clean_pillar_cache=False)
  changelog/64081.fixed.md
  conf/master
  conf/suse/master
  doc/ref/configuration/master.rst
  pkg/common/conf/master
  salt/modules/saltutil.py
  tests/pytests/unit/modules/test_saltutil.py
Labels: Sulfur v3006.1

#63876 Update `py` renderer documentation with information on user-provideded context
  salt/renderers/py.py
Labels: Documentation

#64101 [master] dec doc m
  CONTRIBUTING.rst
  doc/topics/tutorials/writing_tests.rst
Labels: Documentation

#64119 [master] docs: small fixes for transactional update module
  salt/modules/transactional_update.py
Labels: Documentation, backport:3006.x

#63168 Add `signed_by_[any|all]` parameters to `gpg.verify`
  changelog/63166.added.md
  salt/modules/gpg.py
  tests/pytests/functional/modules/test_gpg.py
Labels: Chlorine v3007.0

#64210 [master] corrected misleading comment
  salt/utils/find.py
Labels: Chlorine v3007.0

#64085 [Documentation] linux_acl: Add warning about effective rights mask
  salt/states/linux_acl.py
Labels: Documentation, Chlorine v3007.0, backport:3006.x

#64337 [3006.x] Fix 64169 lint error
  tests/pytests/unit/states/test_pip.py
Labels: Sulfur v3006.2

#64375 [master] Removed the broken link in modules.win_path
  salt/modules/win_path.py
Labels: Documentation

#64049 [master] Update docstring for an outdated URL
  salt/modules/ps.py
Labels: Documentation, backport:3006.x
