Repository saltstack/salt, pull requests merged in 2023-04, with the labels that each got.

#63983 [master] Fix aptpkg.latest_version calls apt-cache too much
  changelog/63982.fixed.md
  salt/modules/aptpkg.py
  tests/pytests/unit/modules/test_aptpkg.py
Labels: Chlorine v3007.0

#63911 fix: lxd remove outdated monkey patch
  changelog/59514.fixed.md
  salt/modules/lxd.py
Labels: Chlorine v3007.0

#64038 [3006.x] Populate user data / name within runners and for runner events on the event bus
  changelog/63148.fixed.md
  salt/client/mixins.py
  salt/modules/saltutil.py
  salt/runners/state.py
  salt/state.py
  salt/states/saltmod.py
  tests/pytests/integration/runners/state/orchestrate/test_events.py
Labels: Sulfur v3006.0

#64065 [3006.x] Test removing epoch from deb versions
  tools/changelog.py
Labels: Sulfur v3006.0

#64050 [3006.x] Bump pyzmq to 25.0.2 on Windows
  requirements/static/ci/py3.10/pkgtests-windows.txt
  requirements/static/ci/py3.10/pkgtests.txt
  requirements/static/ci/py3.10/windows.txt
  requirements/static/ci/py3.7/windows.txt
  requirements/static/ci/py3.8/windows.txt
  requirements/static/ci/py3.9/windows.txt
  requirements/static/pkg/py3.10/windows.txt
  requirements/static/pkg/py3.7/windows.txt
  requirements/static/pkg/py3.8/windows.txt
  requirements/static/pkg/py3.9/windows.txt
  requirements/zeromq.txt
Labels: Sulfur v3006.0

#64084 [3006.x] Add docs for new salt user for linux packages
  doc/topics/releases/templates/3006.0.md.template
Labels: Sulfur v3006.0

#64087 [3006.x] Add release note about salt-pip
  doc/topics/releases/templates/3006.0.md.template
Labels: Sulfur v3006.0

#64097 [3006.x] Add back ssm.exe. It is needed for VMtools
  pkg/windows/prep_salt.ps1
  tools/pkg/__init__.py
Labels: Sulfur v3006.0

#63818 Change saltenv description
  doc/ref/configuration/minion.rst
Labels: Documentation

#63723 [DOCS] Fix typo "occurence" -> "occurrence" in ps module
  salt/modules/ps.py
Labels: Documentation

#63712 [DOCS] Fix a small typo in `CONTRIBUTING.rst`.
  CONTRIBUTING.rst
Labels: Documentation

#64149 [DOCS] service state and module docs do not mention that systemd daemon is reloaded
  salt/states/service.py
Labels: Documentation, Sulfur v3006.1

#64146 [3006.x] Merge pull request #63818 from OrangeDog/patch-12
  doc/ref/configuration/minion.rst
Labels: Documentation, Sulfur v3006.1

#64147 [3006.x] Merge pull request #63723 from joshmcorreia/patch-2
  salt/modules/ps.py
Labels: Documentation, Sulfur v3006.1

#64148 [3006.x] Merge pull request #63712 from Airtonomy/fix-typo
  CONTRIBUTING.rst
Labels: Documentation, Sulfur v3006.1

#63702 [DOCS] Fix incorrect reactor target in documentation
  doc/topics/beacons/index.rst
Labels: Documentation

#64154 [3006.x] Fix incorrect reactor target
  doc/topics/beacons/index.rst
Labels: Sulfur v3006.1

#64165 [master] Add automated backports support
  .backportrc.json
  .github/workflows/backport.yml
Labels: backport:3006.x, backport:3005.x

#64173 [3006.x] Fix 64170
  changelog/64170.fixed.md
  salt/utils/cloud.py
  tests/pytests/unit/utils/test_cloud.py
Labels: Sulfur v3006.1

#64175 [3006.x] Fix various issues with lgpo_reg
  changelog/64126.fixed.md
  salt/modules/win_lgpo_reg.py
  salt/states/win_lgpo_reg.py
  salt/utils/win_lgpo_reg.py
  tests/pytests/unit/modules/test_win_lgpo_reg.py
  tests/pytests/unit/states/test_win_lgpo_reg.py
Labels: Sulfur v3006.1

#64134 Update the bootstrap script to v2023.04.26
  salt/cloud/deploy/bootstrap-salt.sh
Labels: backport:3006.x

#64191 [3006.x] Fix to cloud.run_profile when show_deploy_args is False
  changelog/61236.fixed.md
  salt/cloud/__init__.py
  tests/pytests/unit/cloud/test_cloud.py
Labels: Sulfur v3006.1

#64188 [3006.x] Add support for test=True to file.cached
  changelog/63785.fixed.md
  salt/states/file.py
  tests/pytests/functional/states/file/test_cached.py
Labels: Sulfur v3006.1

#64187 [3006.x] Lower y
  CONTRIBUTING.rst
  doc/topics/tutorials/writing_tests.rst
Labels: Documentation
