Repository saltstack/salt, pull requests merged in 2023-12, with the labels that each got.

#64636 [master] Revamped Windows package manager documentation
  doc/topics/releases/2015.8.0.rst
  doc/topics/windows/windows-package-manager.rst
Labels: Documentation, Chlorine v3007.0, backport:3006.x

#65659 [3006.x] Stop trying when codecov replies with `Too many uploads to this commit`
  tools/ci.py
Labels: test:coverage

#65678 [master] Bump cache seed
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/scheduled.yml
  .github/workflows/staging.yml
  .github/workflows/templates/layout.yml.jinja
Labels: test:full

#53338 [master]Modular Systems: Document saltenvs and modules
  doc/topics/development/modules/index.rst
Labels: Reviewers-Assigned

#65228 [master] Fix cluster key rotation
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/scheduled.yml
  .github/workflows/staging.yml
  .github/workflows/templates/layout.yml.jinja
  salt/channel/server.py
  salt/crypt.py
  salt/master.py
  tests/pytests/integration/cluster/__init__.py
  tests/pytests/integration/cluster/conftest.py
  tests/pytests/integration/cluster/test_basic_cluster.py
  tests/pytests/scenarios/cluster/conftest.py
  tests/pytests/scenarios/cluster/test_cluster.py
  tests/pytests/unit/modules/test_saltutil.py
  tests/pytests/unit/test_crypt.py
  tests/pytests/unit/test_master.py
Labels: Chlorine v3007.0, test:full

#59045 modules.system: document platform support for "reboot witnessed" functions
  salt/modules/system.py
Labels: Documentation

#65675 [master] add documentation for facl defaults, in acl state
  salt/states/linux_acl.py
Labels: Documentation

#62299 doc: gitfs_remotes provide additional ordering information
  doc/topics/tutorials/gitfs.rst
Labels: Documentation

#65683 [master] Update documentation of encoding kwarg
  salt/states/postgres_database.py
Labels: Documentation

#65684 [master] Fix wheel key.key_str usage example
  salt/wheel/key.py
Labels: Documentation

#65351 [master] Add fallback for when "remounting" NFS or FUSE initially fails
  changelog/18907.fixed.md
  salt/modules/mount.py
  salt/states/mount.py
  tests/pytests/unit/modules/test_mount.py
  tests/pytests/unit/states/test_mount.py
Labels: Chlorine v3007.0

#64221 [master] doc: Fix incorrect mentioning systemd.scope in states.pkg
  salt/states/pkg.py
Labels: Documentation

#65687 [master] Fix extfs parameter and retcode handling
  changelog/51858.fixed.md
  changelog/54426.fixed.md
  changelog/65686.fixed.md
  salt/modules/extfs.py
  tests/pytests/unit/modules/test_extfs.py
Labels: Chlorine v3007.0

#65596 [3006.x] Fix an issue with the openscap module
  changelog/65193.fixed.md
  salt/modules/openscap.py
  tests/pytests/unit/modules/test_openscap.py
  tests/unit/modules/test_openscap.py
Labels: Sulfur v3006.6

#65676 [3006.x] Stop importing salt in `tools/`
  requirements/static/ci/py3.10/tools-virustotal.txt
  requirements/static/ci/py3.10/tools.txt
  requirements/static/ci/py3.11/tools-virustotal.txt
  requirements/static/ci/py3.11/tools.txt
  requirements/static/ci/py3.12/tools-virustotal.txt
  requirements/static/ci/py3.12/tools.txt
  requirements/static/ci/py3.9/tools-virustotal.txt
  requirements/static/ci/py3.9/tools.txt
  requirements/static/ci/tools-virustotal.in
  requirements/static/ci/tools.in
  salt/version.py
  tools/__init__.py
  tools/precommit/docstrings.py
Labels: Sulfur v3006.6

#65407 [3006.x] Additional test cases for slsutil
  salt/modules/slsutil.py
  tests/pytests/unit/modules/test_slsutil.py
Labels: test:full, test:coverage, Sulfur v3006.6

#63484 migrate test_tomcat to pytest
  tests/pytests/unit/modules/test_tomcat.py
  tests/unit/modules/test_tomcat.py
Labels: Sulfur v3006.6

#65712 [master] Fix cluster test flakiness
  salt/master.py
  salt/utils/event.py
  tests/pytests/integration/cluster/conftest.py
  tests/pytests/integration/cluster/test_basic_cluster.py
  tests/pytests/scenarios/cluster/test_cluster.py
Labels: test:full, test:pkg

#58044 [PR port] Port #47835 - Add password support to Redis returner
  changelog/58044.added.md
  salt/returners/redis_return.py
  tests/pytests/unit/returners/test_redis_return.py
Labels: master-port

#65716 [master] Merge forward 3006.x
  salt/modules/mac_assistive.py
  salt/modules/slsutil.py
  tests/pytests/integration/minion/test_return_retries.py
  tests/pytests/pkg/download/test_pkg_download.py
  tests/pytests/unit/conftest.py
  tests/pytests/unit/modules/test_slsutil.py
  tests/pytests/unit/modules/test_tomcat.py
  tests/pytests/unit/states/test_grains.py
  tests/unit/modules/test_tomcat.py
  tests/unit/states/test_grains.py
  tools/pkg/repo/create.py
Labels: test:full, test:pkg

#65286 [master] Remove warning that related to now-unsupported systems
  salt/states/augeas.py
Labels: Documentation

#65347 [master] Document parameters in modules.disk
  salt/modules/disk.py
Labels: Documentation

#65201 [master] Fix documentation of file.prepend
  salt/states/file.py
Labels: Documentation

#63736 sdb doc example subkeys
  doc/topics/sdb/index.rst
Labels: Documentation, pending-changes, Chlorine v3007.0

#64908 [master] fixes saltstack#53120 State firewalld.present disables masquerade when making unrelated changes
  changelog/53120.changed.md
  salt/states/firewalld.py
  tests/pytests/unit/states/test_firewalld.py
Labels: Chlorine v3007.0

#58474 Remove duplicatated code
  salt/netapi/rest_cherrypy/app.py
Labels: Needs-Testcase

#65747 [master] Merge forward from 3006.x
  changelog/65691.fixed.md
  changelog/65692.fixed.md
  salt/fileclient.py
  salt/loader/__init__.py
  salt/loader/context.py
  salt/minion.py
  salt/utils/extmods.py
  tests/pytests/integration/cli/test_matcher.py
  tests/pytests/integration/cli/test_salt_call.py
  tests/pytests/integration/minion/test_return_retries.py
  tests/pytests/integration/netapi/test_ssh_client.py
  tests/pytests/scenarios/multimaster/beacons/test_inotify.py
  tests/pytests/unit/loader/test_loader.py
  tests/pytests/unit/loader/test_loading_modules.py
  tools/pkg/repo/create.py
Labels: test:full, test:pkg

#65758 [master] Revert test changes and fix original tests
  salt/client/ssh/wrapper/__init__.py
  tests/filename_map.yml
  tests/pytests/integration/netapi/test_ssh_client.py
Labels: test:core, test:slow
