Repository saltstack/salt, pull requests merged in 2023-06, with the labels that each got.

#64421 [master] Fix 'unable to unmount' failure to return False result instead of None
  changelog/64420.fixed.md
  salt/states/mount.py
  tests/pytests/unit/states/test_mount.py
Labels: Chlorine v3007.0

#60278 DOC Update walkthrough_macosx.rst
  doc/topics/tutorials/walkthrough_macosx.rst
Labels: Documentation, doc-correction, Chlorine v3007.0

#58089 [PR port] Port #54047 - auth: correct typos in docstrings
  changelog/54047.fixed
Labels: Documentation, master-port

#64300 [master] Fix utf8 handling in 'pass' renderer and make it more robust
  changelog/64300.fixed.md
  salt/renderers/pass.py
  tests/pytests/unit/renderers/test_pass.py
Labels: Chlorine v3007.0, backport:3006.x

#64419 [master] Add ability to return False result in test mode of configurable_test_state
  changelog/64418.added.md
  salt/states/test.py
  tests/pytests/unit/states/test_test.py
Labels: Chlorine v3007.0

#64436 [3006.x] Fix `versionadded` and/or `versionchanged` versions in docstrings
  .pre-commit-config.yaml
  salt/_logging/handlers.py
  salt/cache/consul.py
  salt/client/ssh/wrapper/pillar.py
  salt/cloud/clouds/clc.py
  salt/grains/metadata_gce.py
  salt/modules/acme.py
  salt/modules/aptpkg.py
  salt/modules/git.py
  salt/modules/mod_random.py
  salt/modules/openvswitch.py
  salt/modules/pillar.py
  salt/modules/rh_service.py
  salt/modules/sysmod.py
  salt/modules/win_system.py
  salt/modules/yumpkg.py
  salt/modules/zabbix.py
  salt/pillar/netbox.py
  salt/runners/state.py
  salt/states/acme.py
  salt/states/apache.py
  salt/states/file.py
  salt/states/lvm.py
  salt/states/openvswitch_bridge.py
  salt/states/openvswitch_db.py
  salt/states/pcs.py
  salt/states/zabbix_action.py
  salt/states/zabbix_template.py
  salt/states/zabbix_valuemap.py
Labels: Documentation

#64257 [master] Fix 64256: Add flags to create local users and groups
  changelog/64256.added.md
  salt/modules/groupadd.py
  salt/modules/useradd.py
  salt/states/group.py
  salt/states/user.py
  tests/pytests/unit/modules/test_groupadd.py
  tests/pytests/unit/modules/test_useradd.py
  tests/pytests/unit/states/test_group.py
Labels: Chlorine v3007.0

#64440 [master] fix: slack bolt engine name is slack_bolt
  salt/engines/slack_bolt_engine.py
Labels: Documentation

#64262 [master] Fix 64260: Remove `isfile` check to increase speed of listing large numbers of keys
  changelog/64260.fixed.md
  salt/key.py
  salt/master.py
  salt/utils/minions.py
  tests/pytests/integration/cli/test_matcher.py
  tests/pytests/integration/cli/test_salt_key.py
Labels: Chlorine v3007.0

#63897 Document pip.installed pkgs parameter
  salt/states/pip_state.py
Labels: Documentation, Chlorine v3007.0

#63993 [master] Fix 63991: Add option to use a fresh connection for mysql cache
  changelog/63991.fixed.md
  salt/cache/mysql_cache.py
  tests/pytests/unit/cache/test_mysql_cache.py
Labels: Chlorine v3007.0

#64028 [master] file.keyvalue should allow creating a file if it doesn't exist
  changelog/63545.added.md
  salt/states/file.py
  tests/pytests/unit/states/file/test_keyvalue.py
Labels: Chlorine v3007.0

#64478 [3006.x] fix regression where file.symlink will not replace/update existing symlink
  changelog/64477.fixed.md
  salt/states/file.py
  tests/pytests/functional/states/test_file.py
Labels: Sulfur v3006.2

#64471 [master]gpg_decrypt_must_succeed default from False to True
  changelog/64462.changed.md
  salt/config/__init__.py
  salt/renderers/gpg.py
Labels: Chlorine v3007.0

#64527 [3006.x] More nightly build fixes
  tests/pytests/unit/client/ssh/test_password.py
  tests/pytests/unit/client/ssh/test_return_events.py
Labels: test:core, test:slow

#64540 [3006.x] nightly fix
  tests/support/case.py
Labels: Tests, test-fix, test:core, test:slow

#64537 [master] Fix incorrect usage of "finite" wrt ordering
  doc/ref/states/ordering.rst
Labels: Documentation

#64528 [master] Structured Layered State name added insted of SaLt State file
  doc/topics/tutorials/starting_states.rst
Labels: Documentation

#64548 [3006.x] fix nightlies by unbreaking runner.run.
  salt/cli/run.py
  salt/runner.py
  tests/support/case.py
Labels: test-fix, test:core, test:slow

#64466 [master] Remove salt.modules.napalm_mod.netmiko_conn and pyeapi_conn
  changelog/64460.removed.md
  salt/modules/napalm_mod.py
Labels: has-failing-test, Chlorine v3007.0

#64560 [master] Merge 3006.x into master
  .github/actions/get-pull-labels/action.yml
  .github/actions/get-pull-number/action.yml
  .github/actions/get-pull-request/action.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/scheduled.yml
  .github/workflows/staging.yml
  .github/workflows/templates/ci.yml.jinja
  .github/workflows/templates/layout.yml.jinja
  .github/workflows/templates/test-salt.yml.jinja
  .github/workflows/test-action-macos.yml
  .github/workflows/test-action.yml
  .github/workflows/test-package-downloads-action-linux.yml
  .github/workflows/test-package-downloads-action-macos.yml
  .github/workflows/test-package-downloads-action-windows.yml
  .github/workflows/test-packages-action-macos.yml
  .github/workflows/test-packages-action.yml
  changelog/58667.fixed.md
  changelog/61173.fixed.md
  changelog/64211.fixed.md
  changelog/64439.added.md
  changelog/64514.fixed.md
  changelog/64539.fixed.md
  changelog/64547.added.md
  changelog/64553.changed.md
  changelog/64553.removed.md
  doc/topics/windows/multi-minion.rst
  pkg/tests/integration/test_multi_minion.py
  pkg/windows/clean.ps1
  pkg/windows/multi-minion.cmd
  pkg/windows/multi-minion.ps1
  pkg/windows/prep_salt.ps1
  salt/cli/run.py
  salt/client/mixins.py
  salt/client/ssh/__init__.py
  salt/client/ssh/wrapper/state.py
  salt/modules/aptpkg.py
  salt/runner.py
  salt/states/user.py
  tests/pytests/functional/cli/test_salt_run_.py
  tests/pytests/functional/modules/test_aptpkg.py
  tests/pytests/functional/states/test_user.py
  tests/pytests/integration/reactor/test_reactor.py
  tests/pytests/integration/ssh/test_deploy.py
  tests/pytests/integration/ssh/test_state.py
  tests/pytests/unit/client/ssh/test_password.py
  tests/pytests/unit/client/ssh/test_return_events.py
  tests/pytests/unit/states/test_user.py
  tools/ci.py
Labels: test:full

#64555 [master] Master branch slowdown
  changelog/64457.changed.md
  salt/__init__.py
  salt/client/ssh/ssh_py_shim.py
  salt/grains/core.py
  salt/utils/locales.py
Labels: test:full

#64574 [master] Merge 3006.x into master
  changelog/64565.changed.md
  tests/conftest.py
  tests/pytests/functional/modules/state/requisites/test_mixed.py
  tests/pytests/functional/modules/state/requisites/test_require.py
  tests/pytests/functional/modules/state/requisites/test_watch.py
  tests/pytests/functional/modules/state/test_state.py
  tests/pytests/integration/cli/test_salt.py
  tests/pytests/integration/cli/test_salt_cp.py
  tests/pytests/integration/cli/test_salt_deltaproxy.py
  tests/pytests/integration/modules/state/test_state_pillar_errors.py
  tests/pytests/integration/runners/test_saltutil.py
  tests/pytests/integration/states/test_file.py
  tests/pytests/unit/state/test_state_compiler.py
  tests/pytests/unit/state/test_state_format_slots.py
Labels: test:full
