Repository saltstack/salt, pull requests merged in 2023-07, with the labels that each got.

#64579 [master] Update the bootstrap script to v2023.06.28
  salt/cloud/deploy/bootstrap-salt.sh
Labels: backport:3006.x

#64571 [3006.x] Fix an issue caching the installer when version=latest
  changelog/64519.fixed.md
  salt/modules/win_pkg.py
  tests/pytests/unit/modules/test_win_pkg.py
Labels: Sulfur v3006.2

#64573 Revert to Py3.10
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/scheduled.yml
  .github/workflows/staging.yml
  cicd/shared-gh-workflows-context.yml
Labels: test:full

#64608 [3006.x] Allow forcing the package tests to run by the `test:pkg` label
  tools/ci.py
Labels: test:pkg

#64609 [master] Merge 3006.x into master
  .github/actions/setup-python-tools-scripts/action.yml
  .github/workflows/build-deb-packages.yml
  changelog/64519.fixed.md
  changelog/64595.security.md
  requirements/darwin.txt
  requirements/static/ci/py3.10/cloud.txt
  requirements/static/ci/py3.10/darwin.txt
  requirements/static/ci/py3.10/linux.txt
  requirements/static/ci/py3.10/windows.txt
  requirements/static/ci/py3.11/cloud.txt
  requirements/static/ci/py3.11/darwin.txt
  requirements/static/ci/py3.11/linux.txt
  requirements/static/ci/py3.11/windows.txt
  requirements/static/ci/py3.8/cloud.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.8/windows.txt
  requirements/static/ci/py3.9/cloud.txt
  requirements/static/ci/py3.9/darwin.txt
  requirements/static/ci/py3.9/linux.txt
  requirements/static/ci/py3.9/windows.txt
  requirements/static/pkg/linux.in
  requirements/static/pkg/py3.10/darwin.txt
  requirements/static/pkg/py3.10/linux.txt
  requirements/static/pkg/py3.10/windows.txt
  requirements/static/pkg/py3.11/darwin.txt
  requirements/static/pkg/py3.11/linux.txt
  requirements/static/pkg/py3.11/windows.txt
  requirements/static/pkg/py3.8/linux.txt
  requirements/static/pkg/py3.8/windows.txt
  requirements/static/pkg/py3.9/darwin.txt
  requirements/static/pkg/py3.9/linux.txt
  requirements/static/pkg/py3.9/windows.txt
  requirements/windows.txt
  salt/modules/win_pkg.py
  tests/pytests/unit/modules/test_win_pkg.py
Labels: test:full

#64616 [3006.x] Allow randomizing the GH Actions cache seed value by setting the `test:random-cache-seed` label
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/scheduled.yml
  .github/workflows/staging.yml
  .github/workflows/templates/layout.yml.jinja
  tools/ci.py
Labels: test:random-cache-seed

#64652 [master] Merge 3006.x into master
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/scheduled.yml
  .github/workflows/staging.yml
  .github/workflows/templates/layout.yml.jinja
  changelog/64398.fixed.md
  changelog/64657.changed.md
  requirements/darwin.txt
  requirements/static/ci/py3.10/cloud.txt
  requirements/static/ci/py3.10/darwin.txt
  requirements/static/ci/py3.10/freebsd.txt
  requirements/static/ci/py3.10/linux.txt
  requirements/static/ci/py3.10/windows.txt
  requirements/static/ci/py3.11/cloud.txt
  requirements/static/ci/py3.11/darwin.txt
  requirements/static/ci/py3.11/freebsd.txt
  requirements/static/ci/py3.11/linux.txt
  requirements/static/ci/py3.11/windows.txt
  requirements/static/ci/py3.8/cloud.txt
  requirements/static/ci/py3.8/freebsd.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.8/windows.txt
  requirements/static/ci/py3.9/cloud.txt
  requirements/static/ci/py3.9/darwin.txt
  requirements/static/ci/py3.9/freebsd.txt
  requirements/static/ci/py3.9/linux.txt
  requirements/static/ci/py3.9/windows.txt
  requirements/static/pkg/linux.in
  requirements/static/pkg/py3.10/darwin.txt
  requirements/static/pkg/py3.10/freebsd.txt
  requirements/static/pkg/py3.10/linux.txt
  requirements/static/pkg/py3.10/windows.txt
  requirements/static/pkg/py3.11/darwin.txt
  requirements/static/pkg/py3.11/freebsd.txt
  requirements/static/pkg/py3.11/linux.txt
  requirements/static/pkg/py3.11/windows.txt
  requirements/static/pkg/py3.8/freebsd.txt
  requirements/static/pkg/py3.8/linux.txt
  requirements/static/pkg/py3.8/windows.txt
  requirements/static/pkg/py3.9/darwin.txt
  requirements/static/pkg/py3.9/freebsd.txt
  requirements/static/pkg/py3.9/linux.txt
  requirements/static/pkg/py3.9/windows.txt
  requirements/windows.txt
  salt/auth/__init__.py
  tests/pytests/unit/daemons/masterapi/test_local_funcs.py
  tools/ci.py
Labels: test:full

#64650 [3006.x] Clarify rejected_retry option docs
  doc/ref/configuration/minion.rst
Labels: Documentation

#64687 [3006.x] Bump to `aiohttp==3.8.5` due to https://github.com/advisories/GHSA-45c4-8wx5-qw6w
  changelog/64687.security.md
  requirements/static/ci/py3.10/cloud.txt
  requirements/static/ci/py3.10/darwin.txt
  requirements/static/ci/py3.10/freebsd.txt
  requirements/static/ci/py3.10/lint.txt
  requirements/static/ci/py3.10/linux.txt
  requirements/static/ci/py3.10/windows.txt
  requirements/static/ci/py3.7/cloud.txt
  requirements/static/ci/py3.7/freebsd.txt
  requirements/static/ci/py3.7/lint.txt
  requirements/static/ci/py3.7/linux.txt
  requirements/static/ci/py3.7/windows.txt
  requirements/static/ci/py3.8/cloud.txt
  requirements/static/ci/py3.8/freebsd.txt
  requirements/static/ci/py3.8/lint.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.8/windows.txt
  requirements/static/ci/py3.9/cloud.txt
  requirements/static/ci/py3.9/darwin.txt
  requirements/static/ci/py3.9/freebsd.txt
  requirements/static/ci/py3.9/lint.txt
  requirements/static/ci/py3.9/linux.txt
  requirements/static/ci/py3.9/windows.txt
Labels: Sulfur v3006.2

#64688 [master] Merge 3006.x into master
  .github/config.yml
  CONTRIBUTING.rst
  README.rst
  SUPPORT.rst
  changelog/64622.fixed.md
  changelog/64687.security.md
  doc/conf.py
  doc/ref/configuration/minion.rst
  requirements/static/ci/py3.10/darwin.txt
  requirements/static/ci/py3.10/freebsd.txt
  requirements/static/ci/py3.10/linux.txt
  requirements/static/ci/py3.10/windows.txt
  requirements/static/ci/py3.11/darwin.txt
  requirements/static/ci/py3.11/freebsd.txt
  requirements/static/ci/py3.11/linux.txt
  requirements/static/ci/py3.11/windows.txt
  requirements/static/ci/py3.8/freebsd.txt
  requirements/static/ci/py3.8/linux.txt
  requirements/static/ci/py3.8/windows.txt
  requirements/static/ci/py3.9/darwin.txt
  requirements/static/ci/py3.9/freebsd.txt
  requirements/static/ci/py3.9/linux.txt
  requirements/static/ci/py3.9/windows.txt
  salt/auth/__init__.py
  salt/modules/chocolatey.py
  tests/filename_map.yml
  tests/integration/modules/test_service.py
  tests/integration/states/test_service.py
  tests/pytests/functional/modules/test_service.py
  tests/pytests/functional/states/test_service.py
  tests/pytests/unit/modules/test_chocolatey.py
  tools/vm.py
Labels: test:full

#64719 [3006.x] Upgrade `relenv` to `0.13.2` and Python to `3.10.12`.
  .github/actions/setup-relenv/action.yml
  .github/workflows/build-deps-onedir.yml
  .github/workflows/build-salt-onedir.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/scheduled.yml
  .github/workflows/staging.yml
  changelog/64719.security.md
  cicd/shared-gh-workflows-context.yml
  pkg/macos/build_python.sh
  pkg/windows/build.ps1
  pkg/windows/build_python.ps1
Labels: test:full, test:pkg
