Repository saltstack/salt, pull requests merged in 2023-11, with the labels that each got.

#65500 [3006.x] The default timeout values are now passed as inputs
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/scheduled.yml
  .github/workflows/staging.yml
  .github/workflows/templates/test-salt.yml.jinja
  .github/workflows/test-action-macos.yml
  .github/workflows/test-action.yml
Labels: test:full

#65510 [3006.x] Adjust break in control file to 3006.4, for updated salt-common commit b3fcdf8
  pkg/debian/control
Labels: test:pkg

#65498 [3006.x] Ensure any pre-exiting incorrect ufw directory /etc/ufw/applications.dsalt-master removed
  pkg/debian/salt-master.preinst
Labels: test:pkg

#65416 [3006.x] Additional tests for http state
  tests/pytests/unit/states/test_http.py
Labels: test:full, test:coverage

#65298 [3006.x] Add some tests for client/__init__.py
  tests/pytests/unit/client/test_init.py
Labels: test:full, test:coverage

#65521 [master] Update the bootstrap script to v2023.11.07
  salt/cloud/deploy/bootstrap-salt.sh
Labels: backport:3006.x

#65552 [master] file.comment ignore_missing not working with multiline char
  changelog/65501.fixed.md
  salt/states/file.py
  tests/pytests/functional/states/file/test_comment.py
Labels: Chlorine v3007.0

#65221 [master] Add wildcard removal for aptpkg
  changelog/65220.added.md
  salt/modules/aptpkg.py
  salt/modules/yumpkg.py
  salt/utils/pkg/__init__.py
  tests/pytests/functional/modules/test_aptpkg.py
  tests/pytests/functional/modules/test_yumpkg.py
  tests/pytests/unit/utils/test_pkg.py
Labels: Chlorine v3007.0

#65566 [master] Deprecate Kubernetes modules for move to saltext-kubernetes
  changelog/65565.deprecated.md
  salt/modules/k8s.py
  salt/modules/kubeadm.py
  salt/modules/kubernetesmod.py
  salt/states/kubernetes.py
Labels: Chlorine v3007.0

#65560 [master] Move configuration index doc
  doc/ref/index.rst
  doc/topics/configuration/index.rst
Labels: Documentation

#65572 [master] Show warning on modules which are getting deprecated into extensions
  doc/conf.py
Labels: Documentation

#65539 [master] Fix service module does not handle enable/disable if systemd service is an alias
  changelog/63214.fixed.md
  salt/modules/systemd_service.py
  tests/pytests/unit/modules/test_systemd_service.py
  tests/unit/modules/test_systemd_service.py
Labels: Chlorine v3007.0

#65540 [master] nftables module typo does not ensure unique nft family values
  changelog/65295.fixed.md
  salt/modules/nftables.py
Labels: Chlorine v3007.0, backport:3006.x

#65576 [3006.x] CodeCov: LGPO
  tests/pytests/unit/modules/win_lgpo/test__policy_info.py
  tests/pytests/unit/modules/win_lgpo/test_adv_audit.py
  tests/pytests/unit/modules/win_lgpo/test_netsh.py
  tests/pytests/unit/modules/win_lgpo/test_policy_info.py
  tests/pytests/unit/modules/win_lgpo/test_reg_pol.py
  tests/pytests/unit/modules/win_lgpo/test_secedit.py
Labels: test:full, test:coverage

#65571 [master] Missing versionadded tag for "offline"
  salt/states/schedule.py
Labels: Documentation

#65052 [3006.x] adding usermod, groupadd, useradd to requires for rpm
  pkg/rpm/salt.spec
Labels: test:pkg
