Repository saltstack/salt, pull requests merged in 2023-01, with the labels that each got.

#63390 Call `os._exit()` instead of `sys.exit()` on forked processes.
  salt/utils/process.py
Labels: Sulfur v3006.0

#63355 Update pythonnet to 3.0.1 to support Python 3.10
  requirements/static/ci/py3.10/windows.txt
  requirements/static/ci/py3.7/windows.txt
  requirements/static/ci/py3.8/windows.txt
  requirements/static/ci/py3.9/windows.txt
  requirements/static/pkg/py3.10/windows.txt
  requirements/static/pkg/py3.7/windows.txt
  requirements/static/pkg/py3.8/windows.txt
  requirements/static/pkg/py3.9/windows.txt
  requirements/windows.txt
  salt/utils/win_network.py
Labels: Sulfur v3006.0

#63421 Remove unneded pythonwin dirs and tests
  pkg/windows/prep_salt.ps1
Labels: Sulfur v3006.0

#63357 Add state module queue setting from config and max limit
  changelog/31468.added
  changelog/63356.added
  conf/minion
  doc/ref/configuration/minion.rst
  salt/config/__init__.py
  salt/modules/state.py
  tests/pytests/unit/modules/state/test_state.py
  tests/pytests/unit/modules/state/test_top_file_merge.py
Labels: Sulfur v3006.0

#63452 Remove toc link to http tutorial in netapi page
  doc/topics/netapi/index.rst
Labels: Chlorine v3007.0

#63428 Syndics honor MoM acl
  changelog/62618.fixed
  changelog/62933.fixed
  doc/topics/hardening.rst
  doc/topics/topology/syndic.rst
  salt/client/__init__.py
  salt/master.py
  salt/minion.py
  salt/utils/minions.py
  tests/pytests/integration/cli/test_syndic_eauth.py
  tests/pytests/unit/utils/test_minions.py
  tests/unit/test_auth.py
Labels: Sulfur v3006.0

#63427 Fix hidden redis cache failure
  tests/pytests/functional/cache/test_redis.py
Labels: Sulfur v3006.0

#63486 Fix issue with Salt not starting on Windows Server 2016/Windows 10
  salt/utils/win_network.py
Labels: Sulfur v3006.0

#63565 Update regex to allow for Debian family architectures and tarballs when determining version of Salt
  pkg/tests/conftest.py
Labels: Tests, Sulfur v3006.0

#63550 rpm: Include the cli scripts in /usr/bin in the package
  pkg/rpm/salt.spec
Labels: Sulfur v3006.0

#63566 Add pythonw.exe back to the package
  pkg/common/env-cleanup-rules.yml
  pkg/windows/prep_salt.ps1
Labels: Sulfur v3006.0

#63522 Docs: use Salt function to hash passwords
  salt/modules/bsd_shadow.py
  salt/modules/linux_shadow.py
Labels: Documentation

#63558 Mention that a restart is needed
  doc/topics/tutorials/autoaccept_grains.rst
Labels: Documentation

#63561 Guidance on worker_threads value
  doc/ref/configuration/master.rst
Labels: Documentation

#63510 Use default if access to registry key is denied
  changelog/61789.fixed
  salt/utils/win_reg.py
  tests/pytests/unit/utils/test_win_reg.py
  tests/unit/utils/test_win_reg.py
Labels: Sulfur v3006.0
