Repository saltstack/salt, pull requests merged in 2023-08, with the labels that each got.

#64707 [master] Update the bootstrap script to v2023.07.25
  salt/cloud/deploy/bootstrap-salt.sh
Labels: backport:3006.x

#64907 [master] fix nightly repofile path
  tools/pkg/repo/create.py
Labels: Chlorine v3007.0, backport:3006.x

#64883 [master] adding obsoletes to rpm.spec for photon3 packages
  pkg/rpm/salt.spec
Labels: test:pkg

#64976 [3006.x] Restore current path, rather than removing from path
  tests/pytests/functional/states/test_chocolatey_1_2_1.py
  tests/pytests/functional/states/test_chocolatey_latest.py
Labels: test:full

#64986 [3006.x] Bump relenv to 0.13.4
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/scheduled.yml
  .github/workflows/staging.yml
  cicd/shared-gh-workflows-context.yml
Labels: Sulfur v3006.2

#64467 [master] remove salt.payload.Serial
  changelog/64459.removed.md
  salt/payload.py
  tests/pytests/unit/modules/state/test_state.py
  tests/pytests/unit/modules/test_data.py
  tests/pytests/unit/test_auth.py
Labels: Deprecation, Chlorine v3007.0

#64481 [3006.x] Fix for assume role when used salt-cloud to create aws ec2
  changelog/52501.fixed.md
  salt/utils/aws.py
  tests/pytests/unit/utils/test_aws.py
Labels: Sulfur v3006.2

#64378 [3006.x] Fix salt user login shell path in Debian packages
  changelog/64377.fixed.md
  pkg/debian/salt-common.preinst
  pkg/tests/integration/test_salt_user.py
Labels: Chlorine v3007.0, backport:3006.x, Sulfur v3006.2

#65003 [3006.x] Updated semanage fcontext to use --modify if context already exists when adding context
  changelog/64625.fixed.md
  salt/modules/selinux.py
  tests/pytests/unit/modules/file/test_file_selinux.py
Labels: Sulfur v3006.2

#65005 [3006.x] Do not expect : in cached filename
  tests/pytests/functional/states/test_archive.py
  tests/pytests/functional/states/test_file.py
Labels: Sulfur v3006.2

#65007 [3006.x] fix #64973 by adding header that microsoft started enforcing.
  changelog/64973.fixed.md
  salt/modules/msteams.py
  tests/pytests/unit/modules/test_msteams.py
Labels: Sulfur v3006.2

#65009 [3006.x] Fixed KeyError in logs when running a state that fails.
  changelog/64231.fixed.md
  salt/master.py
  salt/minion.py
  salt/utils/event.py
  tests/pytests/integration/states/test_state_test.py
Labels: test:full

#64568 [master] Fix Flaky LazyLoaderRefreshFileMappingTest
  changelog/64567.fixed.md
  salt/loader/lazy.py
  tests/unit/test_loader.py
Labels: Chlorine v3007.0

#64701 [master] make Cloud::vm_config() handle per-VM vm_overrides according to inline docs
  changelog/64610.fixed.md
  salt/cloud/__init__.py
  tests/pytests/unit/cloud/test_cloud.py
Labels: Chlorine v3007.0

#65097 [3006.x] Fix `module has no attribute UpdateProgress`
  tools/release.py
Labels: Sulfur v3006.3
