Repository saltstack/salt, pull requests merged in 2024-02, with the labels that each got.

#65982 [master] Remove unused import causing delays on starting salt-master
  salt/utils/minions.py
Labels: backport:3006.x, backport:3007.x

#66066 [3006.x] Increase timeouts on problematic tests
  tests/integration/modules/test_decorators.py
  tests/integration/modules/test_saltcheck.py
  tests/integration/ssh/test_state.py
  tests/pytests/functional/modules/test_ansiblegate.py
  tests/pytests/integration/cli/test_matcher.py
  tests/pytests/integration/cli/test_salt_deltaproxy.py
Labels: test:full, test:pkg

#66063 [3006.x] Fix default request channel timeout regression
  changelog/66061.fixed.md
  salt/config/__init__.py
Labels: test:full

#66072 [3006.x] Update deltaproxy test timeout
  tests/pytests/integration/cli/test_salt_deltaproxy.py
Labels: test:full

#66092 [3006.x] Try disconnecting while we wait
  salt/modules/mac_assistive.py
Labels: test:full
