Repository saltstack/salt, pull requests merged in 2024-01, with the labels that each got.

#65625 [3006.x] s3fs: add settings s3_sync_on_update and s3_cache_expire
  salt/fileserver/s3fs.py
Labels: Sulfur v3006.6

#63453 Update note around password field on user.present wrt Windows
  salt/states/user.py
Labels: Documentation, Pending-Discussion, doc-correction, doc-rework, docstring-update

#63347 Add context aware change handling for file.managed state module function
  changelog/63328.added.md
  salt/modules/file.py
  salt/state.py
  salt/states/file.py
  salt/utils/stringutils.py
  tests/pytests/integration/states/test_file.py
  tests/pytests/unit/utils/test_stringutils.py
Labels: test:full, Argon v3008.0
