Repository saltstack/salt, pull requests merged in 2025-02, with the labels that each got.

#67723 [3006.x]Fix tech-debt for Git Pillar data with os.walk
  changelog/67733.fixed.md
  salt/utils/gitfs.py
Labels: test:full, test:os:all

#67152 [3006.x] fix yumpkg for Python <3.8
  changelog/67091.fixed.md
  salt/modules/yumpkg.py
Labels: test:full

#67756 Corrected the issue number for changelog file
  changelog/67722.fixed.md
Labels: doc-rework

#67771 Getting nightly builds running again for 3006.x
  salt/_logging/impl.py
Labels: test:full, test:os:all

#67734 Set virtual grain in Podman systemd container
  changelog/67733.fixed.md
  salt/grains/core.py
  tests/pytests/unit/grains/test_core.py
Labels: test:full
